SUBROUTINE APL_ARPEGE_INIT_SURFEX_PARALLEL (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC,  &
& YDCPG_GPAR, YDMF_PHYS, YDVARS, YDMODEL, YD_PALBD, YD_PALBP, YD_PFLU_EMIS, YD_PSGROUPEL, YD_PSRAIN, YD_PSSNOW, YD_PTSN)
  
  !**** *APL_ARPEGE_INIT_SURFEX*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  USE ACPY_MOD
  USE STACK_MOD
  USE YOMPARALLELMETHOD
  USE FIELD_ACCESS_MODULE
  USE FIELD_FACTORY_MODULE
  USE FIELD_MODULE
#include "stack.h"
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE PARKIND1, ONLY: JPIM, JPRB
  
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE CPG_TYPE_MOD, ONLY: CPG_MISC_TYPE, CPG_GPAR_TYPE
  USE MF_PHYS_TYPE_MOD, ONLY: MF_PHYS_TYPE
  USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
  USE TYPE_MODEL, ONLY: MODEL
  
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
  TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
  TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
  TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  CLASS(FIELD_3RB), POINTER :: YD_PALBD
  REAL(KIND=JPRB), POINTER :: PALBD(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YD_PALBP
  REAL(KIND=JPRB), POINTER :: PALBP(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YD_PFLU_EMIS
  REAL(KIND=JPRB), POINTER :: PFLU_EMIS(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PSGROUPEL
  REAL(KIND=JPRB), POINTER :: PSGROUPEL(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PSRAIN
  REAL(KIND=JPRB), POINTER :: PSRAIN(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PSSNOW
  REAL(KIND=JPRB), POINTER :: PSSNOW(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PTSN
  REAL(KIND=JPRB), POINTER :: PTSN(:, :)
  
#include "abor1.intfb.h"
  
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JSG
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
  TYPE(STACK) :: YLSTACK
  INTEGER(KIND=JPIM) :: JBLK
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_ALBDIR(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_ALBSCA(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_GZ0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_GZ0H(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_RAIN(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_SNOW(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_VEMIS(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_VQS(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_GPAR_VTS(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_MISC_QS(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_ALB(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_GZ0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_GZ0H(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_RINDX_T0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_RINDY_T0(:, :)
  
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX', 0, ZHOOK_HANDLE)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  
  
  ! INITIALISATIONS LIEES AU SCHEMA DE SURFACE EXTERNALISE
  
  IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
    
    ! INITIALISATION DU SCHEMA DE SURFACE EXTERNALISE ET DES VARIABLES PSEUDO-HISTORIQUES ASSOCIEES
    
!$ACDC SERIAL {
    
    IF (YDMODEL%YRML_PHY_MF%YRPARAR%NSWB_MNH /= YDMODEL%YRML_PHY_RAD%YRERAD%NSW) THEN
      CALL ABOR1('APL_ARPEGE_INIT_SURFEX: NSWB_MNH /= NSW')
    END IF
    
!$loki end parallel
    
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0', 0, ZHOOK_HANDLE_PARALLEL)
    IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE_INIT_SURFEX_PARALLEL:0')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
      PSGROUPEL => GET_HOST_DATA_RDWR(YD_PSGROUPEL)
      PSRAIN => GET_HOST_DATA_RDWR(YD_PSRAIN)
      PSSNOW => GET_HOST_DATA_RDWR(YD_PSSNOW)
      PTSN => GET_HOST_DATA_RDWR(YD_PTSN)
      Z_YDCPG_GPAR_GZ0 => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_GZ0)
      Z_YDCPG_GPAR_GZ0H => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_GZ0H)
      Z_YDCPG_GPAR_RAIN => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_RAIN)
      Z_YDCPG_GPAR_SNOW => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_SNOW)
      Z_YDCPG_GPAR_VEMIS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VEMIS)
      Z_YDCPG_GPAR_VQS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VQS)
      Z_YDCPG_GPAR_VTS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VTS)
      Z_YDCPG_MISC_QS => GET_HOST_DATA_RDWR(YDCPG_MISC%F_QS)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_OUT_GZ0 => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0)
      Z_YDMF_PHYS_OUT_GZ0H => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0H)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
      CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON ) FIRSTPRIVATE( YLCPG_BNDS )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE(JBLK)
        
        
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          Z_YDMF_PHYS_OUT_GZ0(JLON, JBLK) = Z_YDCPG_GPAR_GZ0(JLON, JBLK)
          Z_YDMF_PHYS_OUT_GZ0H(JLON, JBLK) = Z_YDCPG_GPAR_GZ0H(JLON, JBLK)
          PFLU_EMIS(JLON, JBLK) = Z_YDCPG_GPAR_VEMIS(JLON, JBLK)
          Z_YDCPG_MISC_QS(JLON, JBLK) = Z_YDCPG_GPAR_VQS(JLON, JBLK)
          Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK) = Z_YDCPG_GPAR_VTS(JLON, JBLK)
          PSRAIN(JLON, JBLK) = Z_YDCPG_GPAR_RAIN(JLON, JBLK)
          PSSNOW(JLON, JBLK) = Z_YDCPG_GPAR_SNOW(JLON, JBLK)
          PSGROUPEL(JLON, JBLK) = 0._JPRB
          PTSN(JLON, JBLK) = Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK)
        END DO
        
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_INIT_SURFEX_PARALLEL:0')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
        PSGROUPEL => GET_HOST_DATA_RDWR(YD_PSGROUPEL)
        PSRAIN => GET_HOST_DATA_RDWR(YD_PSRAIN)
        PSSNOW => GET_HOST_DATA_RDWR(YD_PSSNOW)
        PTSN => GET_HOST_DATA_RDWR(YD_PTSN)
        Z_YDCPG_GPAR_GZ0 => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_GZ0)
        Z_YDCPG_GPAR_GZ0H => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_GZ0H)
        Z_YDCPG_GPAR_RAIN => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_RAIN)
        Z_YDCPG_GPAR_SNOW => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_SNOW)
        Z_YDCPG_GPAR_VEMIS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VEMIS)
        Z_YDCPG_GPAR_VQS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VQS)
        Z_YDCPG_GPAR_VTS => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_VTS)
        Z_YDCPG_MISC_QS => GET_HOST_DATA_RDWR(YDCPG_MISC%F_QS)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_OUT_GZ0 => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0)
        Z_YDMF_PHYS_OUT_GZ0H => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0H)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PFLU_EMIS => NULL()
      PSGROUPEL => NULL()
      PSRAIN => NULL()
      PSSNOW => NULL()
      PTSN => NULL()
      Z_YDCPG_GPAR_GZ0 => NULL()
      Z_YDCPG_GPAR_GZ0H => NULL()
      Z_YDCPG_GPAR_RAIN => NULL()
      Z_YDCPG_GPAR_SNOW => NULL()
      Z_YDCPG_GPAR_VEMIS => NULL()
      Z_YDCPG_GPAR_VQS => NULL()
      Z_YDCPG_GPAR_VTS => NULL()
      Z_YDCPG_MISC_QS => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_OUT_GZ0 => NULL()
      Z_YDMF_PHYS_OUT_GZ0H => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:0', 1, ZHOOK_HANDLE_PARALLEL)
    
    
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1', 0, ZHOOK_HANDLE_PARALLEL)
    IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE_INIT_SURFEX_PARALLEL:1')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
      PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
      PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
      Z_YDCPG_GPAR_ALBDIR => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_ALBDIR)
      Z_YDCPG_GPAR_ALBSCA => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_ALBSCA)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
      CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, JSG ) FIRSTPRIVATE( YLCPG_BNDS )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE(JBLK)
        
        ! FMR  radiation => NSW solar bands
        DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            PALBP(JLON, JSG, JBLK) = Z_YDCPG_GPAR_ALBDIR(JLON, JSG, JBLK)
            PALBD(JLON, JSG, JBLK) = Z_YDCPG_GPAR_ALBSCA(JLON, JSG, JBLK)
          END DO
        END DO
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) = 0.0_JPRB
        END DO
        DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) =  &
            & Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + 0.5*(PALBP(JLON, JSG, JBLK) + PALBD(JLON, JSG, JBLK))
          END DO
        END DO
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) =  &
          & Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) / REAL(YDMODEL%YRML_PHY_RAD%YRERAD%NSW, kind=JPRB)
        END DO
        
        
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          IF (PFLU_EMIS(JLON, JBLK) == 0._JPRB) THEN
            PFLU_EMIS(JLON, JBLK) = 0.99_JPRB
            Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK) = 288.0_JPRB
            Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) = 0.1_JPRB
          END IF
        END DO
        
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_INIT_SURFEX_PARALLEL:1')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
        PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
        PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
        Z_YDCPG_GPAR_ALBDIR => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_ALBDIR)
        Z_YDCPG_GPAR_ALBSCA => GET_HOST_DATA_RDWR(YDCPG_GPAR%F_ALBSCA)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => NULL()
      PALBP => NULL()
      PFLU_EMIS => NULL()
      Z_YDCPG_GPAR_ALBDIR => NULL()
      Z_YDCPG_GPAR_ALBSCA => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_OUT_ALB => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:1', 1, ZHOOK_HANDLE_PARALLEL)
    
    ! Define z0;z0h if it's necessary
    
    IF (YDCPG_OPTS%LCONFX) THEN
      
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2', 0, ZHOOK_HANDLE_PARALLEL)
      IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE_INIT_SURFEX_PARALLEL:2')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
        Z_YDMF_PHYS_OUT_GZ0 => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0)
        Z_YDMF_PHYS_OUT_GZ0H => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0H)
        Z_YDVARS_GEOMETRY_RINDX_T0 => GET_HOST_DATA_RDWR(YDVARS%GEOMETRY%RINDX%FT0)
        Z_YDVARS_GEOMETRY_RINDY_T0 => GET_HOST_DATA_RDWR(YDVARS%GEOMETRY%RINDY%FT0)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
        CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK ) FIRSTPRIVATE( YLCPG_BNDS )
        DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
          CALL YLCPG_BNDS%UPDATE(JBLK)
          
          CALL ARO_GROUND_DIAG_Z0(YLCPG_BNDS%KBL, YDCPG_BNDS%KFDIA - YDCPG_BNDS%KIDIA + 1, YLCPG_BNDS%KIDIA,  &
          & YLCPG_BNDS%KFDIA, YDGEOMETRY%YRDIM%NDGUNG, YDGEOMETRY%YRDIM%NDGUXG, YDGEOMETRY%YRDIM%NDLUNG,  &
          & YDGEOMETRY%YRDIM%NDLUXG, Z_YDVARS_GEOMETRY_RINDX_T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JBLK),  &
          & Z_YDVARS_GEOMETRY_RINDY_T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JBLK),  &
          & Z_YDMF_PHYS_OUT_GZ0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JBLK),  &
          & Z_YDMF_PHYS_OUT_GZ0H(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA, JBLK))
          
        END DO
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
        IF (LSYNCHOST('APL_ARPEGE_INIT_SURFEX_PARALLEL:2')) THEN
          IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
          Z_YDMF_PHYS_OUT_GZ0 => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0)
          Z_YDMF_PHYS_OUT_GZ0H => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_GZ0H)
          Z_YDVARS_GEOMETRY_RINDX_T0 => GET_HOST_DATA_RDWR(YDVARS%GEOMETRY%RINDX%FT0)
          Z_YDVARS_GEOMETRY_RINDY_T0 => GET_HOST_DATA_RDWR(YDVARS%GEOMETRY%RINDY%FT0)
          IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
        END IF
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
        Z_YDMF_PHYS_OUT_GZ0 => NULL()
        Z_YDMF_PHYS_OUT_GZ0H => NULL()
        Z_YDVARS_GEOMETRY_RINDX_T0 => NULL()
        Z_YDVARS_GEOMETRY_RINDY_T0 => NULL()
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX_PARALLEL:2', 1, ZHOOK_HANDLE_PARALLEL)
      
    END IF
    
  END IF
  
  
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_INIT_SURFEX', 1, ZHOOK_HANDLE)
  
END SUBROUTINE APL_ARPEGE_INIT_SURFEX_PARALLEL
