SUBROUTINE APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF,  &
& YDMODEL, YD_PALBD, YD_PALBP, PEPS0, YD_PFLU_EMIS, YD_PFLU_NEIJ, YD_PRDG_MU0, YD_PALBDIR)
  
  !**** *APL_ARPEGE_ALBEDO_COMPUTATION*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  USE ACPY_MOD
  USE STACK_MOD
  USE YOMPARALLELMETHOD
  USE FIELD_ACCESS_MODULE
  USE FIELD_FACTORY_MODULE
  USE FIELD_MODULE
#include "stack.h"
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE PARKIND1, ONLY: JPIM, JPRB
  
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE MF_PHYS_TYPE_MOD, ONLY: MF_PHYS_TYPE
  USE MF_PHYS_SURFACE_TYPE_MOD, ONLY: MF_PHYS_SURF_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
  TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  CLASS(FIELD_3RB), POINTER :: YD_PALBD
  REAL(KIND=JPRB), POINTER :: PALBD(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YD_PALBP
  REAL(KIND=JPRB), POINTER :: PALBP(:, :, :)
  REAL(KIND=JPRB), INTENT(IN) :: PEPS0
  CLASS(FIELD_2RB), POINTER :: YD_PFLU_EMIS
  REAL(KIND=JPRB), POINTER :: PFLU_EMIS(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PFLU_NEIJ
  REAL(KIND=JPRB), POINTER :: PFLU_NEIJ(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PRDG_MU0
  REAL(KIND=JPRB), POINTER :: PRDG_MU0(:, :)
  CLASS(FIELD_2RB), POINTER :: YD_PALBDIR
  REAL(KIND=JPRB), POINTER :: PALBDIR(:, :)
  
  
  CLASS(FIELD_2RB), POINTER :: YL_ZMERL => NULL()
  REAL(KIND=JPRB), POINTER :: ZMERL(:, :) => NULL()
  REAL(KIND=JPRB) :: ZLAMB
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JSG
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
  TYPE(STACK) :: YLSTACK
  INTEGER(KIND=JPIM) :: JBLK
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_OUT_ALB(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VF_PALBF(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VF_PLSM(:, :)
  
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION', 0, ZHOOK_HANDLE)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  CALL FIELD_NEW(YL_ZMERL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  
  
  IF (.not.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
    
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0', 0, ZHOOK_HANDLE_PARALLEL)
    IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
      PALBDIR => GET_HOST_DATA_RDWR(YD_PALBDIR)
      PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
      PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
      PFLU_NEIJ => GET_HOST_DATA_RDWR(YD_PFLU_NEIJ)
      PRDG_MU0 => GET_HOST_DATA_RDWR(YD_PRDG_MU0)
      ZMERL => GET_HOST_DATA_RDWR(YL_ZMERL)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
      CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, JSG, ZLAMB ) FIRSTPRIVATE( YLCPG_BNDS )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE(JBLK)
        
        !DEC$ IVDEP
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - MAX(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK),  &
          & YDMODEL%YRML_PHY_MF%YRPHY1%ALCRIN))
          PFLU_EMIS(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - YDMODEL%YRML_PHY_MF%YRPHY1%EMCRIN)
        END DO
        
        IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAYFM) THEN
          
          ! diffuse and direct (parallel) albedo in NSW solar intervals
          
          !DEC$ IVDEP
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            ZMERL(JLON, JBLK) = (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB - MAX(0.0_JPRB,  &
            & SIGN(1.0_JPRB, YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL - Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK))))
            PFLU_EMIS(JLON, JBLK) = PFLU_EMIS(JLON, JBLK)*Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) + ZMERL(JLON, JBLK) &
            & *YDMODEL%YRML_PHY_MF%YRPHY1%EMMMER + (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB -  &
            & ZMERL(JLON, JBLK))*YDMODEL%YRML_PHY_MF%YRPHY1%EMMGLA
          END DO
          DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
            DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
              PALBD(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *YDMODEL%YRML_PHY_MF%YRPHY1%ALBMED
              PALBP(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *MAX(0.037_JPRB / (1.1_JPRB*PRDG_MU0(JLON, JBLK)**1.4_JPRB + 0.15_JPRB), PEPS0)
            END DO
          END DO
          
        ELSE IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAY) THEN
          
          ! direct (parallel) albedo for ACRANEB/ACRANEB2, Geleyn's formula
          ! with given proportion of Lambertian scattering
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            IF (Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) < 0.5_JPRB .and. Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK) >=  &
            & YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL) THEN
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_WATER                ! water surface (open sea)
            ELSE
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_SOLID                ! solid surface (frozen sea or land)
            END IF
            PALBDIR(JLON, JBLK) = ZLAMB*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + (1._JPRB - ZLAMB)*(1._JPRB +  &
            & 0.5_JPRB*PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB)) / (1.0_JPRB +  &
            & PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB))**2
          END DO
          
        END IF
        
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
        PALBDIR => GET_HOST_DATA_RDWR(YD_PALBDIR)
        PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
        PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
        PFLU_NEIJ => GET_HOST_DATA_RDWR(YD_PFLU_NEIJ)
        PRDG_MU0 => GET_HOST_DATA_RDWR(YD_PRDG_MU0)
        ZMERL => GET_HOST_DATA_RDWR(YL_ZMERL)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
        Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
        Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
        Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => NULL()
      PALBDIR => NULL()
      PALBP => NULL()
      PFLU_EMIS => NULL()
      PFLU_NEIJ => NULL()
      PRDG_MU0 => NULL()
      ZMERL => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_OUT_ALB => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    ELSE IF (LPARALLELMETHOD('OPENMPSINGLECOLUMN', 'APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
      PALBDIR => GET_HOST_DATA_RDWR(YD_PALBDIR)
      PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
      PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
      PFLU_NEIJ => GET_HOST_DATA_RDWR(YD_PFLU_NEIJ)
      PRDG_MU0 => GET_HOST_DATA_RDWR(YD_PRDG_MU0)
      ZMERL => GET_HOST_DATA_RDWR(YL_ZMERL)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, JSG, YLCPG_BNDS, YLSTACK, ZLAMB )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JLON
          YLCPG_BNDS%KFDIA = JLON
          YLSTACK%L8 = stack_l8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U8 = stack_u8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%L4 = stack_l4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U4 = stack_u4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          
          !DEC$ IVDEP
          Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - MAX(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK),  &
          & YDMODEL%YRML_PHY_MF%YRPHY1%ALCRIN))
          PFLU_EMIS(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - YDMODEL%YRML_PHY_MF%YRPHY1%EMCRIN)
          
          IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAYFM) THEN
            
            ! diffuse and direct (parallel) albedo in NSW solar intervals
            
            !DEC$ IVDEP
            ZMERL(JLON, JBLK) = (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB - MAX(0.0_JPRB,  &
            & SIGN(1.0_JPRB, YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL - Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK))))
            PFLU_EMIS(JLON, JBLK) = PFLU_EMIS(JLON, JBLK)*Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) + ZMERL(JLON, JBLK) &
            & *YDMODEL%YRML_PHY_MF%YRPHY1%EMMMER + (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB -  &
            & ZMERL(JLON, JBLK))*YDMODEL%YRML_PHY_MF%YRPHY1%EMMGLA
            DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
              PALBD(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *YDMODEL%YRML_PHY_MF%YRPHY1%ALBMED
              PALBP(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *MAX(0.037_JPRB / (1.1_JPRB*PRDG_MU0(JLON, JBLK)**1.4_JPRB + 0.15_JPRB), PEPS0)
            END DO
            
          ELSE IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAY) THEN
            
            ! direct (parallel) albedo for ACRANEB/ACRANEB2, Geleyn's formula
            ! with given proportion of Lambertian scattering
            IF (Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) < 0.5_JPRB .and. Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK) >=  &
            & YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL) THEN
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_WATER                ! water surface (open sea)
            ELSE
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_SOLID                ! solid surface (frozen sea or land)
            END IF
            PALBDIR(JLON, JBLK) = ZLAMB*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + (1._JPRB - ZLAMB)*(1._JPRB +  &
            & 0.5_JPRB*PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB)) / (1.0_JPRB +  &
            & PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB))**2
            
          END IF
          
        END DO
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
        PALBDIR => GET_HOST_DATA_RDWR(YD_PALBDIR)
        PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
        PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
        PFLU_NEIJ => GET_HOST_DATA_RDWR(YD_PFLU_NEIJ)
        PRDG_MU0 => GET_HOST_DATA_RDWR(YD_PRDG_MU0)
        ZMERL => GET_HOST_DATA_RDWR(YL_ZMERL)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
        Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
        Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
        Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => NULL()
      PALBDIR => NULL()
      PALBP => NULL()
      PFLU_EMIS => NULL()
      PFLU_NEIJ => NULL()
      PRDG_MU0 => NULL()
      ZMERL => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_OUT_ALB => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    ELSE IF (LPARALLELMETHOD('OPENACCSINGLECOLUMN', 'APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => GET_DEVICE_DATA_RDWR(YD_PALBD)
      PALBDIR => GET_DEVICE_DATA_RDWR(YD_PALBDIR)
      PALBP => GET_DEVICE_DATA_RDWR(YD_PALBP)
      PFLU_EMIS => GET_DEVICE_DATA_RDWR(YD_PFLU_EMIS)
      PFLU_NEIJ => GET_DEVICE_DATA_RDWR(YD_PFLU_NEIJ)
      PRDG_MU0 => GET_DEVICE_DATA_RDWR(YD_PRDG_MU0)
      ZMERL => GET_DEVICE_DATA_RDWR(YL_ZMERL)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_DEVICE_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_OUT_ALB => GET_DEVICE_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
!$ACC PARALLEL LOOP GANG PRESENT( PALBD, PALBDIR, PALBP, PFLU_EMIS, PFLU_NEIJ, PRDG_MU0, YDCPG_OPTS, YDMODEL, YSTACK, ZMERL,  &
!$ACC & Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, Z_YDMF_PHYS_OUT_ALB, Z_YDMF_PHYS_SURF_GSD_VF_PALBF,  &
!$ACC & Z_YDMF_PHYS_SURF_GSD_VF_PEMISF, Z_YDMF_PHYS_SURF_GSD_VF_PLSM ) PRIVATE( JBLK ) VECTOR_LENGTH( YDCPG_OPTS%KLON )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
!$ACC LOOP VECTOR PRIVATE( JLON, YLCPG_BNDS, YLSTACK )
        DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JLON
          YLCPG_BNDS%KFDIA = JLON
          YLSTACK%L8 = stack_l8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U8 = stack_u8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%L4 = stack_l4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U4 = stack_u4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          
          !DEC$ IVDEP
          Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK) - MAX(Z_YDMF_PHYS_SURF_GSD_VF_PALBF(JLON, JBLK),  &
          & YDMODEL%YRML_PHY_MF%YRPHY1%ALCRIN))
          PFLU_EMIS(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - PFLU_NEIJ(JLON, JBLK) &
          & *(Z_YDMF_PHYS_SURF_GSD_VF_PEMISF(JLON, JBLK) - YDMODEL%YRML_PHY_MF%YRPHY1%EMCRIN)
          
          IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAYFM) THEN
            
            ! diffuse and direct (parallel) albedo in NSW solar intervals
            
            !DEC$ IVDEP
            ZMERL(JLON, JBLK) = (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB - MAX(0.0_JPRB,  &
            & SIGN(1.0_JPRB, YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL - Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK))))
            PFLU_EMIS(JLON, JBLK) = PFLU_EMIS(JLON, JBLK)*Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) + ZMERL(JLON, JBLK) &
            & *YDMODEL%YRML_PHY_MF%YRPHY1%EMMMER + (1.0_JPRB - Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK))*(1.0_JPRB -  &
            & ZMERL(JLON, JBLK))*YDMODEL%YRML_PHY_MF%YRPHY1%EMMGLA
            DO JSG=1,YDMODEL%YRML_PHY_RAD%YRERAD%NSW
              PALBD(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *YDMODEL%YRML_PHY_MF%YRPHY1%ALBMED
              PALBP(JLON, JSG, JBLK) = (1.0_JPRB - ZMERL(JLON, JBLK))*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + ZMERL(JLON, JBLK) &
              & *MAX(0.037_JPRB / (1.1_JPRB*PRDG_MU0(JLON, JBLK)**1.4_JPRB + 0.15_JPRB), PEPS0)
            END DO
            
          ELSE IF (YDMODEL%YRML_PHY_MF%YRPHY%LRAY) THEN
            
            ! direct (parallel) albedo for ACRANEB/ACRANEB2, Geleyn's formula
            ! with given proportion of Lambertian scattering
            IF (Z_YDMF_PHYS_SURF_GSD_VF_PLSM(JLON, JBLK) < 0.5_JPRB .and. Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(JLON, JBLK) >=  &
            & YDMODEL%YRML_PHY_MF%YRPHY1%TMERGL) THEN
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_WATER                ! water surface (open sea)
            ELSE
              ZLAMB = YDMODEL%YRML_PHY_MF%YRPHY3%RLAMB_SOLID                ! solid surface (frozen sea or land)
            END IF
            PALBDIR(JLON, JBLK) = ZLAMB*Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) + (1._JPRB - ZLAMB)*(1._JPRB +  &
            & 0.5_JPRB*PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB)) / (1.0_JPRB +  &
            & PRDG_MU0(JLON, JBLK)*(1.0_JPRB / Z_YDMF_PHYS_OUT_ALB(JLON, JBLK) - 1.0_JPRB))**2
            
          END IF
          
        END DO
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PALBD => GET_HOST_DATA_RDWR(YD_PALBD)
        PALBDIR => GET_HOST_DATA_RDWR(YD_PALBDIR)
        PALBP => GET_HOST_DATA_RDWR(YD_PALBP)
        PFLU_EMIS => GET_HOST_DATA_RDWR(YD_PFLU_EMIS)
        PFLU_NEIJ => GET_HOST_DATA_RDWR(YD_PFLU_NEIJ)
        PRDG_MU0 => GET_HOST_DATA_RDWR(YD_PRDG_MU0)
        ZMERL => GET_HOST_DATA_RDWR(YL_ZMERL)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_OUT_ALB => GET_HOST_DATA_RDWR(YDMF_PHYS%OUT%F_ALB)
        Z_YDMF_PHYS_SURF_GSD_VF_PALBF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_ALBF)
        Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_EMISF)
        Z_YDMF_PHYS_SURF_GSD_VF_PLSM => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VF%F_LSM)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PALBD => NULL()
      PALBDIR => NULL()
      PALBP => NULL()
      PFLU_EMIS => NULL()
      PFLU_NEIJ => NULL()
      PRDG_MU0 => NULL()
      ZMERL => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_OUT_ALB => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PALBF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PEMISF => NULL()
      Z_YDMF_PHYS_SURF_GSD_VF_PLSM => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL:0', 1, ZHOOK_HANDLE_PARALLEL)
    
  END IF
  
  
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  IF (ASSOCIATED(YL_ZMERL)) CALL FIELD_DELETE(YL_ZMERL)
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_ALBEDO_COMPUTATION', 1, ZHOOK_HANDLE)
  
END SUBROUTINE APL_ARPEGE_ALBEDO_COMPUTATION_PARALLEL
