SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_SURF,  &
& YDMODEL, YD_PAER, YD_PAERINDS)
  
  !**** *APL_ARPEGE_AEROSOLS_FOR_RADIATION*
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  USE ACPY_MOD
  USE STACK_MOD
  USE YOMPARALLELMETHOD
  USE FIELD_ACCESS_MODULE
  USE FIELD_FACTORY_MODULE
  USE FIELD_MODULE
#include "stack.h"
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE PARKIND1, ONLY: JPIM, JPRB
  
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE MF_PHYS_SURFACE_TYPE_MOD, ONLY: MF_PHYS_SURF_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  CLASS(FIELD_4RB), POINTER :: YD_PAER
  REAL(KIND=JPRB), POINTER :: PAER(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YD_PAERINDS
  REAL(KIND=JPRB), POINTER :: PAERINDS(:, :, :)
  
#include "radaer.intfb.h"
#include "radaer_openacc.intfb.h"
  
  CLASS(FIELD_2RB), POINTER :: YL_ZAESEA => NULL()
  REAL(KIND=JPRB), POINTER :: ZAESEA(:, :) => NULL()
  CLASS(FIELD_2RB), POINTER :: YL_ZAELAN => NULL()
  REAL(KIND=JPRB), POINTER :: ZAELAN(:, :) => NULL()
  CLASS(FIELD_2RB), POINTER :: YL_ZAESOO => NULL()
  REAL(KIND=JPRB), POINTER :: ZAESOO(:, :) => NULL()
  CLASS(FIELD_2RB), POINTER :: YL_ZAEDES => NULL()
  REAL(KIND=JPRB), POINTER :: ZAEDES(:, :) => NULL()
  CLASS(FIELD_2RB), POINTER :: YL_ZAESUL => NULL()
  REAL(KIND=JPRB), POINTER :: ZAESUL(:, :) => NULL()
  CLASS(FIELD_2RB), POINTER :: YL_ZAEVOL => NULL()
  REAL(KIND=JPRB), POINTER :: ZAEVOL(:, :) => NULL()
  INTEGER(KIND=JPIM) :: JLON
  LOGICAL :: LLAERO
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS
  TYPE(STACK) :: YLSTACK
  INTEGER(KIND=JPIM) :: JBLK
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_T(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VA_PDES(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VA_PLAN(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VA_PSEA(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDMF_PHYS_SURF_GSD_VA_PSOO(:, :)
  
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION', 0, ZHOOK_HANDLE)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  CALL FIELD_NEW(YL_ZAEDES, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAELAN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAESEA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAESOO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAESUL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAEVOL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%JBLKMAX /), LBOUNDS=(/ 1, YDCPG_OPTS%JBLKMIN /),  &
  & PERSISTENT=.true.)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  
  
  ! COMPUTATION OF AEROSOLS (FOR RADIATION)
  
  LLAERO = YDMODEL%YRML_PHY_MF%YRPHY%LAEROSEA .and. YDMODEL%YRML_PHY_MF%YRPHY%LAEROLAN .and.  &
  & YDMODEL%YRML_PHY_MF%YRPHY%LAEROSOO .and. YDMODEL%YRML_PHY_MF%YRPHY%LAERODES
  
  IF (MOD(YDCPG_OPTS%NSTEP, YDMODEL%YRML_PHY_RAD%YRERAD%NRADFR) == 0 .or. YDMODEL%YRML_PHY_MF%YRPHY%LRAY .and.  &
  & .not.YDMODEL%YRML_PHY_MF%YRPHY%LRSTAER) THEN
    
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER', 0, ZHOOK_HANDLE_PARALLEL)
    IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => GET_HOST_DATA_RDWR(YD_PAER)
      PAERINDS => GET_HOST_DATA_RDWR(YD_PAERINDS)
      ZAEDES => GET_HOST_DATA_RDWR(YL_ZAEDES)
      ZAELAN => GET_HOST_DATA_RDWR(YL_ZAELAN)
      ZAESEA => GET_HOST_DATA_RDWR(YL_ZAESEA)
      ZAESOO => GET_HOST_DATA_RDWR(YL_ZAESOO)
      ZAESUL => GET_HOST_DATA_RDWR(YL_ZAESUL)
      ZAEVOL => GET_HOST_DATA_RDWR(YL_ZAEVOL)
      Z_YDMF_PHYS_BASE_STATE_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
      CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON ) FIRSTPRIVATE( YLCPG_BNDS )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        CALL YLCPG_BNDS%UPDATE(JBLK)
        
        IF (LLAERO) THEN
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            ZAESEA(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSEA(JLON, JBLK)
            ZAELAN(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PLAN(JLON, JBLK)
            ZAESOO(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSOO(JLON, JBLK)
            ZAEDES(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PDES(JLON, JBLK)
          END DO
        ELSE
          DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
            ZAESEA(JLON, JBLK) = 0.0_JPRB
            ZAELAN(JLON, JBLK) = 0.0_JPRB
            ZAESOO(JLON, JBLK) = 0.0_JPRB
            ZAEDES(JLON, JBLK) = 0.0_JPRB
          END DO
        END IF
        
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          ZAESUL(JLON, JBLK) = 0.0_JPRB
        END DO
        DO JLON=YLCPG_BNDS%KIDIA,YLCPG_BNDS%KFDIA
          ZAEVOL(JLON, JBLK) = 0.0_JPRB
        END DO
        
        IF (YDMODEL%YRML_PHY_RAD%YRERAD%NAER /= 0 .and. LLAERO) THEN
          CALL RADAER(YDMODEL%YRML_PHY_RAD%YREAERD, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_MF%YRPHY,  &
          & YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
          & Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF(:, :, JBLK),  &
          & Z_YDMF_PHYS_BASE_STATE_T(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK), ZAESEA(:, JBLK),  &
          & ZAELAN(:, JBLK), ZAESOO(:, JBLK), ZAEDES(:, JBLK), ZAESUL(:, JBLK), ZAEVOL(:, JBLK), PAER(:, :, :, JBLK),  &
          & PAERINDS(:, :, JBLK))
        END IF
        
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PAER => GET_HOST_DATA_RDWR(YD_PAER)
        PAERINDS => GET_HOST_DATA_RDWR(YD_PAERINDS)
        ZAEDES => GET_HOST_DATA_RDWR(YL_ZAEDES)
        ZAELAN => GET_HOST_DATA_RDWR(YL_ZAELAN)
        ZAESEA => GET_HOST_DATA_RDWR(YL_ZAESEA)
        ZAESOO => GET_HOST_DATA_RDWR(YL_ZAESOO)
        ZAESUL => GET_HOST_DATA_RDWR(YL_ZAESUL)
        ZAEVOL => GET_HOST_DATA_RDWR(YL_ZAEVOL)
        Z_YDMF_PHYS_BASE_STATE_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
        Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
        Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
        Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => NULL()
      PAERINDS => NULL()
      ZAEDES => NULL()
      ZAELAN => NULL()
      ZAESEA => NULL()
      ZAESOO => NULL()
      ZAESUL => NULL()
      ZAEVOL => NULL()
      Z_YDMF_PHYS_BASE_STATE_T => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    ELSE IF (LPARALLELMETHOD('OPENMPSINGLECOLUMN', 'APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => GET_HOST_DATA_RDWR(YD_PAER)
      PAERINDS => GET_HOST_DATA_RDWR(YD_PAERINDS)
      ZAEDES => GET_HOST_DATA_RDWR(YL_ZAEDES)
      ZAELAN => GET_HOST_DATA_RDWR(YL_ZAELAN)
      ZAESEA => GET_HOST_DATA_RDWR(YL_ZAESEA)
      ZAESOO => GET_HOST_DATA_RDWR(YL_ZAESOO)
      ZAESUL => GET_HOST_DATA_RDWR(YL_ZAESUL)
      ZAEVOL => GET_HOST_DATA_RDWR(YL_ZAEVOL)
      Z_YDMF_PHYS_BASE_STATE_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
        DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JLON
          YLCPG_BNDS%KFDIA = JLON
          YLSTACK%L8 = stack_l8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U8 = stack_u8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%L4 = stack_l4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U4 = stack_u4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          
          IF (LLAERO) THEN
            ZAESEA(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSEA(JLON, JBLK)
            ZAELAN(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PLAN(JLON, JBLK)
            ZAESOO(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSOO(JLON, JBLK)
            ZAEDES(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PDES(JLON, JBLK)
          ELSE
            ZAESEA(JLON, JBLK) = 0.0_JPRB
            ZAELAN(JLON, JBLK) = 0.0_JPRB
            ZAESOO(JLON, JBLK) = 0.0_JPRB
            ZAEDES(JLON, JBLK) = 0.0_JPRB
          END IF
          
          ZAESUL(JLON, JBLK) = 0.0_JPRB
          ZAEVOL(JLON, JBLK) = 0.0_JPRB
          
          IF (YDMODEL%YRML_PHY_RAD%YRERAD%NAER /= 0 .and. LLAERO) THEN
            CALL RADAER_OPENACC(YDMODEL%YRML_PHY_RAD%YREAERD, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_MF%YRPHY,  &
            & YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
            & Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF(:, :, JBLK),  &
            & Z_YDMF_PHYS_BASE_STATE_T(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK), ZAESEA(:, JBLK),  &
            & ZAELAN(:, JBLK), ZAESOO(:, JBLK), ZAEDES(:, JBLK), ZAESUL(:, JBLK), ZAEVOL(:, JBLK), PAER(:, :, :, JBLK),  &
            & PAERINDS(:, :, JBLK), YDSTACK=YLSTACK)
          END IF
          
        END DO
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PAER => GET_HOST_DATA_RDWR(YD_PAER)
        PAERINDS => GET_HOST_DATA_RDWR(YD_PAERINDS)
        ZAEDES => GET_HOST_DATA_RDWR(YL_ZAEDES)
        ZAELAN => GET_HOST_DATA_RDWR(YL_ZAELAN)
        ZAESEA => GET_HOST_DATA_RDWR(YL_ZAESEA)
        ZAESOO => GET_HOST_DATA_RDWR(YL_ZAESOO)
        ZAESUL => GET_HOST_DATA_RDWR(YL_ZAESUL)
        ZAEVOL => GET_HOST_DATA_RDWR(YL_ZAEVOL)
        Z_YDMF_PHYS_BASE_STATE_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
        Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
        Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
        Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => NULL()
      PAERINDS => NULL()
      ZAEDES => NULL()
      ZAELAN => NULL()
      ZAESEA => NULL()
      ZAESOO => NULL()
      ZAESUL => NULL()
      ZAEVOL => NULL()
      Z_YDMF_PHYS_BASE_STATE_T => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    ELSE IF (LPARALLELMETHOD('OPENACCSINGLECOLUMN', 'APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => GET_DEVICE_DATA_RDWR(YD_PAER)
      PAERINDS => GET_DEVICE_DATA_RDWR(YD_PAERINDS)
      ZAEDES => GET_DEVICE_DATA_RDWR(YL_ZAEDES)
      ZAELAN => GET_DEVICE_DATA_RDWR(YL_ZAELAN)
      ZAESEA => GET_DEVICE_DATA_RDWR(YL_ZAESEA)
      ZAESOO => GET_DEVICE_DATA_RDWR(YL_ZAESOO)
      ZAESUL => GET_DEVICE_DATA_RDWR(YL_ZAESUL)
      ZAEVOL => GET_DEVICE_DATA_RDWR(YL_ZAEVOL)
      Z_YDMF_PHYS_BASE_STATE_T => GET_DEVICE_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_DEVICE_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_DEVICE_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_DEVICE_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_DEVICE_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
!$ACC PARALLEL LOOP GANG PRESENT( PAER, PAERINDS, YDCPG_OPTS, YDMODEL, YSTACK, ZAEDES, ZAELAN, ZAESEA, ZAESOO, ZAESUL,  &
!$ACC & ZAEVOL, Z_YDMF_PHYS_BASE_STATE_T, Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD, Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF,  &
!$ACC & Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T, Z_YDMF_PHYS_SURF_GSD_VA_PDES, Z_YDMF_PHYS_SURF_GSD_VA_PLAN,  &
!$ACC & Z_YDMF_PHYS_SURF_GSD_VA_PSEA, Z_YDMF_PHYS_SURF_GSD_VA_PSOO ) PRIVATE( JBLK ) VECTOR_LENGTH( YDCPG_OPTS%KLON )
      DO JBLK=YDCPG_OPTS%JBLKMIN,YDCPG_OPTS%JBLKMAX
!$ACC LOOP VECTOR PRIVATE( JLON, YLCPG_BNDS, YLSTACK )
        DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
          YLCPG_BNDS%KIDIA = JLON
          YLCPG_BNDS%KFDIA = JLON
          YLSTACK%L8 = stack_l8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U8 = stack_u8(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%L4 = stack_l4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          YLSTACK%U4 = stack_u4(YSTACK, JBLK - YDCPG_OPTS%JBLKMIN + 1, YDCPG_OPTS%KGPBLKS)
          
          IF (LLAERO) THEN
            ZAESEA(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSEA(JLON, JBLK)
            ZAELAN(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PLAN(JLON, JBLK)
            ZAESOO(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PSOO(JLON, JBLK)
            ZAEDES(JLON, JBLK) = Z_YDMF_PHYS_SURF_GSD_VA_PDES(JLON, JBLK)
          ELSE
            ZAESEA(JLON, JBLK) = 0.0_JPRB
            ZAELAN(JLON, JBLK) = 0.0_JPRB
            ZAESOO(JLON, JBLK) = 0.0_JPRB
            ZAEDES(JLON, JBLK) = 0.0_JPRB
          END IF
          
          ZAESUL(JLON, JBLK) = 0.0_JPRB
          ZAEVOL(JLON, JBLK) = 0.0_JPRB
          
          IF (YDMODEL%YRML_PHY_RAD%YRERAD%NAER /= 0 .and. LLAERO) THEN
            CALL RADAER_OPENACC(YDMODEL%YRML_PHY_RAD%YREAERD, YDMODEL%YRML_PHY_RAD%YRERAD, YDMODEL%YRML_PHY_MF%YRPHY,  &
            & YLCPG_BNDS%KIDIA, YLCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
            & Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF(:, :, JBLK),  &
            & Z_YDMF_PHYS_BASE_STATE_T(:, :, JBLK), Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T(:, JBLK), ZAESEA(:, JBLK),  &
            & ZAELAN(:, JBLK), ZAESOO(:, JBLK), ZAEDES(:, JBLK), ZAESUL(:, JBLK), ZAEVOL(:, JBLK), PAER(:, :, :, JBLK),  &
            & PAERINDS(:, :, JBLK), YDSTACK=YLSTACK)
          END IF
          
        END DO
      END DO
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
      IF (LSYNCHOST('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER')) THEN
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
        PAER => GET_HOST_DATA_RDWR(YD_PAER)
        PAERINDS => GET_HOST_DATA_RDWR(YD_PAERINDS)
        ZAEDES => GET_HOST_DATA_RDWR(YL_ZAEDES)
        ZAELAN => GET_HOST_DATA_RDWR(YL_ZAELAN)
        ZAESEA => GET_HOST_DATA_RDWR(YL_ZAESEA)
        ZAESOO => GET_HOST_DATA_RDWR(YL_ZAESOO)
        ZAESUL => GET_HOST_DATA_RDWR(YL_ZAESUL)
        ZAEVOL => GET_HOST_DATA_RDWR(YL_ZAEVOL)
        Z_YDMF_PHYS_BASE_STATE_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%F_T)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYD)
        Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YCPG_PHY%F_PREHYDF)
        Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => GET_HOST_DATA_RDWR(YDMF_PHYS_BASE_STATE%YGSP_RR%F_T)
        Z_YDMF_PHYS_SURF_GSD_VA_PDES => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_DES)
        Z_YDMF_PHYS_SURF_GSD_VA_PLAN => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_LAN)
        Z_YDMF_PHYS_SURF_GSD_VA_PSEA => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SEA)
        Z_YDMF_PHYS_SURF_GSD_VA_PSOO => GET_HOST_DATA_RDWR(YDMF_PHYS_SURF%GSD_VA%F_SOO)
        IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
      END IF
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
      PAER => NULL()
      PAERINDS => NULL()
      ZAEDES => NULL()
      ZAELAN => NULL()
      ZAESEA => NULL()
      ZAESOO => NULL()
      ZAESUL => NULL()
      ZAEVOL => NULL()
      Z_YDMF_PHYS_BASE_STATE_T => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYD => NULL()
      Z_YDMF_PHYS_BASE_STATE_YCPG_PHY_PREHYDF => NULL()
      Z_YDMF_PHYS_BASE_STATE_YGSP_RR_T => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PDES => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PLAN => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSEA => NULL()
      Z_YDMF_PHYS_SURF_GSD_VA_PSOO => NULL()
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL:RADAER', 1, ZHOOK_HANDLE_PARALLEL)
    
  END IF
  
  
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  IF (ASSOCIATED(YL_ZAEDES)) CALL FIELD_DELETE(YL_ZAEDES)
  IF (ASSOCIATED(YL_ZAELAN)) CALL FIELD_DELETE(YL_ZAELAN)
  IF (ASSOCIATED(YL_ZAESEA)) CALL FIELD_DELETE(YL_ZAESEA)
  IF (ASSOCIATED(YL_ZAESOO)) CALL FIELD_DELETE(YL_ZAESOO)
  IF (ASSOCIATED(YL_ZAESUL)) CALL FIELD_DELETE(YL_ZAESUL)
  IF (ASSOCIATED(YL_ZAEVOL)) CALL FIELD_DELETE(YL_ZAEVOL)
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE_AEROSOLS_FOR_RADIATION', 1, ZHOOK_HANDLE)
  
END SUBROUTINE APL_ARPEGE_AEROSOLS_FOR_RADIATION_PARALLEL
