SUBROUTINE APL_ARPEGE (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR,  &
& YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDCPG_SL2, YDVARS, YDMODEL, YDDDH)
  
  !**** *APL_ARPEGE*  - Call ARPEGE physics
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  !     Modifications.
  !     --------------
  !     13-Jul-2022 R. El Khatib Fix initialization of ZQGM
  ! End Modifications
  !-------------------------------------------------------------------------------
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  USE MF_PHYS_TYPE_MOD, ONLY: MF_PHYS_TYPE
  USE CPG_TYPE_MOD, ONLY: CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
  USE CPG_SL2_TYPE_MOD, ONLY: CPG_SL2_TYPE
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE MF_PHYS_SURFACE_TYPE_MOD, ONLY: MF_PHYS_SURF_TYPE
  USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE MF_PHYS_NEXT_STATE_TYPE_MOD, ONLY: MF_PHYS_NEXT_STATE_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE DDH_MIX, ONLY: TYP_DDH
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
  TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
  TYPE(CPG_PHY_TYPE), INTENT(IN) :: YDCPG_PHY0
  TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
  TYPE(CPG_DYN_TYPE), INTENT(IN) :: YDCPG_DYN0
  TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
  TYPE(CPG_SL2_TYPE), INTENT(INOUT) :: YDCPG_SL2
  TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
  
#include "accldia.intfb.h"
#include "acclph.intfb.h"
#include "acdnshf.intfb.h"
#include "acdrag.intfb.h"
#include "acdrme.intfb.h"
#include "acevadcape.intfb.h"
#include "achmt.intfb.h"
#include "achmtls.intfb.h"
#include "acpluis.intfb.h"
#include "acsol.intfb.h"
#include "actqsat.intfb.h"
#include "acvisih.intfb.h"
#include "aplpar_init.intfb.h"
#include "checkmv.intfb.h"
#include "cpphinp.intfb.h"
#include "cpqsol.intfb.h"
#include "mf_phys_bayrad.intfb.h"
#include "mf_phys_corwat.intfb.h"
#include "mf_phys_cvv.intfb.h"
#include "mf_phys_fpl_part1.intfb.h"
#include "mf_phys_fpl_part2.intfb.h"
#include "mf_phys_mocon.intfb.h"
#include "mf_phys_precips.intfb.h"
#include "mf_phys_save_phsurf_part1.intfb.h"
#include "mf_phys_save_phsurf_part2.intfb.h"
#include "mf_phys_transfer.intfb.h"
#include "ppwetpoint.intfb.h"
#include "qngcor.intfb.h"
#include "aplpar_flexdia.intfb.h"
#include "apl_arpege_oceanic_fluxes.intfb.h"
#include "apl_wind_gust.intfb.h"
#include "apl_arpege_shallow_convection_and_turbulence.intfb.h"
#include "apl_arpege_albedo_computation.intfb.h"
#include "apl_arpege_aerosols_for_radiation.intfb.h"
#include "apl_arpege_cloudiness.intfb.h"
#include "apl_arpege_radiation.intfb.h"
#include "apl_arpege_soil_hydro.intfb.h"
#include "apl_arpege_surface.intfb.h"
#include "apl_arpege_deep_convection.intfb.h"
#include "apl_arpege_precipitation.intfb.h"
#include "apl_arpege_hydro_budget.intfb.h"
#include "apl_arpege_surface_update.intfb.h"
#include "apl_arpege_atmosphere_update.intfb.h"
#include "apl_arpege_init.intfb.h"
#include "apl_arpege_init_surfex.intfb.h"
#include "apl_arpege_dprecips.intfb.h"
  
  
  CLASS(FIELD_4RB), POINTER :: YL_ZDIFEXT
  REAL(KIND=JPRB), POINTER :: ZDIFEXT(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_INLAB_CVPP
  INTEGER(KIND=JPIM), POINTER :: INLAB_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTROV
  REAL(KIND=JPRB), POINTER :: ZXTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXUROV
  REAL(KIND=JPRB), POINTER :: ZXUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMRIPP
  REAL(KIND=JPRB), POINTER :: ZMRIPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKTROV
  REAL(KIND=JPRB), POINTER :: ZKTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKUROV
  REAL(KIND=JPRB), POINTER :: ZKUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNBVNO
  REAL(KIND=JPRB), POINTER :: ZNBVNO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQROV
  REAL(KIND=JPRB), POINTER :: ZKQROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQLROV
  REAL(KIND=JPRB), POINTER :: ZKQLROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS
  REAL(KIND=JPRB), POINTER :: ZNEBS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS
  REAL(KIND=JPRB), POINTER :: ZQLIS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS0
  REAL(KIND=JPRB), POINTER :: ZNEBS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS0
  REAL(KIND=JPRB), POINTER :: ZQLIS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBC0
  REAL(KIND=JPRB), POINTER :: ZNEBC0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBDIFF
  REAL(KIND=JPRB), POINTER :: ZNEBDIFF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBCH
  REAL(KIND=JPRB), POINTER :: ZNEBCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZUNEBH
  REAL(KIND=JPRB), POINTER :: ZUNEBH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPCOR
  REAL(KIND=JPRB), POINTER :: ZFPCOR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPOID
  REAL(KIND=JPRB), POINTER :: ZPOID(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQV
  REAL(KIND=JPRB), POINTER :: ZQV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQI
  REAL(KIND=JPRB), POINTER :: ZQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQL
  REAL(KIND=JPRB), POINTER :: ZQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQR
  REAL(KIND=JPRB), POINTER :: ZQR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQS
  REAL(KIND=JPRB), POINTER :: ZQS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENHA
  REAL(KIND=JPRB), POINTER :: ZTENHA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENQVA
  REAL(KIND=JPRB), POINTER :: ZTENQVA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCP
  REAL(KIND=JPRB), POINTER :: ZCP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSL
  REAL(KIND=JPRB), POINTER :: ZFPLSL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSN
  REAL(KIND=JPRB), POINTER :: ZFPLSN(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQL
  REAL(KIND=JPRB), POINTER :: ZSEDIQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQI
  REAL(KIND=JPRB), POINTER :: ZSEDIQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPQ
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPS
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPU
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPV
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFQ
  REAL(KIND=JPRB), POINTER :: ZEDMFQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFS
  REAL(KIND=JPRB), POINTER :: ZEDMFS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFU
  REAL(KIND=JPRB), POINTER :: ZEDMFU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFV
  REAL(KIND=JPRB), POINTER :: ZEDMFV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMF_UP
  REAL(KIND=JPRB), POINTER :: ZMF_UP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPL
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPI
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRODTH_CVPP
  REAL(KIND=JPRB), POINTER :: ZPRODTH_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDE2MR
  REAL(KIND=JPRB), POINTER :: ZDE2MR(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXDROV
  REAL(KIND=JPRB), POINTER :: ZXDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXHROV
  REAL(KIND=JPRB), POINTER :: ZXHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZUGST
  REAL(KIND=JPRB), POINTER :: ZUGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZVGST
  REAL(KIND=JPRB), POINTER :: ZVGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCDROV
  REAL(KIND=JPRB), POINTER :: ZCDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCHROV
  REAL(KIND=JPRB), POINTER :: ZCHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDQSTS
  REAL(KIND=JPRB), POINTER :: ZDQSTS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZGWDCS
  REAL(KIND=JPRB), POINTER :: ZGWDCS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHQ
  REAL(KIND=JPRB), POINTER :: ZHQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHU
  REAL(KIND=JPRB), POINTER :: ZHU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHTR
  REAL(KIND=JPRB), POINTER :: ZHTR(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRTI
  REAL(KIND=JPRB), POINTER :: ZRTI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHI
  REAL(KIND=JPRB), POINTER :: ZDPHI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPRS
  REAL(KIND=JPRB), POINTER :: ZPRS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSTAB
  REAL(KIND=JPRB), POINTER :: ZSTAB(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWFC
  REAL(KIND=JPRB), POINTER :: ZWFC(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWPMX
  REAL(KIND=JPRB), POINTER :: ZWPMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWLMX
  REAL(KIND=JPRB), POINTER :: ZWLMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSEQ
  REAL(KIND=JPRB), POINTER :: ZWSEQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSMX
  REAL(KIND=JPRB), POINTER :: ZWSMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWWILT
  REAL(KIND=JPRB), POINTER :: ZWWILT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZC3
  REAL(KIND=JPRB), POINTER :: ZC3(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCG
  REAL(KIND=JPRB), POINTER :: ZCG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCN
  REAL(KIND=JPRB), POINTER :: ZCN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJG
  REAL(KIND=JPRB), POINTER :: ZNEIJG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJV
  REAL(KIND=JPRB), POINTER :: ZNEIJV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPCLS
  REAL(KIND=JPRB), POINTER :: ZPCLS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZBLH
  REAL(KIND=JPRB), POINTER :: ZBLH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQO3
  REAL(KIND=JPRB), POINTER :: ZQO3(:, :, :)
  CLASS(FIELD_4RB), POINTER :: YL_ZAER
  REAL(KIND=JPRB), POINTER :: ZAER(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZAERINDS
  REAL(KIND=JPRB), POINTER :: ZAERINDS(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIV
  REAL(KIND=JPRB), POINTER :: ZDPHIV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIT
  REAL(KIND=JPRB), POINTER :: ZDPHIT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTRSOD
  REAL(KIND=JPRB), POINTER :: ZTRSOD(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCEMTR
  REAL(KIND=JPRB), POINTER :: ZCEMTR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCTRSO
  REAL(KIND=JPRB), POINTER :: ZCTRSO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBD
  REAL(KIND=JPRB), POINTER :: ZALBD(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBP
  REAL(KIND=JPRB), POINTER :: ZALBP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIR
  REAL(KIND=JPRB), POINTER :: ZSFSWDIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIF
  REAL(KIND=JPRB), POINTER :: ZSFSWDIF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIR
  REAL(KIND=JPRB), POINTER :: ZTRSODIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIF
  REAL(KIND=JPRB), POINTER :: ZTRSODIF(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSUDU
  REAL(KIND=JPRB), POINTER :: ZSUDU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTHETAVS
  REAL(KIND=JPRB), POINTER :: ZTHETAVS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZGEOSLC
  REAL(KIND=JPRB), POINTER :: ZGEOSLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENT
  REAL(KIND=JPRB), POINTER :: ZTENT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTHETAV
  REAL(KIND=JPRB), POINTER :: ZTHETAV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFN
  REAL(KIND=JPRB), POINTER :: ZCOEFN(:, :, :)
  
  ! LOCAL ARRAYS FOR ACVPPKF
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVPP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEB_CVPP
  REAL(KIND=JPRB), POINTER :: ZNEB_CVPP(:, :, :)
  
  ! Implicit coupling coefficients
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBTH
  REAL(KIND=JPRB), POINTER :: ZCFBTH(:, :, :)
  REAL(KIND=JPRB) :: ZDTMSE
  REAL(KIND=JPRB) :: ZRHGMT
  REAL(KIND=JPRB) :: ZSTATI
  CLASS(FIELD_3RB), POINTER :: YL_ZCFATH
  REAL(KIND=JPRB), POINTER :: ZCFATH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFAU
  REAL(KIND=JPRB), POINTER :: ZCFAU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBU
  REAL(KIND=JPRB), POINTER :: ZCFBU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBV
  REAL(KIND=JPRB), POINTER :: ZCFBV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSRAIN
  REAL(KIND=JPRB), POINTER :: ZSRAIN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSSNOW
  REAL(KIND=JPRB), POINTER :: ZSSNOW(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSGROUPEL
  REAL(KIND=JPRB), POINTER :: ZSGROUPEL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTSN
  REAL(KIND=JPRB), POINTER :: ZTSN(:, :)
  
  !         ACFLUSO (ECUME) local variable
  CLASS(FIELD_2RB), POINTER :: YL_ZCE
  REAL(KIND=JPRB), POINTER :: ZCE(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCEROV
  REAL(KIND=JPRB), POINTER :: ZCEROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCRTI
  REAL(KIND=JPRB), POINTER :: ZCRTI(:, :)
  
  !        New ACDIFV1 local variable
  CLASS(FIELD_3RB), POINTER :: YL_ZXURO
  REAL(KIND=JPRB), POINTER :: ZXURO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXQRO
  REAL(KIND=JPRB), POINTER :: ZXQRO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTRO
  REAL(KIND=JPRB), POINTER :: ZXTRO(:, :, :)
  
  !        New ACNORGWD local variables
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWU
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWV
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWV(:, :, :)
  
  !    TKE+ for ACCLDIA
  CLASS(FIELD_3RB), POINTER :: YL_ZTKE1
  REAL(KIND=JPRB), POINTER :: ZTKE1(:, :, :)
  
  !   For ACVISIH
  CLASS(FIELD_3RB), POINTER :: YL_ZQGM
  REAL(KIND=JPRB), POINTER :: ZQGM(:, :, :)
  
  
  !        New ARP_GROUND_PARAM local variable
  CLASS(FIELD_3RB), POINTER :: YL_ZALPHA1
  REAL(KIND=JPRB), POINTER :: ZALPHA1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFA
  REAL(KIND=JPRB), POINTER :: ZCOEFA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZLVT
  REAL(KIND=JPRB), POINTER :: ZLVT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQICE
  REAL(KIND=JPRB), POINTER :: ZQICE(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWQ
  REAL(KIND=JPRB), POINTER :: ZDIFWQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWS
  REAL(KIND=JPRB), POINTER :: ZDIFWS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVI
  REAL(KIND=JPRB), POINTER :: ZSC_FEVI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVN
  REAL(KIND=JPRB), POINTER :: ZSC_FEVN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLL
  REAL(KIND=JPRB), POINTER :: ZSC_FCLL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLN
  REAL(KIND=JPRB), POINTER :: ZSC_FCLN(:, :)
  
  !           TRAJECTORY (For diffusion !) local VARIABLES
  CLASS(FIELD_3RB), POINTER :: YL_ZTRAJGWD
  REAL(KIND=JPRB), POINTER :: ZTRAJGWD(:, :, :)
  
  CLASS(FIELD_2RB), POINTER :: YL_ZAIPCMT
  REAL(KIND=JPRB), POINTER :: ZAIPCMT(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQIC
  REAL(KIND=JPRB), POINTER :: ZQIC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLC
  REAL(KIND=JPRB), POINTER :: ZQLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQC_DET_PCMT
  REAL(KIND=JPRB), POINTER :: ZQC_DET_PCMT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDCAPE
  REAL(KIND=JPRB), POINTER :: ZDCAPE(:, :)
  
  ! ACRANEB/ACRANEB2 local variables
  CLASS(FIELD_2RB), POINTER :: YL_ZDECRD
  REAL(KIND=JPRB), POINTER :: ZDECRD(:, :)
  
  ! Precipitation type diagnostics
  CLASS(FIELD_2RB), POINTER :: YL_IMOC_CLPH
  INTEGER(KIND=JPIM), POINTER :: IMOC_CLPH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QRCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QRCONV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QSCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QSCONV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C1
  REAL(KIND=JPRB), POINTER :: ZDSA_C1(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C2
  REAL(KIND=JPRB), POINTER :: ZDSA_C2(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_CPS
  REAL(KIND=JPRB), POINTER :: ZDSA_CPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_LHS
  REAL(KIND=JPRB), POINTER :: ZDSA_LHS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_RS
  REAL(KIND=JPRB), POINTER :: ZDSA_RS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CDN
  REAL(KIND=JPRB), POINTER :: ZFLU_CDN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CD
  REAL(KIND=JPRB), POINTER :: ZFLU_CD(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CH
  REAL(KIND=JPRB), POINTER :: ZFLU_CH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_EMIS
  REAL(KIND=JPRB), POINTER :: ZFLU_EMIS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_FEVI
  REAL(KIND=JPRB), POINTER :: ZFLU_FEVI(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_NEIJ
  REAL(KIND=JPRB), POINTER :: ZFLU_NEIJ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_QSATS
  REAL(KIND=JPRB), POINTER :: ZFLU_QSATS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_QSAT
  REAL(KIND=JPRB), POINTER :: ZFLU_QSAT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_VEG
  REAL(KIND=JPRB), POINTER :: ZFLU_VEG(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_FRMQ
  REAL(KIND=JPRB), POINTER :: ZMSC_FRMQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LH
  REAL(KIND=JPRB), POINTER :: ZMSC_LH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LSCPE
  REAL(KIND=JPRB), POINTER :: ZMSC_LSCPE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_QW
  REAL(KIND=JPRB), POINTER :: ZMSC_QW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_TW
  REAL(KIND=JPRB), POINTER :: ZMSC_TW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB1
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB2
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB3
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB3(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLCH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLSH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLSH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKEI
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKEI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKE
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS2
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_CVGQ
  REAL(KIND=JPRB), POINTER :: ZRDG_CVGQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_LCVQ
  REAL(KIND=JPRB), POINTER :: ZRDG_LCVQ(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0LU
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0LU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0M
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0M(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0N
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0N(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_DDAL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_DDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_ENTCH
  REAL(KIND=JPRB), POINTER :: ZSAV_ENTCH(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_FHPS
  REAL(KIND=JPRB), POINTER :: ZSAV_FHPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0F
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0F(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0HF
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0HF(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_HV
  REAL(KIND=JPRB), POINTER :: ZSAV_HV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_PBLH
  REAL(KIND=JPRB), POINTER :: ZSAV_PBLH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_QSH
  REAL(KIND=JPRB), POINTER :: ZSAV_QSH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_UDAL(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_UDGRO
  REAL(KIND=JPRB), POINTER :: ZSAV_UDGRO(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_UDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UNEBH
  REAL(KIND=JPRB), POINTER :: ZSAV_UNEBH(:, :, :)
  
  INTEGER(KIND=JPIM) :: INSTEP_DEB
  INTEGER(KIND=JPIM) :: INSTEP_FIN
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JSPP
  LOGICAL :: LLCLS
  LOGICAL :: LLHMT
  LOGICAL :: LLREDPR
  REAL(KIND=JPRB) :: ZEPS0
  REAL(KIND=JPRB) :: ZEPSNEB
  REAL(KIND=JPRB) :: ZRVMD
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_GEMU_T0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_GELAM_T0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_U_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_V_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_DL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_DM(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_DL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_DM(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_PHY0_XYB_RDELP(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_DYN0_CTY_EVEL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_T0(:, :, :)
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  CALL FIELD_NEW(YL_ZDIFEXT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_INLAB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMRIPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNBVNO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQLROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBC0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBDIFF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPCOR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPOID, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENHA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENQVA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMF_UP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRODTH_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDE2MR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZVGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDQSTS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGWDCS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHTR, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSTAB, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWFC, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWPMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWLMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSEQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWWILT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZC3, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPCLS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQO3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAER, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAERINDS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSOD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEMTR, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCTRSO, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSUDU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAVS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGEOSLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBTH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFATH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFAU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSRAIN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSSNOW, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSGROUPEL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTSN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXURO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXQRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTKE1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQGM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALPHA1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZLVT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQICE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRAJGWD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAIPCMT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQIC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQC_DET_PCMT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDCAPE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDECRD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_IMOC_CLPH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QRCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QSCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C1, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C2, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_CPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_LHS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_RS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CDN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_EMIS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KTSSG + 1 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_NEIJ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSATS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSAT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_VEG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_FRMQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LSCPE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_QW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_TW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLSH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKEI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC2 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_CVGQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_LCVQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0LU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0M, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0N, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_ENTCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_FHPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0F, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0HF, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_HV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_PBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_QSH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDGRO, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  
  
  
  
  
  
  <PragmaRegion::>
    
    CALL CPPHINP(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDVARS%GEOMETRY%GEMU%T0, YDVARS%GEOMETRY%GELAM%T0,  &
    & YDVARS%U%T0, YDVARS%V%T0, YDVARS%Q%T0, YDVARS%Q%DL, YDVARS%Q%DM, YDVARS%CVGQ%DL, YDVARS%CVGQ%DM, YDCPG_PHY0%XYB%RDELP,  &
    & YDCPG_DYN0%CTY%EVEL, YDVARS%CVGQ%T0, ZRDG_MU0, ZRDG_MU0LU, ZRDG_MU0M, ZRDG_MU0N, ZRDG_CVGQ)
    
  
  
  
  
END SUBROUTINE APL_ARPEGE
