SUBROUTINE APL_ARPEGE (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR,  &
& YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDCPG_SL2, YDVARS, YDMODEL, YDDDH)
  
  !**** *APL_ARPEGE*  - Call ARPEGE physics
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  !     Modifications.
  !     --------------
  !     13-Jul-2022 R. El Khatib Fix initialization of ZQGM
  ! End Modifications
  !-------------------------------------------------------------------------------
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  USE MF_PHYS_TYPE_MOD, ONLY: MF_PHYS_TYPE
  USE CPG_TYPE_MOD, ONLY: CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
  USE CPG_SL2_TYPE_MOD, ONLY: CPG_SL2_TYPE
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE MF_PHYS_SURFACE_TYPE_MOD, ONLY: MF_PHYS_SURF_TYPE
  USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE MF_PHYS_NEXT_STATE_TYPE_MOD, ONLY: MF_PHYS_NEXT_STATE_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE DDH_MIX, ONLY: TYP_DDH
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
  TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
  TYPE(CPG_PHY_TYPE), INTENT(IN) :: YDCPG_PHY0
  TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
  TYPE(CPG_DYN_TYPE), INTENT(IN) :: YDCPG_DYN0
  TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
  TYPE(CPG_SL2_TYPE), INTENT(INOUT) :: YDCPG_SL2
  TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
  
#include "accldia.intfb.h"
#include "acclph.intfb.h"
#include "acdnshf.intfb.h"
#include "acdrag.intfb.h"
#include "acdrme.intfb.h"
#include "acevadcape.intfb.h"
#include "achmt.intfb.h"
#include "achmtls.intfb.h"
#include "acpluis.intfb.h"
#include "acsol.intfb.h"
#include "actqsat.intfb.h"
#include "acvisih.intfb.h"
#include "aplpar_init.intfb.h"
#include "checkmv.intfb.h"
#include "cpphinp.intfb.h"
#include "cpqsol.intfb.h"
#include "mf_phys_bayrad.intfb.h"
#include "mf_phys_corwat.intfb.h"
#include "mf_phys_cvv.intfb.h"
#include "mf_phys_fpl_part1.intfb.h"
#include "mf_phys_fpl_part2.intfb.h"
#include "mf_phys_mocon.intfb.h"
#include "mf_phys_precips.intfb.h"
#include "mf_phys_save_phsurf_part1.intfb.h"
#include "mf_phys_save_phsurf_part2.intfb.h"
#include "mf_phys_transfer.intfb.h"
#include "ppwetpoint.intfb.h"
#include "qngcor.intfb.h"
#include "aplpar_flexdia.intfb.h"
#include "apl_arpege_oceanic_fluxes.intfb.h"
#include "apl_wind_gust.intfb.h"
#include "apl_arpege_shallow_convection_and_turbulence.intfb.h"
#include "apl_arpege_albedo_computation.intfb.h"
#include "apl_arpege_aerosols_for_radiation.intfb.h"
#include "apl_arpege_cloudiness.intfb.h"
#include "apl_arpege_radiation.intfb.h"
#include "apl_arpege_soil_hydro.intfb.h"
#include "apl_arpege_surface.intfb.h"
#include "apl_arpege_deep_convection.intfb.h"
#include "apl_arpege_precipitation.intfb.h"
#include "apl_arpege_hydro_budget.intfb.h"
#include "apl_arpege_surface_update.intfb.h"
#include "apl_arpege_atmosphere_update.intfb.h"
#include "apl_arpege_init.intfb.h"
#include "apl_arpege_init_surfex.intfb.h"
#include "apl_arpege_dprecips.intfb.h"
  
  
  CLASS(FIELD_4RB), POINTER :: YL_ZDIFEXT
  REAL(KIND=JPRB), POINTER :: ZDIFEXT(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_INLAB_CVPP
  INTEGER(KIND=JPIM), POINTER :: INLAB_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTROV
  REAL(KIND=JPRB), POINTER :: ZXTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXUROV
  REAL(KIND=JPRB), POINTER :: ZXUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMRIPP
  REAL(KIND=JPRB), POINTER :: ZMRIPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKTROV
  REAL(KIND=JPRB), POINTER :: ZKTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKUROV
  REAL(KIND=JPRB), POINTER :: ZKUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNBVNO
  REAL(KIND=JPRB), POINTER :: ZNBVNO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQROV
  REAL(KIND=JPRB), POINTER :: ZKQROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQLROV
  REAL(KIND=JPRB), POINTER :: ZKQLROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS
  REAL(KIND=JPRB), POINTER :: ZNEBS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS
  REAL(KIND=JPRB), POINTER :: ZQLIS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS0
  REAL(KIND=JPRB), POINTER :: ZNEBS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS0
  REAL(KIND=JPRB), POINTER :: ZQLIS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBC0
  REAL(KIND=JPRB), POINTER :: ZNEBC0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBDIFF
  REAL(KIND=JPRB), POINTER :: ZNEBDIFF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBCH
  REAL(KIND=JPRB), POINTER :: ZNEBCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZUNEBH
  REAL(KIND=JPRB), POINTER :: ZUNEBH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPCOR
  REAL(KIND=JPRB), POINTER :: ZFPCOR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPOID
  REAL(KIND=JPRB), POINTER :: ZPOID(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQV
  REAL(KIND=JPRB), POINTER :: ZQV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQI
  REAL(KIND=JPRB), POINTER :: ZQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQL
  REAL(KIND=JPRB), POINTER :: ZQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQR
  REAL(KIND=JPRB), POINTER :: ZQR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQS
  REAL(KIND=JPRB), POINTER :: ZQS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENHA
  REAL(KIND=JPRB), POINTER :: ZTENHA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENQVA
  REAL(KIND=JPRB), POINTER :: ZTENQVA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCP
  REAL(KIND=JPRB), POINTER :: ZCP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSL
  REAL(KIND=JPRB), POINTER :: ZFPLSL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSN
  REAL(KIND=JPRB), POINTER :: ZFPLSN(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQL
  REAL(KIND=JPRB), POINTER :: ZSEDIQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQI
  REAL(KIND=JPRB), POINTER :: ZSEDIQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPQ
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPS
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPU
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPV
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFQ
  REAL(KIND=JPRB), POINTER :: ZEDMFQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFS
  REAL(KIND=JPRB), POINTER :: ZEDMFS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFU
  REAL(KIND=JPRB), POINTER :: ZEDMFU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFV
  REAL(KIND=JPRB), POINTER :: ZEDMFV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMF_UP
  REAL(KIND=JPRB), POINTER :: ZMF_UP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPL
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPI
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRODTH_CVPP
  REAL(KIND=JPRB), POINTER :: ZPRODTH_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDE2MR
  REAL(KIND=JPRB), POINTER :: ZDE2MR(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXDROV
  REAL(KIND=JPRB), POINTER :: ZXDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXHROV
  REAL(KIND=JPRB), POINTER :: ZXHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZUGST
  REAL(KIND=JPRB), POINTER :: ZUGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZVGST
  REAL(KIND=JPRB), POINTER :: ZVGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCDROV
  REAL(KIND=JPRB), POINTER :: ZCDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCHROV
  REAL(KIND=JPRB), POINTER :: ZCHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDQSTS
  REAL(KIND=JPRB), POINTER :: ZDQSTS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZGWDCS
  REAL(KIND=JPRB), POINTER :: ZGWDCS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHQ
  REAL(KIND=JPRB), POINTER :: ZHQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHU
  REAL(KIND=JPRB), POINTER :: ZHU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHTR
  REAL(KIND=JPRB), POINTER :: ZHTR(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRTI
  REAL(KIND=JPRB), POINTER :: ZRTI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHI
  REAL(KIND=JPRB), POINTER :: ZDPHI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPRS
  REAL(KIND=JPRB), POINTER :: ZPRS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSTAB
  REAL(KIND=JPRB), POINTER :: ZSTAB(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWFC
  REAL(KIND=JPRB), POINTER :: ZWFC(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWPMX
  REAL(KIND=JPRB), POINTER :: ZWPMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWLMX
  REAL(KIND=JPRB), POINTER :: ZWLMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSEQ
  REAL(KIND=JPRB), POINTER :: ZWSEQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSMX
  REAL(KIND=JPRB), POINTER :: ZWSMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWWILT
  REAL(KIND=JPRB), POINTER :: ZWWILT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZC3
  REAL(KIND=JPRB), POINTER :: ZC3(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCG
  REAL(KIND=JPRB), POINTER :: ZCG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCN
  REAL(KIND=JPRB), POINTER :: ZCN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJG
  REAL(KIND=JPRB), POINTER :: ZNEIJG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJV
  REAL(KIND=JPRB), POINTER :: ZNEIJV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPCLS
  REAL(KIND=JPRB), POINTER :: ZPCLS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZBLH
  REAL(KIND=JPRB), POINTER :: ZBLH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQO3
  REAL(KIND=JPRB), POINTER :: ZQO3(:, :, :)
  CLASS(FIELD_4RB), POINTER :: YL_ZAER
  REAL(KIND=JPRB), POINTER :: ZAER(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZAERINDS
  REAL(KIND=JPRB), POINTER :: ZAERINDS(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIV
  REAL(KIND=JPRB), POINTER :: ZDPHIV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIT
  REAL(KIND=JPRB), POINTER :: ZDPHIT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTRSOD
  REAL(KIND=JPRB), POINTER :: ZTRSOD(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCEMTR
  REAL(KIND=JPRB), POINTER :: ZCEMTR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCTRSO
  REAL(KIND=JPRB), POINTER :: ZCTRSO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBD
  REAL(KIND=JPRB), POINTER :: ZALBD(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBP
  REAL(KIND=JPRB), POINTER :: ZALBP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIR
  REAL(KIND=JPRB), POINTER :: ZSFSWDIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIF
  REAL(KIND=JPRB), POINTER :: ZSFSWDIF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIR
  REAL(KIND=JPRB), POINTER :: ZTRSODIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIF
  REAL(KIND=JPRB), POINTER :: ZTRSODIF(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSUDU
  REAL(KIND=JPRB), POINTER :: ZSUDU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTHETAVS
  REAL(KIND=JPRB), POINTER :: ZTHETAVS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZGEOSLC
  REAL(KIND=JPRB), POINTER :: ZGEOSLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENT
  REAL(KIND=JPRB), POINTER :: ZTENT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTHETAV
  REAL(KIND=JPRB), POINTER :: ZTHETAV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFN
  REAL(KIND=JPRB), POINTER :: ZCOEFN(:, :, :)
  
  ! LOCAL ARRAYS FOR ACVPPKF
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVPP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEB_CVPP
  REAL(KIND=JPRB), POINTER :: ZNEB_CVPP(:, :, :)
  
  ! Implicit coupling coefficients
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBTH
  REAL(KIND=JPRB), POINTER :: ZCFBTH(:, :, :)
  REAL(KIND=JPRB) :: ZDTMSE
  REAL(KIND=JPRB) :: ZRHGMT
  REAL(KIND=JPRB) :: ZSTATI
  CLASS(FIELD_3RB), POINTER :: YL_ZCFATH
  REAL(KIND=JPRB), POINTER :: ZCFATH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFAU
  REAL(KIND=JPRB), POINTER :: ZCFAU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBU
  REAL(KIND=JPRB), POINTER :: ZCFBU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBV
  REAL(KIND=JPRB), POINTER :: ZCFBV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSRAIN
  REAL(KIND=JPRB), POINTER :: ZSRAIN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSSNOW
  REAL(KIND=JPRB), POINTER :: ZSSNOW(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSGROUPEL
  REAL(KIND=JPRB), POINTER :: ZSGROUPEL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTSN
  REAL(KIND=JPRB), POINTER :: ZTSN(:, :)
  
  !         ACFLUSO (ECUME) local variable
  CLASS(FIELD_2RB), POINTER :: YL_ZCE
  REAL(KIND=JPRB), POINTER :: ZCE(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCEROV
  REAL(KIND=JPRB), POINTER :: ZCEROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCRTI
  REAL(KIND=JPRB), POINTER :: ZCRTI(:, :)
  
  !        New ACDIFV1 local variable
  CLASS(FIELD_3RB), POINTER :: YL_ZXURO
  REAL(KIND=JPRB), POINTER :: ZXURO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXQRO
  REAL(KIND=JPRB), POINTER :: ZXQRO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTRO
  REAL(KIND=JPRB), POINTER :: ZXTRO(:, :, :)
  
  !        New ACNORGWD local variables
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWU
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWV
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWV(:, :, :)
  
  !    TKE+ for ACCLDIA
  CLASS(FIELD_3RB), POINTER :: YL_ZTKE1
  REAL(KIND=JPRB), POINTER :: ZTKE1(:, :, :)
  
  !   For ACVISIH
  CLASS(FIELD_3RB), POINTER :: YL_ZQGM
  REAL(KIND=JPRB), POINTER :: ZQGM(:, :, :)
  
  
  !        New ARP_GROUND_PARAM local variable
  CLASS(FIELD_3RB), POINTER :: YL_ZALPHA1
  REAL(KIND=JPRB), POINTER :: ZALPHA1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFA
  REAL(KIND=JPRB), POINTER :: ZCOEFA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZLVT
  REAL(KIND=JPRB), POINTER :: ZLVT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQICE
  REAL(KIND=JPRB), POINTER :: ZQICE(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWQ
  REAL(KIND=JPRB), POINTER :: ZDIFWQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWS
  REAL(KIND=JPRB), POINTER :: ZDIFWS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVI
  REAL(KIND=JPRB), POINTER :: ZSC_FEVI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVN
  REAL(KIND=JPRB), POINTER :: ZSC_FEVN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLL
  REAL(KIND=JPRB), POINTER :: ZSC_FCLL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLN
  REAL(KIND=JPRB), POINTER :: ZSC_FCLN(:, :)
  
  !           TRAJECTORY (For diffusion !) local VARIABLES
  CLASS(FIELD_3RB), POINTER :: YL_ZTRAJGWD
  REAL(KIND=JPRB), POINTER :: ZTRAJGWD(:, :, :)
  
  CLASS(FIELD_2RB), POINTER :: YL_ZAIPCMT
  REAL(KIND=JPRB), POINTER :: ZAIPCMT(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQIC
  REAL(KIND=JPRB), POINTER :: ZQIC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLC
  REAL(KIND=JPRB), POINTER :: ZQLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQC_DET_PCMT
  REAL(KIND=JPRB), POINTER :: ZQC_DET_PCMT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDCAPE
  REAL(KIND=JPRB), POINTER :: ZDCAPE(:, :)
  
  ! ACRANEB/ACRANEB2 local variables
  CLASS(FIELD_2RB), POINTER :: YL_ZDECRD
  REAL(KIND=JPRB), POINTER :: ZDECRD(:, :)
  
  ! Precipitation type diagnostics
  CLASS(FIELD_2RB), POINTER :: YL_IMOC_CLPH
  INTEGER(KIND=JPIM), POINTER :: IMOC_CLPH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QRCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QRCONV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QSCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QSCONV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C1
  REAL(KIND=JPRB), POINTER :: ZDSA_C1(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C2
  REAL(KIND=JPRB), POINTER :: ZDSA_C2(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_CPS
  REAL(KIND=JPRB), POINTER :: ZDSA_CPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_LHS
  REAL(KIND=JPRB), POINTER :: ZDSA_LHS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_RS
  REAL(KIND=JPRB), POINTER :: ZDSA_RS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CDN
  REAL(KIND=JPRB), POINTER :: ZFLU_CDN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CD
  REAL(KIND=JPRB), POINTER :: ZFLU_CD(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CH
  REAL(KIND=JPRB), POINTER :: ZFLU_CH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_EMIS
  REAL(KIND=JPRB), POINTER :: ZFLU_EMIS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_FEVI
  REAL(KIND=JPRB), POINTER :: ZFLU_FEVI(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_NEIJ
  REAL(KIND=JPRB), POINTER :: ZFLU_NEIJ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_QSATS
  REAL(KIND=JPRB), POINTER :: ZFLU_QSATS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_QSAT
  REAL(KIND=JPRB), POINTER :: ZFLU_QSAT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_VEG
  REAL(KIND=JPRB), POINTER :: ZFLU_VEG(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_FRMQ
  REAL(KIND=JPRB), POINTER :: ZMSC_FRMQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LH
  REAL(KIND=JPRB), POINTER :: ZMSC_LH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LSCPE
  REAL(KIND=JPRB), POINTER :: ZMSC_LSCPE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_QW
  REAL(KIND=JPRB), POINTER :: ZMSC_QW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_TW
  REAL(KIND=JPRB), POINTER :: ZMSC_TW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB1
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB2
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB3
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB3(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLCH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLSH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLSH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKEI
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKEI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKE
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS2
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_CVGQ
  REAL(KIND=JPRB), POINTER :: ZRDG_CVGQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_LCVQ
  REAL(KIND=JPRB), POINTER :: ZRDG_LCVQ(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0LU
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0LU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0M
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0M(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0N
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0N(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_DDAL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_DDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_ENTCH
  REAL(KIND=JPRB), POINTER :: ZSAV_ENTCH(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_FHPS
  REAL(KIND=JPRB), POINTER :: ZSAV_FHPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0F
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0F(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0HF
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0HF(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_HV
  REAL(KIND=JPRB), POINTER :: ZSAV_HV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_PBLH
  REAL(KIND=JPRB), POINTER :: ZSAV_PBLH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_QSH
  REAL(KIND=JPRB), POINTER :: ZSAV_QSH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_UDAL(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_UDGRO
  REAL(KIND=JPRB), POINTER :: ZSAV_UDGRO(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_UDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UNEBH
  REAL(KIND=JPRB), POINTER :: ZSAV_UNEBH(:, :, :)
  
  INTEGER(KIND=JPIM) :: INSTEP_DEB
  INTEGER(KIND=JPIM) :: INSTEP_FIN
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JSPP
  LOGICAL :: LLCLS
  LOGICAL :: LLHMT
  LOGICAL :: LLREDPR
  REAL(KIND=JPRB) :: ZEPS0
  REAL(KIND=JPRB) :: ZEPSNEB
  REAL(KIND=JPRB) :: ZRVMD
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  CALL FIELD_NEW(YL_ZDIFEXT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_INLAB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMRIPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNBVNO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQLROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBC0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBDIFF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPCOR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPOID, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENHA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENQVA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMF_UP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRODTH_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDE2MR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZVGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDQSTS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGWDCS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHTR, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSTAB, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWFC, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWPMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWLMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSEQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWWILT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZC3, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPCLS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQO3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAER, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAERINDS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSOD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEMTR, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCTRSO, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSUDU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAVS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGEOSLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBTH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFATH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFAU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSRAIN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSSNOW, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSGROUPEL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTSN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXURO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXQRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTKE1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQGM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALPHA1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZLVT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQICE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRAJGWD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAIPCMT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQIC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQC_DET_PCMT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDCAPE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDECRD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_IMOC_CLPH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QRCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QSCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C1, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C2, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_CPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_LHS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_RS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CDN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_EMIS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KTSSG + 1 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_NEIJ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSATS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSAT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_VEG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_FRMQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LSCPE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_QW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_TW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLSH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKEI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC2 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_CVGQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_LCVQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0LU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0M, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0N, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_ENTCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_FHPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0F, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0HF, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_HV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_PBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_QSH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDGRO, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  
  
  
  
  
  INSTEP_DEB = 1
  INSTEP_FIN = 1
  
  <PragmaRegion::>
    
    CALL CPPHINP(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDVARS%GEOMETRY%GEMU%T0, YDVARS%GEOMETRY%GELAM%T0,  &
    & YDVARS%U%T0, YDVARS%V%T0, YDVARS%Q%T0, YDVARS%Q%DL, YDVARS%Q%DM, YDVARS%CVGQ%DL, YDVARS%CVGQ%DM, YDCPG_PHY0%XYB%RDELP,  &
    & YDCPG_DYN0%CTY%EVEL, YDVARS%CVGQ%T0, YL_ZRDG_MU0, YL_ZRDG_MU0LU, YL_ZRDG_MU0M, YL_ZRDG_MU0N, YL_ZRDG_CVGQ)
    
  
  <PragmaRegion::>
    
    DO JLEV=1,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZRDG_LCVQ(JLON, JLEV) = YL_ZRDG_CVGQ(JLON, JLEV)
      END DO
    END DO
    
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YL_ZFLU_QSATS(JLON) = 0.0_JPRB
    END DO
    
  
  CALL MF_PHYS_FPL_PART1(YDCPG_BNDS, YDCPG_OPTS, YL_ZPFL_FPLCH, YL_ZPFL_FPLSH, YDVARS%CPF%T0, YDVARS%SPF%T0, YDMODEL)
  
  IF (YDCPG_OPTS%LCONFX) THEN
    
    CALL MF_PHYS_SAVE_PHSURF_PART1(YDCPG_BNDS, YDCPG_OPTS, YL_ZSAV_DDAL, YL_ZSAV_DDOM, YL_ZSAV_ENTCH, YL_ZSAV_FHPS,  &
    & YL_ZSAV_GZ0F, YL_ZSAV_GZ0HF, YL_ZSAV_HV, YL_ZSAV_PBLH, YL_ZSAV_QSH, YL_ZSAV_UDAL, YL_ZSAV_UDGRO, YL_ZSAV_UDOM,  &
    & YL_ZSAV_UNEBH, YDMF_PHYS_SURF%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VH%PPBLH, YDMF_PHYS_SURF%GSD_VH%PQSH,  &
    & YDMF_PHYS_SURF%GSD_VH%PSPSH, YDMF_PHYS_SURF%GSD_VK%PUDGRO, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VV%PZ0H,  &
    & YDVARS%DAL%T0, YDVARS%DOM%T0, YDVARS%UAL%T0, YDVARS%UEN%T0, YDVARS%UNEBH%T0, YDVARS%UOM%T0, YDMODEL)
    
  END IF
  
  
  <PragmaRegion::>
    
    CALL APLPAR_INIT(YDCPG_OPTS%LAROME, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
    & YDMODEL%YRML_PHY_G%YRDPHY%NTSSG, YDCPG_OPTS%YRSURF_DIMS%YSP_SBD%NLEVS, YDMF_PHYS_SURF%GSD_VF%PVEG, YL_ZMSC_FRMQ,  &
    & YL_ZDSA_CPS, YL_ZDSA_LHS, YL_ZDSA_RS, YL_ZMSC_LH, YL_ZMSC_LSCPE, YL_ZFLU_QSAT, YL_ZMSC_QW, YL_ZMSC_TW, YL_ZFLU_CD,  &
    & YL_ZFLU_CDN, YL_ZFLU_CH, YL_ZDSA_C1, YL_ZDSA_C2, YL_ZFLU_EMIS, YL_ZFLU_FEVI, YL_ZPFL_FTKE, YL_ZPFL_FTKEI, YL_ZPFL_FEFB1,  &
    & YL_ZPFL_FEFB2, YL_ZPFL_FEFB3, YL_ZFLU_NEIJ, YL_ZFLU_VEG, YL_ZFLU_QSATS, YL_IMOC_CLPH)
    
  
  <PragmaRegion::>
    
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDMF_PHYS_SURF%GSD_VF%PLSM(JLON) = REAL(NINT(YDMF_PHYS_SURF%GSD_VF%PLSM(JLON)), kind=JPRB)
    END DO
    
  
  ! Check magnitude of model variables.
  
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGCHECKMV) THEN
    <PragmaRegion::>
      CALL CHECKMV(YDCPG_OPTS%NINDAT, YDMODEL%YRCST, YDMODEL%YRML_GCONF%YRRIP, YDMODEL%YRML_PHY_MF%YRPHY0,  &
      & YDMODEL%YRML_PHY_MF%YRPHY2, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDCPG_OPTS%NSTEP,  &
      & YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD,  &
      & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDVARS%GEOMETRY%GELAM%T0, YDVARS%GEOMETRY%GEMU%T0, YL_ZRDG_MU0,  &
      & YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%Q, YDMF_PHYS_BASE_STATE%YGSP_RR%T)
  END IF
  
  
  
  LLREDPR = .false.
  ZRVMD = YDMODEL%YRCST%RV - YDMODEL%YRCST%RD
  
  IF (YDCPG_OPTS%LCONFX) THEN
    ZDTMSE = 0.01_JPRB
    ZSTATI = YDMODEL%YRML_GCONF%YRRIP%RSTATI - ZDTMSE / 2._JPRB
  ELSE
    ZDTMSE = YDMODEL%YRML_PHY_MF%YRPHY2%TSPHY
    ZSTATI = YDMODEL%YRML_GCONF%YRRIP%RSTATI
  END IF
  ZRHGMT = REAL(YDMODEL%YRML_GCONF%YRRIP%RHGMT, kind=JPRB)
  
  
  CALL APL_ARPEGE_INIT(YDMODEL%YRCST, YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDMF_PHYS_SURF,  &
  & YDVARS, YDMODEL, YL_IMOC_CLPH, YL_INLAB_CVPP, YL_ZAER, YL_ZAERINDS, YL_ZAIPCMT, YL_ZALBD, YL_ZALBP, YL_ZALPHA1, YL_ZCEMTR,  &
  & YL_ZCFATH, YL_ZCFAU, YL_ZCFBTH, YL_ZCFBU, YL_ZCFBV, YL_ZCOEFA, YL_ZCONDCVPPI, YL_ZCONDCVPPL, YL_ZCTRSO, YL_ZDECRD,  &
  & YL_ZDIFCVPPQ, YL_ZDIFCVPPS, YL_ZDIFCVPPU, YL_ZDIFCVPPV, YL_ZDIFWQ, YL_ZDIFWS, YL_ZEDMFQ, YL_ZEDMFS, YL_ZEDMFU, YL_ZEDMFV,  &
  & ZEPS0, ZEPSNEB, YL_ZFPCOR, YL_ZKQLROV, YL_ZKQROV, YL_ZKTROV, YL_ZKUROV, YL_ZLVT, YL_ZMF_UP, YL_ZMRIPP, YL_ZNEBC0, YL_ZNEBCH,  &
  & YL_ZNEBDIFF, YL_ZNEBS, YL_ZNEBS0, YL_ZNEB_CVPP, YL_ZPFL_FPLCH, YL_ZPFL_FPLSH, YL_ZPOID, YL_ZPRODTH_CVPP, YL_ZQC_DET_PCMT,  &
  & YL_ZQI, YL_ZQIC, YL_ZQICE, YL_ZQL, YL_ZQLC, YL_ZQLIS, YL_ZQLIS0, YL_ZQLI_CVP, YL_ZQLI_CVPP, YL_ZQO3, YL_ZQR, YL_ZQS, YL_ZQV,  &
  & YL_ZSC_FCLL, YL_ZSC_FCLN, YL_ZSC_FEVI, YL_ZSC_FEVN, YL_ZSEDIQI, YL_ZSEDIQL, YL_ZSFSWDIF, YL_ZSFSWDIR, YL_ZSUDU, YL_ZTENHA,  &
  & YL_ZTENQVA, YL_ZTENT, YL_ZTRSOD, YL_ZTRSODIF, YL_ZTRSODIR, YL_ZUNEBH, YL_ZXDROV, YL_ZXHROV, YL_ZXQRO, YL_ZXTRO, YL_ZXTROV,  &
  & YL_ZXURO, YL_ZXUROV)
  
  <PragmaRegion::>
    
    CALL ACTQSAT(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
    & YDMODEL%YRML_PHY_MF%YRTOPH%NTQSAT, YDCPG_OPTS%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF,  &
    & YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, YL_ZQV, YDMF_PHYS_BASE_STATE%T, YL_ZGEOSLC, YL_ZMSC_LH, YL_ZMSC_LSCPE, YL_ZFLU_QSAT,  &
    & YL_ZMSC_QW, YDCPG_MISC%RH, YL_ZMSC_TW)
    
  
  
  IF (.not.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
    
    <PragmaRegion::>
      
      IF (YDMODEL%YRML_PHY_MF%YRPHY%LSOLV) THEN
        LLHMT = .false.
        CALL ACSOL(YDCPG_OPTS%YRCLI, YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY1, YDCPG_BNDS%KIDIA,  &
        & YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDMF_PHYS_SURF%GSD_VV%PARG, YDMF_PHYS_SURF%GSD_VV%PD2, YDMF_PHYS_SURF%GSD_VF%PZ0F,  &
        & YDMF_PHYS_SURF%GSD_VV%PZ0H, YDMF_PHYS_SURF%GSD_VF%PZ0RLF, YDMF_PHYS_SURF%GSD_VF%PLSM, YDMF_PHYS_SURF%GSD_VV%PIVEG,  &
        & YDMF_PHYS_SURF%GSD_VV%PLAI, YDMF_PHYS_BASE_STATE%YGSP_SG%A(:, 1), YDMF_PHYS_BASE_STATE%YGSP_SG%R(:, 1),  &
        & YDMF_PHYS_SURF%GSD_VV%PSAB, YDMF_PHYS_BASE_STATE%YGSP_SG%F(:, 1), YDMF_PHYS_BASE_STATE%YGSP_RR%T,  &
        & YDMF_PHYS_SURF%GSD_VF%PVEG, YDMF_PHYS_BASE_STATE%YGSP_SB%Q(:, 1), YDMF_PHYS_BASE_STATE%YGSP_SB%TL(:, 1),  &
        & YDMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_BASE_STATE%YGSP_RR%IC, LLHMT, YL_ZDSA_C1, YL_ZDSA_C2, YL_ZC3, YL_ZCG,  &
        & YL_ZCN, YDMF_PHYS%OUT%CT, YL_ZNEIJG, YL_ZNEIJV, YL_ZWFC, YL_ZWPMX, YL_ZWSEQ, YL_ZWSMX, YL_ZWWILT)
      ELSE
        
        !DEC$ IVDEP
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YDMF_PHYS%OUT%CT(JLON) = YDMODEL%YRML_PHY_MF%YRPHY1%HSOL / (1.0_JPRB +  &
          & YDMODEL%YRML_PHY_MF%YRPHY1%HSOLIWR*(YDMF_PHYS_BASE_STATE%YGSP_RR%W(JLON) + YDMF_PHYS_BASE_STATE%YGSP_SB%Q(JLON, 1)) / &
          &  (YDMODEL%YRML_PHY_MF%YRPHY1%WSMX + YDMODEL%YRML_PHY_MF%YRPHY1%WPMX) &
          & *EXP(-0.5_JPRB*(YDMODEL%YRML_PHY_MF%YRPHY1%HSOLIT0*(YDMF_PHYS_BASE_STATE%YGSP_RR%T(JLON) - YDMODEL%YRCST%RTT))**2))
        END DO
      END IF
      
    
  END IF
  
  
  CALL APL_ARPEGE_INIT_SURFEX(YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR, YDMF_PHYS,  &
  & YDVARS, YDMODEL, YL_ZALBD, YL_ZALBP, YL_ZFLU_EMIS, YL_ZSGROUPEL, YL_ZSRAIN, YL_ZSSNOW, YL_ZTSN)
  
  <PragmaRegion::>
    
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YL_ZDPHIV(JLON) = YDMODEL%YRCST%RG*YDMODEL%YRML_PHY_MF%YRPHY2%HVCLS
      YL_ZDPHIT(JLON) = YDMODEL%YRCST%RG*YDMODEL%YRML_PHY_MF%YRPHY2%HTCLS
    END DO
    
  
  LLCLS = .true.
  LLHMT = .true.
  IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) THEN
    
    <PragmaRegion::>
      
      CALL ACHMTLS(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
      & YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD,  &
      & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, YDMF_PHYS_BASE_STATE%T,  &
      & YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YDMF_PHYS_BASE_STATE%YGSP_RR%T, YDCPG_MISC%QS, YL_ZDPHIT,  &
      & YDMF_PHYS%OUT%GZ0, YDMF_PHYS%OUT%GZ0H, LLCLS, YL_ZNBVNO, YL_ZMRIPP, YL_ZDSA_CPS, YL_ZGWDCS, YL_ZDSA_LHS, YL_ZPCLS,  &
      & YL_ZFLU_CD, YL_ZFLU_CDN)
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZDPHI(JLON) = YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF(JLON, YDCPG_OPTS%KFLEVG) - YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI(JLON,  &
        & YDCPG_OPTS%KFLEVG)
        YL_ZPRS(JLON) = YDMODEL%YRCST%RD + ZRVMD*YDCPG_MISC%QS(JLON)
        YL_ZRTI(JLON) = 2.0_JPRB / (YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R(JLON, YDCPG_OPTS%KFLEVG)*YDMF_PHYS_BASE_STATE%T(JLON,  &
        & YDCPG_OPTS%KFLEVG) + YDMODEL%YRCST%RKAPPA*YL_ZDPHI(JLON) + YL_ZPRS(JLON)*YDMF_PHYS_BASE_STATE%YGSP_RR%T(JLON))
      END DO
      
    
  ELSE
    
    <PragmaRegion::>
      
      CALL ACHMT(YDCPG_OPTS%YRCLI, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY0, YDMODEL%YRML_PHY_MF%YRPHY1,  &
      & YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRCST, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG,  &
      & YDCPG_OPTS%YRSURF_DIMS%YSD_VVD%NUMFLDS >= 8 .and. YDMODEL%YRML_PHY_MF%YRPHY%LSOLV, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI,  &
      & YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF,  &
      & YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, YL_ZQV, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, YDMF_PHYS_BASE_STATE%T,  &
      & YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YL_ZPFL_FPLSH, YL_ZPFL_FPLCH, YL_ZDPHIT, YL_ZDPHIV,  &
      & YDMF_PHYS_SURF%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VV%PZ0H, YDMF_PHYS_SURF%GSD_VF%PZ0RLF, YDMF_PHYS_SURF%GSD_VV%PHV,  &
      & YDMF_PHYS_SURF%GSD_VF%PLSM, YL_ZNEIJG, YL_ZNEIJV, YDMF_PHYS_BASE_STATE%YGSP_SG%F(:, 1), YDMF_PHYS_BASE_STATE%YGSP_RR%T,  &
      & YDMF_PHYS_SURF%GSD_VF%PVEG, YL_ZWFC, YDMF_PHYS_BASE_STATE%YGSP_RR%W, YDMF_PHYS_BASE_STATE%YGSP_RR%IC, LLCLS, LLHMT,  &
      & YL_ZNBVNO, YL_ZMRIPP, YL_ZFLU_CD, YL_ZFLU_CDN, YL_ZCDROV, YL_ZFLU_CH, YL_ZCHROV, YL_ZDSA_CPS, YL_ZDQSTS, YL_ZGWDCS,  &
      & YDMF_PHYS%OUT%GZ0, YDMF_PHYS%OUT%GZ0H, YL_ZHQ, YL_ZHU, YL_ZFLU_NEIJ, YDMF_PHYS%OUT%QCLS, YDCPG_MISC%QS, YL_ZFLU_QSATS,  &
      & YDMF_PHYS%OUT%RHCLS, YL_ZDSA_RS, YL_ZRTI, YL_ZSTAB, YDMF_PHYS%OUT%TCLS, YDMF_PHYS%OUT%UCLS, YDMF_PHYS%OUT%VCLS,  &
      & YDMF_PHYS%OUT%NUCLS, YDMF_PHYS%OUT%NVCLS, YL_ZPCLS, YL_ZFLU_VEG, YL_ZXDROV, YL_ZXHROV, YDMF_PHYS%OUT%UGST,  &
      & YDMF_PHYS%OUT%VGST)
      
    
  END IF
  
  
  <PragmaRegion::>
    
    DO JLEV=1,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZCP(JLON, JLEV) = YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP(JLON, JLEV)
      END DO
    END DO
    
    DO JLEV=YDCPG_OPTS%KTDIA,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZTHETAV(JLON, JLEV) = YDMF_PHYS_BASE_STATE%T(JLON, JLEV)*(1.0_JPRB + YDMODEL%YRCST%RETV*YL_ZQV(JLON, JLEV)) &
        & *(YDMODEL%YRCST%RATM / YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF(JLON, JLEV))**YDMODEL%YRCST%RKAPPA
      END DO
    END DO
    
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YL_ZTHETAVS(JLON) = YDMF_PHYS_BASE_STATE%YGSP_RR%T(JLON)*(1.0_JPRB + YDMODEL%YRCST%RETV*YDCPG_MISC%QS(JLON)) &
      & *(YDMODEL%YRCST%RATM / YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD(JLON, YDCPG_OPTS%KFLEVG))**YDMODEL%YRCST%RKAPPA
    END DO
    
    CALL ACCLPH(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY0, YDMODEL%YRML_PHY_MF%YRPHY2, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA,  &
    & YDCPG_OPTS%KLON, YDCPG_OPTS%KTDIA, YDCPG_OPTS%KFLEVG, YL_ZTHETAV, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI,  &
    & YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YL_ZTHETAVS, YL_IMOC_CLPH,  &
    & YDMF_PHYS%OUT%CLPH, YDMF_PHYS%OUT%VEIN, YL_ZUGST, YL_ZVGST)
    
    
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YL_ZBLH(JLON) = YDMF_PHYS%OUT%CLPH(JLON)
    END DO
    
  
  CALL APL_ARPEGE_OCEANIC_FLUXES(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, LLHMT,  &
  & YL_ZCDROV, YL_ZCEROV, YL_ZCHROV, YL_ZDPHIT, YL_ZDPHIV, YL_ZDSA_RS, YL_ZFLU_CD, YL_ZFLU_CDN, YL_ZFLU_CH, YL_ZFLU_QSATS)
  
  
  CALL APL_WIND_GUST(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDVARS, YDMODEL, YL_IMOC_CLPH, YL_ZBLH, YL_ZDCAPE)
  
  
  CALL APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS,  &
  & YDMODEL, YDDDH, YL_INLAB_CVPP, YL_ZCDROV, YL_ZCHROV, YL_ZCOEFN, YL_ZCONDCVPPI, YL_ZCONDCVPPL, YL_ZDIFCVPPQ, YL_ZDIFCVPPS,  &
  & YDMODEL%YRML_PHY_MF%YRPHY0%REPS, YL_ZFLU_CD, YL_ZFLU_CH, YL_ZKQLROV, YL_ZKQROV, YL_ZKTROV, YL_ZKUROV, YL_ZMSC_LSCPE,  &
  & YL_ZNBVNO, YL_ZNEBS, YL_ZNEBS0, YL_ZNEB_CVPP, YL_ZPFL_FPLCH, YL_ZPFL_FTKE, YL_ZPFL_FTKEI, YL_ZPRODTH_CVPP, YL_ZQI, YL_ZQIC,  &
  & YL_ZQL, YL_ZQLC, YL_ZQLIS, YL_ZQLIS0, YL_ZQLI_CVPP, YL_ZQV, YL_ZTKE1, YL_ZXTROV, YL_ZXUROV)
  
  CALL APL_ARPEGE_ALBEDO_COMPUTATION(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YL_ZALBD,  &
  & YL_ZALBP, ZEPS0, YL_ZFLU_EMIS, YL_ZFLU_NEIJ, YL_ZRDG_MU0)
  
  CALL APL_ARPEGE_AEROSOLS_FOR_RADIATION(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS_SURF, YDMODEL, YL_ZAER,  &
  & YL_ZAERINDS)
  
  CALL APL_ARPEGE_CLOUDINESS(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDVARS, YDMODEL, LLREDPR,  &
  & YL_ZAIPCMT, YL_ZBLH, YL_ZDECRD, YL_ZFLU_QSAT, YL_ZMSC_QW, YL_ZNEBC0, YL_ZNEBCH, YL_ZNEBS, YL_ZNEBS0, YL_ZNEB_CVPP,  &
  & YL_ZPFL_FPLCH, YL_ZQI, YL_ZQL, YL_ZQLIS, YL_ZQLIS0, YL_ZQLI_CVP, YL_ZQLI_CVPP, YL_ZQV, YL_ZUNEBH, YDGEOMETRY%YRSTA)
  
  CALL APL_ARPEGE_RADIATION(YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR, YDMF_PHYS,  &
  & YDMF_PHYS_SURF, YDVARS, YDMODEL, YL_ZAER, YL_ZAERINDS, YL_ZALBD, YL_ZALBP, YL_ZCEMTR, YL_ZCTRSO, YL_ZFLU_EMIS, YL_ZFLU_QSAT,  &
  & YL_ZQO3, YL_ZQR, YL_ZQS, YL_ZQV, YL_ZRDG_MU0, YL_ZRDG_MU0LU, YL_ZRDG_MU0M, YL_ZSFSWDIF, YL_ZSFSWDIR, YL_ZSUDU, YL_ZTENT,  &
  & YL_ZTRSOD, YL_ZTRSODIF, YL_ZTRSODIR)
  
  CALL APL_ARPEGE_SOIL_HYDRO(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YL_ZCHROV,  &
  & YL_ZFLU_NEIJ, YL_ZFLU_QSAT, YL_ZFLU_QSATS, YL_ZFLU_VEG, YL_ZGWDCS, YL_ZHQ, YL_ZHTR, YL_ZHU, YL_ZQV, YL_ZWFC, YL_ZWLMX,  &
  & YL_ZWWILT)
  
  CALL APL_ARPEGE_SURFACE(YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR, YDMF_PHYS,  &
  & YDMF_PHYS_SURF, YDVARS, YDMODEL, YL_ZALBD, YL_ZALBP, YL_ZALPHA1, YL_ZCDROV, YL_ZCEROV, YL_ZCFATH, YL_ZCFAU, YL_ZCFBTH,  &
  & YL_ZCFBU, YL_ZCFBV, YL_ZCHROV, YL_ZCOEFA, YL_ZCOEFN, YL_ZCP, YL_ZDIFEXT, YL_ZDIFWQ, YL_ZDIFWS, YL_ZDQSTS, YL_ZDSA_CPS,  &
  & YL_ZDSA_LHS, ZDTMSE, YL_ZEDMFQ, YL_ZEDMFS, YL_ZEDMFU, YL_ZEDMFV, YL_ZFLU_CD, YL_ZFLU_CDN, YL_ZFLU_EMIS, YL_ZFLU_FEVI,  &
  & YL_ZFLU_NEIJ, YL_ZFLU_QSATS, YL_ZFLU_VEG, YL_ZHQ, YL_ZHTR, YL_ZHU, YL_ZKQLROV, YL_ZKQROV, YL_ZKTROV, YL_ZKUROV, YL_ZLVT,  &
  & YL_ZMF_UP, YL_ZNEBCH, YL_ZNEBDIFF, YL_ZNEBS, YL_ZPOID, YL_ZQI, YL_ZQICE, YL_ZQL, YL_ZQV, YL_ZRDG_MU0, YL_ZRDG_MU0N, ZRHGMT,  &
  & YL_ZSC_FCLL, YL_ZSC_FCLN, YL_ZSC_FEVI, YL_ZSC_FEVN, YL_ZSFSWDIF, YL_ZSFSWDIR, YL_ZSGROUPEL, YL_ZSRAIN, YL_ZSSNOW, ZSTATI,  &
  & YL_ZTSN, YL_ZXDROV, YL_ZXHROV, YL_ZXQRO, YL_ZXTRO, YL_ZXTROV, YL_ZXURO, YL_ZXUROV)
  
  ! The deep convection will see the shallow part from KFB as it is with Louis scheme and the modified RI
  
  <PragmaRegion::>
    
    DO JLEV=YDCPG_OPTS%KTDIA,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDMF_PHYS%OUT%DIFTQ(JLON, JLEV) = YDMF_PHYS%OUT%DIFTQ(JLON, JLEV) + YL_ZDIFCVPPQ(JLON, JLEV)
        YDMF_PHYS%OUT%DIFTS(JLON, JLEV) = YDMF_PHYS%OUT%DIFTS(JLON, JLEV) + YL_ZDIFCVPPS(JLON, JLEV)
        YDMF_PHYS%OUT%STRTU(JLON, JLEV) = YDMF_PHYS%OUT%STRTU(JLON, JLEV) + YL_ZDIFCVPPU(JLON, JLEV)
        YDMF_PHYS%OUT%STRTV(JLON, JLEV) = YDMF_PHYS%OUT%STRTV(JLON, JLEV) + YL_ZDIFCVPPV(JLON, JLEV)
      END DO
    END DO
    
  
  ! Additional diagnostics of radiative fluxes (PFRTHDS and PFRSOPT)
  
  <PragmaRegion::>
    
    !DEC$ IVDEP
    DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      IF (.not.YDMODEL%YRML_PHY_MF%YRARPHY%LMSE) YDMF_PHYS%OUT%FRTHDS(JLON) = YDMF_PHYS%OUT%FRTH(JLON, YDCPG_OPTS%KFLEVG, 1) / YL_ZFLU_EMIS(JLON) +  &
      & YDMODEL%YRCST%RSIGMA*YDMF_PHYS_BASE_STATE%YGSP_RR%T(JLON)**4
      IF (YL_ZRDG_MU0(JLON) <= 0.0_JPRB) THEN
        YDMF_PHYS%OUT%FRSOPT(JLON) = 0.0_JPRB
      ELSE
        YDMF_PHYS%OUT%FRSOPT(JLON) = YDMODEL%YRML_PHY_MF%YRPHY3%RII0*YL_ZRDG_MU0(JLON)
      END IF
    END DO
    
  
  ! Additional diagnostic of the derivative of the non solar surface; heat flux with respect to surface temperature
  
  <PragmaRegion::>
    
    IF (YDMODEL%YRML_AOC%YRMCC%LMCC03) THEN
      CALL ACDNSHF(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHY1, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA,  &
      & YDCPG_OPTS%KLON, YDCPG_OPTS%KTDIA, YDCPG_OPTS%KFLEVG, YL_ZFLU_EMIS, YDMF_PHYS_SURF%GSD_VF%PLSM, YL_ZFLU_NEIJ, YL_ZQV,  &
      & YDCPG_MISC%QS, YDMF_PHYS_BASE_STATE%YGSP_RR%T, YL_ZCHROV, YL_ZDQSTS, YDMF_PHYS%OUT%DRNSHF)
    END IF
    
    CALL ACDRAG(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
    & YDMODEL%YRML_PHY_MF%YRTOPH%NTDRAG, YDCPG_OPTS%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD,  &
    & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, YL_ZNBVNO,  &
    & YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YDVARS%GEOMETRY%RCORI%T0,  &
    & YDMF_PHYS_SURF%GSD_VF%PGETRL, YL_ZGWDCS, YDMF_PHYS_SURF%GSD_VF%PVRLAN, YDMF_PHYS_SURF%GSD_VF%PVRLDI, YDMF_PHYS%OUT%STRDU,  &
    & YDMF_PHYS%OUT%STRDV, YL_ZTRAJGWD)
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LSTRAS) THEN
      CALL ACPLUIS(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
      & YDMODEL%YRML_PHY_MF%YRTOPH%NTPLUI, YDCPG_OPTS%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF,  &
      & YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, YL_ZNEBS, YL_ZQV, YL_ZQLIS, YL_ZMSC_QW, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R,  &
      & YDMF_PHYS_BASE_STATE%T, YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN,  &
      & YDMF_PHYS%OUT%FPEVPSL, YDMF_PHYS%OUT%FPEVPSN, YDMF_PHYS%OUT%FPFPSL, YDMF_PHYS%OUT%FPFPSN)
    END IF
    
  
  CALL APL_ARPEGE_DEEP_CONVECTION(YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDCPG_DYN0,  &
  & YDMF_PHYS_SURF, YDVARS, YDMODEL, YL_ZFPCOR, YL_ZQV, YL_ZTENHA, YL_ZTENQVA, YL_ZTENT)
  
  CALL APL_ARPEGE_PRECIPITATION(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDMODEL,  &
  & YL_ZFLU_NEIJ, YL_ZNEBS, YL_ZNEB_CVPP, YL_ZQC_DET_PCMT, YL_ZQI, YL_ZQL, YL_ZQLIS, YL_ZQLI_CVPP, YL_ZQR, YL_ZQS, YL_ZQV,  &
  & YL_ZSEDIQI, YL_ZSEDIQL, YL_ZTENHA, YL_ZTENQVA, YDGEOMETRY%YRSTA)
  
  
  <PragmaRegion::>
    
    DO JLEV=0,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZFLX_LOTT_GWU(JLON, JLEV) = 0.0_JPRB
        YL_ZFLX_LOTT_GWV(JLON, JLEV) = 0.0_JPRB
      END DO
    END DO
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LNEBN .or. YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
      DO JLEV=YDCPG_OPTS%KTDIA - 1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YL_ZPFL_FPLCH(JLON, JLEV) = YL_ZFPCOR(JLON, JLEV)
        END DO
      END DO
    END IF
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LRRGUST) THEN
      DO JLEV=YDCPG_OPTS%KTDIA - 1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YL_ZPFL_FPLSH(JLON, JLEV) =  &
          & YDMF_PHYS%OUT%FPLSL(JLON, JLEV) + YDMF_PHYS%OUT%FPLSN(JLON, JLEV) + YDMF_PHYS%OUT%FPLSG(JLON, JLEV)
        END DO
      END DO
    END IF
    
    
    ! Update transport fluxes due to sedimentation of clouds.
    
    DO JLEV=YDCPG_OPTS%KTDIA,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDMF_PHYS%OUT%DIFTQL(JLON, JLEV) = YDMF_PHYS%OUT%DIFTQL(JLON, JLEV) + YL_ZSEDIQL(JLON, JLEV)
        YDMF_PHYS%OUT%DIFTQN(JLON, JLEV) = YDMF_PHYS%OUT%DIFTQN(JLON, JLEV) + YL_ZSEDIQI(JLON, JLEV)
        YL_ZFPLSL(JLON, JLEV) = YDMF_PHYS%OUT%DIFTQL(JLON, JLEV) + YDMF_PHYS%OUT%FPLSL(JLON, JLEV)
        YL_ZFPLSN(JLON, JLEV) = YDMF_PHYS%OUT%DIFTQN(JLON, JLEV) + YDMF_PHYS%OUT%FPLSN(JLON, JLEV)
      END DO
    END DO
    
    ! Correct negative water contents.
    
    CALL QNGCOR(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY2, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
    & YDMODEL%YRML_PHY_MF%YRTOPH%NTPLUI, YDCPG_OPTS%KFLEVG, YL_ZQV, YL_ZQL, YL_ZQI, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%RDELP,  &
    & YDMF_PHYS%OUT%DIFCQ, YDMF_PHYS%OUT%DIFCQN, YDMF_PHYS%OUT%DIFCQL, YDMF_PHYS%OUT%DIFTQ, YDMF_PHYS%OUT%DIFTQN,  &
    & YDMF_PHYS%OUT%DIFTQL, YDMF_PHYS%OUT%FPEVPSL, YDMF_PHYS%OUT%FPEVPSN, YDMF_PHYS%OUT%FPEVPCL, YDMF_PHYS%OUT%FPEVPCN,  &
    & YDMF_PHYS%OUT%FPFPSL, YDMF_PHYS%OUT%FPFPSN, YDMF_PHYS%OUT%FPFPCL, YDMF_PHYS%OUT%FPFPCN, YDMF_PHYS%OUT%FCCQL,  &
    & YDMF_PHYS%OUT%FCCQN, YDMF_PHYS%OUT%FCSQL, YDMF_PHYS%OUT%FCSQN, YDMF_PHYS%OUT%FCQNG)
    
  
  ! Bilan hydrique du sol
  
  CALL APL_ARPEGE_HYDRO_BUDGET(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL,  &
  & YL_ZC3, YL_ZCN, YL_ZDSA_C1, YL_ZDSA_C2, YL_ZFLU_FEVI, YL_ZFLU_NEIJ, YL_ZFLU_VEG, YL_ZFPLSL, YL_ZFPLSN, YL_ZWFC, YL_ZWLMX,  &
  & YL_ZWPMX, YL_ZWSEQ, YL_ZWSMX)
  
  ! Drag mesospherique pour un modele possedant des niveaux au-dessus de 50 km (i.e. dans la mesosphere)
  
  <PragmaRegion::>
    
    CALL ACDRME(YDMODEL%YRCST, YDGEOMETRY%YRSTA, YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRML_PHY_MF%YRTOPH, YDCPG_BNDS%KIDIA,  &
    & YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YDMODEL%YRML_PHY_MF%YRTOPH%NTDRME, YDCPG_OPTS%KFLEVG,  &
    & YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, YDMF_PHYS_BASE_STATE%T, YL_ZQV,  &
    & YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V, YDMF_PHYS%OUT%FRMH, YL_ZMSC_FRMQ, YDMF_PHYS%OUT%STRMU, YDMF_PHYS%OUT%STRMV)
    
    ! Store radiative cloudiness in GFL structure for ISP, Historical files or PostProcessing
    
    IF (YDMODEL%YRML_GCONF%YGFL%YIRAD%LGP) THEN
      DO JLEV=1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YDVARS%IRAD%T1(JLON, JLEV) = YDCPG_MISC%QICE(JLON, JLEV)
        END DO
      END DO
    END IF
    
    IF (YDMODEL%YRML_GCONF%YGFL%YLRAD%LGP) THEN
      DO JLEV=1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YDVARS%LRAD%T1(JLON, JLEV) = YDCPG_MISC%QLI(JLON, JLEV)
        END DO
      END DO
    END IF
    
    IF (YDMODEL%YRML_GCONF%YGFL%YA%LGP) THEN
      DO JLEV=1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          YDVARS%A%T1(JLON, JLEV) = YDCPG_MISC%NEB(JLON, JLEV)
        END DO
      END DO
    END IF
    
  
  <PragmaRegion::>
    
    ! DDH flexibles pour les champs de surface variables/flux/tendances.
    
    
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY2%LRAFTKE) THEN
    
    <PragmaRegion::>
      
      ! DCAPE due to precipitation evaporation.
      
      CALL ACEVADCAPE(YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRCST, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
      & YDCPG_OPTS%KFLEVG, YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN, YDMF_PHYS%OUT%FPLCL, YDMF_PHYS%OUT%FPLCN,  &
      & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD, YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%T,  &
      & YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YL_ZDCAPE)
      
      ! Gusts.
      
      CALL ACCLDIA(YDMODEL%YRCST, YDCPG_OPTS%LXCLP, YDCPG_OPTS%LXTGST, YDCPG_OPTS%LXXGST, YDMODEL%YRML_PHY_MF%YRPHY,  &
      & YDMODEL%YRML_PHY_MF%YRPHY2, YDMODEL%YRML_PHY_MF%YRTOPH, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
      & YDCPG_OPTS%KFLEVG, YDMF_PHYS%OUT%UCLS, YDMF_PHYS%OUT%VCLS, YDMF_PHYS_BASE_STATE%U, YDMF_PHYS_BASE_STATE%V,  &
      & YDMF_PHYS%OUT%CAPE, YL_ZDCAPE, YL_ZTKE1, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, YDVARS%GEOMETRY%OROG%T0,  &
      & YDMF_PHYS%OUT%UGST, YDMF_PHYS%OUT%VGST, YL_ZBLH, YL_IMOC_CLPH)
      
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDMF_PHYS%OUT%CLPH(JLON) = MIN(YDMODEL%YRML_PHY_MF%YRPHY0%XMAXLM, MAX(YDMODEL%YRML_PHY_MF%YRPHY0%XMINLM, YL_ZBLH(JLON)))
      END DO
      
    
  END IF
  
  <PragmaRegion::>
    
    YL_ZQGM(1:YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG) = ZEPSNEB
    
    CALL ACVISIH(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY%YRDVISI, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON,  &
    & YDCPG_OPTS%KTDIA, YDCPG_OPTS%KFLEVG, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF,  &
    & YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, YDMF_PHYS_BASE_STATE%T, YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, YDCPG_MISC%QLI,  &
    & YDCPG_MISC%QICE, YL_ZQR, YL_ZQS, YL_ZQGM, YDMF_PHYS%OUT%VISICLD, YDMF_PHYS%OUT%VISIHYD, YDMF_PHYS%OUT%MXCLWC)
    
  
  ! Convert from flux [kg/m2/s] to density [kg/m3] using old RTTOV-SCATT
  !  a    b         ! RR = a * LWC^b, [RR]=mm/h, [LWC]=g/m^3
  ! 20.89 1.15      ! rain
  ! 29.51 1.10      ! snow
  
  <PragmaRegion::>
    
    DO JLEV=1,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZBAY_QRCONV(JLON, JLEV) = 0.001_JPRB*((ABS(YDMF_PHYS%OUT%FPLCL(JLON, JLEV))*YDMODEL%YRML_PHY_MF%YRPHY0%RCOEFRAIN(1)) &
        & **YDMODEL%YRML_PHY_MF%YRPHY0%RCOEFRAIN(2))
        YL_ZBAY_QSCONV(JLON, JLEV) = 0.001_JPRB*((ABS(YDMF_PHYS%OUT%FPLCN(JLON, JLEV))*YDMODEL%YRML_PHY_MF%YRPHY0%RCOEFSNOW(1)) &
        & **YDMODEL%YRML_PHY_MF%YRPHY0%RCOEFSNOW(2))
      END DO
    END DO
    
  
  ! Convert density [kg/m3] to mixing ratio [kg/kg]
  ! R_dry (dry air constant)
  
  <PragmaRegion::>
    
    DO JLEV=1,YDCPG_OPTS%KFLEVG
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YL_ZDE2MR(JLON, JLEV) =  &
        & YDMODEL%YRCST%RD*YDMF_PHYS_BASE_STATE%T(JLON, JLEV) / YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF(JLON, JLEV)
        YL_ZBAY_QRCONV(JLON, JLEV) = YL_ZBAY_QRCONV(JLON, JLEV)*YL_ZDE2MR(JLON, JLEV)
        YL_ZBAY_QSCONV(JLON, JLEV) = YL_ZBAY_QSCONV(JLON, JLEV)*YL_ZDE2MR(JLON, JLEV)
      END DO
    END DO
    
  
  ! Precipitation Type
  
  ! Compute wet-bulb temperature at 2 meters (suppose homogeneity of qv/ql/qi )
  
  <PragmaRegion::>
    
    CALL PPWETPOINT(YDMODEL%YRCST, YDMODEL%YRML_PHY_MF%YRPHY, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDCPG_OPTS%KLON, YL_ZPCLS,  &
    & YDMF_PHYS%OUT%TCLS, YDMF_PHYS_BASE_STATE%Q(:, YDCPG_OPTS%KFLEVG), YDMF_PHYS_BASE_STATE%L(:, YDCPG_OPTS%KFLEVG),  &
    & YDMF_PHYS_BASE_STATE%I(:, YDCPG_OPTS%KFLEVG), YDMF_PHYS%OUT%TPWCLS)
    
  
  CALL APL_ARPEGE_DPRECIPS(YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDVARS, YDMODEL, YL_ZPRC_DPRECIPS,  &
  & YL_ZPRC_DPRECIPS2)
  
  CALL MF_PHYS_MOCON(YDCPG_BNDS, YDCPG_OPTS, YL_ZRDG_LCVQ, YL_IMOC_CLPH, YDMF_PHYS, YDMF_PHYS_BASE_STATE)
  
  ! Store surface water flux P and E for water conservation
  IF (YDCPG_OPTS%LCORWAT) THEN
    
    <PragmaRegion::>
      
      CALL MF_PHYS_CORWAT(YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS%OUT%FEVL, YDMF_PHYS%OUT%FEVN, YDMF_PHYS%OUT%FPLCL,  &
      & YDMF_PHYS%OUT%FPLCN, YDMF_PHYS%OUT%FPLSL, YDMF_PHYS%OUT%FPLSN, YDMF_PHYS_SURF%GSD_VH%PEVA, YDMF_PHYS_SURF%GSD_VH%PPCL,  &
      & YDMF_PHYS_SURF%GSD_VH%PPCN, YDMF_PHYS_SURF%GSD_VH%PPSL, YDMF_PHYS_SURF%GSD_VH%PPSN)
      
    
  END IF
  
  ! Surface specific humidity necessary to compute the vertical advection of q in the case "delta m=1" (unlagged physics only).
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI == 1) THEN
    
    <PragmaRegion::>
      
      CALL CPQSOL(YDMODEL%YRCST, YDGEOMETRY%YRDIMV, YDMODEL%YRML_PHY_MF%YRPHY, YDCPG_OPTS%KLON, YDCPG_BNDS%KIDIA,  &
      & YDCPG_BNDS%KFDIA, YDCPG_PHY0%PREHYD, YDMF_PHYS_SURF%GSP_RR%PT_T0, YDCPG_MISC%QS, YL_ZFLU_QSATS, YDCPG_MISC%QSOL)
      
    
  END IF
  
  CALL APL_ARPEGE_ATMOSPHERE_UPDATE(YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC,  &
  & YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDVARS, YDMODEL, YDDDH, YL_ZDIFEXT, YL_ZDSA_CPS, YL_ZMSC_FRMQ, YL_ZPFL_FEFB1,  &
  & YL_ZPFL_FEFB2, YL_ZPFL_FEFB3, YL_ZPFL_FTKE, YL_ZPFL_FTKEI)
  
  CALL MF_PHYS_FPL_PART2(YDCPG_BNDS, YDCPG_OPTS, YL_ZPFL_FPLCH, YL_ZPFL_FPLSH, YDVARS%CPF%T1, YDVARS%SPF%T1, YDMODEL)
  
  CALL MF_PHYS_TRANSFER(YDCPG_BNDS, YDCPG_OPTS, YDVARS, YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_GCONF%YGFL)
  
  CALL APL_ARPEGE_SURFACE_UPDATE(YDCPG_BNDS, YDCPG_OPTS, YDCPG_GPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YDCPG_OPTS%LCONFX,  &
  & YDCPG_OPTS%ZDTPHY, YL_ZDSA_C1, YL_ZDSA_C2, YL_ZFLU_FEVI, YL_ZFLU_VEG)
  
  IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVPGY) THEN
    
    <PragmaRegion::>
      
      CALL MF_PHYS_CVV(YDCPG_BNDS, YDCPG_OPTS, YDVARS%CVV%T0, YDVARS%CVV%T1)
      
    
  END IF
  
  ! Restore the initial value of some pseudo-historical surface buffers if relevant.
  
  IF (YDCPG_OPTS%LCONFX) THEN
    
    CALL MF_PHYS_SAVE_PHSURF_PART2(YDCPG_BNDS, YDCPG_OPTS, YL_ZSAV_DDAL, YL_ZSAV_DDOM, YL_ZSAV_ENTCH, YL_ZSAV_FHPS,  &
    & YL_ZSAV_GZ0F, YL_ZSAV_GZ0HF, YL_ZSAV_HV, YL_ZSAV_PBLH, YL_ZSAV_QSH, YL_ZSAV_UDAL, YL_ZSAV_UDGRO, YL_ZSAV_UDOM,  &
    & YL_ZSAV_UNEBH, YDMF_PHYS_SURF%GSD_VF%PZ0F, YDMF_PHYS_SURF%GSD_VH%PPBLH, YDMF_PHYS_SURF%GSD_VH%PQSH,  &
    & YDMF_PHYS_SURF%GSD_VH%PSPSH, YDMF_PHYS_SURF%GSD_VK%PUDGRO, YDMF_PHYS_SURF%GSD_VV%PHV, YDMF_PHYS_SURF%GSD_VV%PZ0H,  &
    & YDVARS%DAL%T0, YDVARS%DOM%T0, YDVARS%UAL%T0, YDVARS%UEN%T0, YDVARS%UNEBH%T0, YDVARS%UOM%T0, YDMODEL)
    
  END IF
  
  ! Store horizontal exchange coefficients (3D turbulence) to SL2 buffers
  
  
  <PragmaRegion::>
    
    CALL MF_PHYS_BAYRAD(YDCPG_BNDS, YDCPG_OPTS, YL_ZBAY_QRCONV, YL_ZBAY_QSCONV, YDVARS%RCONV%T1, YDVARS%SCONV%T1, YDMODEL)
    
  
  
  <PragmaRegion::>
    
    IF (YDMODEL%YRML_PHY_MF%YRPHY%LEDR) THEN
      DO JLEV=1,YDCPG_OPTS%YRSURF_DIMS%YSD_DID%NLEVS
        YDMF_PHYS_SURF%GSD_DI%PXEDR(:, JLEV) = YDMF_PHYS%OUT%EDR(:, JLEV)
      END DO
    END IF
    
  
  <PragmaRegion::>
    
    CALL MF_PHYS_PRECIPS(YDCPG_BNDS, YDCPG_OPTS, YL_ZPRC_DPRECIPS, YL_ZPRC_DPRECIPS2, YDMF_PHYS_SURF%GSD_XP%PPRECIP,  &
    & YDMF_PHYS_SURF%GSD_XP2%PPRECIP2, YDMODEL)
    
  
  
  
END SUBROUTINE APL_ARPEGE
