SUBROUTINE APL_ARPEGE (YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDCPG_GPAR,  &
& YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDCPG_SL2, YDVARS, YDMODEL, YDDDH)
  
  !**** *APL_ARPEGE*  - Call ARPEGE physics
  
  !     Author.
  !     -------
  !      Philippe Marguinaud *METEO-FRANCE*
  !      Original : 28-04-2021
  
  !     Modifications.
  !     --------------
  !     13-Jul-2022 R. El Khatib Fix initialization of ZQGM
  ! End Modifications
  !-------------------------------------------------------------------------------
  
  USE GEOMETRY_MOD, ONLY: GEOMETRY
  
  USE ACPY_MOD
  USE STACK_MOD
  USE YOMPARALLELMETHOD
  USE FIELD_ACCESS_MODULE
  USE FIELD_FACTORY_MODULE
  USE FIELD_MODULE
  USE MF_PHYS_TYPE_MOD, ONLY: MF_PHYS_TYPE
  USE CPG_TYPE_MOD, ONLY: CPG_MISC_TYPE, CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_PHY_TYPE
  USE CPG_SL2_TYPE_MOD, ONLY: CPG_SL2_TYPE
  USE CPG_OPTS_TYPE_MOD, ONLY: CPG_BNDS_TYPE, CPG_OPTS_TYPE
  USE MF_PHYS_SURFACE_TYPE_MOD, ONLY: MF_PHYS_SURF_TYPE
  USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
  USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY: MF_PHYS_BASE_STATE_TYPE
  USE MF_PHYS_NEXT_STATE_TYPE_MOD, ONLY: MF_PHYS_NEXT_STATE_TYPE
  USE TYPE_MODEL, ONLY: MODEL
  
  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
  USE DDH_MIX, ONLY: TYP_DDH
  
  IMPLICIT NONE
  
  TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
  TYPE(MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
  TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
  TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
  TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
  TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
  TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
  TYPE(CPG_PHY_TYPE), INTENT(IN) :: YDCPG_PHY0
  TYPE(MF_PHYS_TYPE), INTENT(INOUT) :: YDMF_PHYS
  TYPE(CPG_DYN_TYPE), INTENT(IN) :: YDCPG_DYN0
  TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
  TYPE(CPG_SL2_TYPE), INTENT(INOUT) :: YDCPG_SL2
  TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
  TYPE(MODEL), INTENT(IN) :: YDMODEL
  TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
  
#include "accldia.intfb.h"
#include "acclph.intfb.h"
#include "acdnshf.intfb.h"
#include "acdrag.intfb.h"
#include "acdrme.intfb.h"
#include "acevadcape.intfb.h"
#include "achmt.intfb.h"
#include "achmtls.intfb.h"
#include "acpluis.intfb.h"
#include "acsol.intfb.h"
#include "actqsat.intfb.h"
#include "acvisih.intfb.h"
#include "aplpar_init.intfb.h"
#include "checkmv.intfb.h"
#include "cpphinp.intfb.h"
#include "cpqsol.intfb.h"
#include "mf_phys_bayrad.intfb.h"
#include "mf_phys_corwat.intfb.h"
#include "mf_phys_cvv.intfb.h"
#include "mf_phys_fpl_part1.intfb.h"
#include "mf_phys_fpl_part2.intfb.h"
#include "mf_phys_mocon.intfb.h"
#include "mf_phys_precips.intfb.h"
#include "mf_phys_save_phsurf_part1.intfb.h"
#include "mf_phys_save_phsurf_part2.intfb.h"
#include "mf_phys_transfer.intfb.h"
#include "ppwetpoint.intfb.h"
#include "qngcor.intfb.h"
#include "aplpar_flexdia.intfb.h"
#include "apl_arpege_oceanic_fluxes.intfb.h"
#include "apl_wind_gust.intfb.h"
#include "apl_arpege_shallow_convection_and_turbulence.intfb.h"
#include "apl_arpege_albedo_computation.intfb.h"
#include "apl_arpege_aerosols_for_radiation.intfb.h"
#include "apl_arpege_cloudiness.intfb.h"
#include "apl_arpege_radiation.intfb.h"
#include "apl_arpege_soil_hydro.intfb.h"
#include "apl_arpege_surface.intfb.h"
#include "apl_arpege_deep_convection.intfb.h"
#include "apl_arpege_precipitation.intfb.h"
#include "apl_arpege_hydro_budget.intfb.h"
#include "apl_arpege_surface_update.intfb.h"
#include "apl_arpege_atmosphere_update.intfb.h"
#include "apl_arpege_init.intfb.h"
#include "apl_arpege_init_surfex.intfb.h"
#include "apl_arpege_dprecips.intfb.h"
  
  
  REAL(KIND=JPRB) :: ZDIFEXT(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)  ! Extra-GFL fluxes.
  INTEGER(KIND=JPIM) :: INLAB_CVPP(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZXTROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZXUROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZMRIPP(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZKTROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZKUROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZNBVNO(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZKQROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZKQLROV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZNEBS(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQLIS(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZNEBS0(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQLIS0(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZNEBC0(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! Nebulosite convective radiative
  REAL(KIND=JPRB) :: ZNEBDIFF(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! Nebulosite: calcul de la diffusion
  REAL(KIND=JPRB) :: ZNEBCH(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! Nebulosite convective condensation
  REAL(KIND=JPRB) :: ZUNEBH(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! Nebulosite convective histo
  REAL(KIND=JPRB) :: ZFPCOR(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPOID(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! DP/(YDMODEL%YRCST%RG*DT) FOR A GIVEN LEVEL AND A GIVEN TIME STEP.
  REAL(KIND=JPRB) :: ZQV(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! corrected (for negative values) vapour
  REAL(KIND=JPRB) :: ZQI(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! corrected (for negative values) cloud ice
  REAL(KIND=JPRB) :: ZQL(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! corrected (for negative values) cloud liquid
  REAL(KIND=JPRB) :: ZQR(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! corrected (for negative values) rain
  REAL(KIND=JPRB) :: ZQS(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! corrected (for negative values) snow
  REAL(KIND=JPRB) :: ZTENHA(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZTENQVA(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCP(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! new cp for turbulent diffusion
  REAL(KIND=JPRB) :: ZFPLSL(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! total liquid water flux: diff+sedi+rain
  REAL(KIND=JPRB) :: ZFPLSN(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! total solid water flux: diff+sedi+snow
  REAL(KIND=JPRB) :: ZSEDIQL(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! sedimentation flux of cloud liquid water
  REAL(KIND=JPRB) :: ZSEDIQI(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! sedimentation flux of cloud ice water
  REAL(KIND=JPRB) :: ZDIFCVPPQ(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de CVPP (KFB or EDKF) sur Qv
  REAL(KIND=JPRB) :: ZDIFCVPPS(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de CVPP (KFB or EDKF) sur CpT
  REAL(KIND=JPRB) :: ZDIFCVPPU(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de CVPP (EDKF) sur U
  REAL(KIND=JPRB) :: ZDIFCVPPV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de CVPP (EDKF) sur V
  REAL(KIND=JPRB) :: ZEDMFQ(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Mass flux part of EDMF flux for Qv
  REAL(KIND=JPRB) :: ZEDMFS(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Mass flux part of EDMF flux for CpT
  REAL(KIND=JPRB) :: ZEDMFU(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Mass flux part of EDMF flux for U
  REAL(KIND=JPRB) :: ZEDMFV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Mass flux part of EDMF flux for V
  REAL(KIND=JPRB) :: ZMF_UP(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Mass flux for implicit formulation of EDMF equation (LEDMFI)
  REAL(KIND=JPRB) :: ZCONDCVPPL(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de condensation liquide du a CVVPP (KFB)
  REAL(KIND=JPRB) :: ZCONDCVPPI(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de condensation glace du a CVVPP (KFB)
  REAL(KIND=JPRB) :: ZPRODTH_CVPP(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! Flux de production thermique de TKE du a CVPP(KFB)
  REAL(KIND=JPRB) :: ZDE2MR(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! temporary array for conversion of density to mixing ratio
  REAL(KIND=JPRB) :: ZXDROV(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZXHROV(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZUGST(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZVGST(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZCDROV(YDCPG_OPTS%KLON)  ! ZCDROV     : PCD RENORME EN DENSITE FOIS VITESSE.
  REAL(KIND=JPRB) :: ZCHROV(YDCPG_OPTS%KLON)  ! ZCHROV     : PCH RENORME EN DENSITE FOIS VITESSE.
  REAL(KIND=JPRB) :: ZDQSTS(YDCPG_OPTS%KLON)  ! ZDQSTS     : DERIVEE DE PQSATS PAR RAPPORT A LA TEMPERATURE.
  REAL(KIND=JPRB) :: ZGWDCS(YDCPG_OPTS%KLON)  ! ZGWDCS     : VARIABLE DE SURFACE POUR LE DRAG OROGRAPHIQUE (RHO*N0/G).
  REAL(KIND=JPRB) :: ZHQ(YDCPG_OPTS%KLON)  ! ZHQ        : POIDS DE L'HUMIDITE DE L'AIR DANS L'HUMIDITE DE SURFACE.
  REAL(KIND=JPRB) :: ZHU(YDCPG_OPTS%KLON)  ! ZHU        : POIDS DE L'HUMIDITE SATURANTE DANS L'HUMIDITE DE SURFACE.
  REAL(KIND=JPRB) :: ZHTR(YDCPG_OPTS%KLON)  ! ZHTR       : RESISTANCE A LA TRANSPIRATION DU COUVERT VEGETAL. /  FOLIAGE TRANSPIRATION RESISTANCE.
  REAL(KIND=JPRB) :: ZRTI(YDCPG_OPTS%KLON)  ! ZRTI       : INVERSE DE R*T.
  REAL(KIND=JPRB) :: ZDPHI(YDCPG_OPTS%KLON)  ! ZDPHI      : EPAISSEUR EN GEOPOTENTIEL DU NIVEAU DE SURFACE.
  REAL(KIND=JPRB) :: ZPRS(YDCPG_OPTS%KLON)  ! ZPRS       : CONSTANTE DES GAZ POUR L'AIR AU SOL.
  REAL(KIND=JPRB) :: ZSTAB(YDCPG_OPTS%KLON)  ! ZSTAB      : INDICE DE STABILITE A LA SURFACE.
  REAL(KIND=JPRB) :: ZWFC(YDCPG_OPTS%KLON)  ! ZWFC       : TENEUR EN EAU A LA CAPACITE AUX CHAMPS. /  FIELD CAPACITY WATER CONTENT.
  REAL(KIND=JPRB) :: ZWPMX(YDCPG_OPTS%KLON)  ! ZWPMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR PROFOND.  / MAXIMUM WATER CONTENT OF THE DEEP WATER-TANK.
  REAL(KIND=JPRB) :: ZWLMX(YDCPG_OPTS%KLON)  ! ZWLMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR D'INTERCEPTION. / MAXIMUM WATER CONTENT OF THE INTERCEPTION WATER-TANK.
  REAL(KIND=JPRB) :: ZWSEQ(YDCPG_OPTS%KLON)  ! ZWSEQ      : TENEUR EN EAU A L'EQUILIBRE (EQUILIBRE ENTRE GRAVITE ET CAPILLARITE) EN SURFACE.  / SURFACE WATER CONTENT FOR THE BALANCE BETWEEN GRAVITY AND CAPILLARITY
  REAL(KIND=JPRB) :: ZWSMX(YDCPG_OPTS%KLON)  ! ZWSMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR SUPERFICIEL.  / MAXIMUM WATER CONTENT FOR THE SUPERFICIAL WATER-TANK.
  REAL(KIND=JPRB) :: ZWWILT(YDCPG_OPTS%KLON)  ! ZWWILT     : TENEUR EN EAU AU POINT DE FLETRISSEMENT.  / WATER CONTENT AT THE WILTING POINT.
  REAL(KIND=JPRB) :: ZC3(YDCPG_OPTS%KLON)  ! ZC3        : COEFFICIENT UTILE POUR LE CALCUL DU DRAINAGE
  REAL(KIND=JPRB) :: ZCG(YDCPG_OPTS%KLON)  ! ZCG        : COEFFICIENT THERMIQUE DU SOL NU.  / THERMICAL COEFFICIENT OF BARE GROUND.
  REAL(KIND=JPRB) :: ZCN(YDCPG_OPTS%KLON)  ! ZCN        : COEFFICIENT THERMIQUE DE LA NEIGE./ THERMICAL COEFFICIENT OF SNOW.
  REAL(KIND=JPRB) :: ZNEIJG(YDCPG_OPTS%KLON)  ! ZNEIJG     : FRACTION DE NEIGE RECOUVRANT LE SOL.
  REAL(KIND=JPRB) :: ZNEIJV(YDCPG_OPTS%KLON)  ! ZNEIJV     : FRACTION DE NEIGE RECOUVRANT LA VEGETATION.
  REAL(KIND=JPRB) :: ZPCLS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZBLH(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZQO3(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  ! ZQO3    : RAPPORT DE MELANGE MASSIQUE D'OZONE MOYEN AU-DESSUS DU MODELE / OZONE MIXING RATIO (MASS) AVERAGED-ABOVE
  REAL(KIND=JPRB) :: ZAER(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6)
  REAL(KIND=JPRB) :: ZAERINDS(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZDPHIV(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDPHIT(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZTRSOD(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZCEMTR(YDCPG_OPTS%KLON, 0:1)
  REAL(KIND=JPRB) :: ZCTRSO(YDCPG_OPTS%KLON, 0:1)
  REAL(KIND=JPRB) :: ZALBD(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZALBP(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZSFSWDIR(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZSFSWDIF(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZTRSODIR(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZTRSODIF(YDCPG_OPTS%KLON, YDCPG_OPTS%KSW)
  REAL(KIND=JPRB) :: ZSUDU(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZTHETAVS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZGEOSLC(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZTENT(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZTHETAV(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCOEFN(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)  ! ZCOEFN : COEFFICIENT STATISTIQUE POUR LES FLUX D'EAUX CONDENSEES.
  
  ! LOCAL ARRAYS FOR ACVPPKF
  REAL(KIND=JPRB) :: ZQLI_CVPP(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZNEB_CVPP(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  
  ! Implicit coupling coefficients
  REAL(KIND=JPRB) :: ZCFBTH(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZDTMSE
  REAL(KIND=JPRB) :: ZRHGMT
  REAL(KIND=JPRB) :: ZSTATI
  REAL(KIND=JPRB) :: ZCFATH(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCFAU(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCFBU(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCFBV(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSRAIN(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSSNOW(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSGROUPEL(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZTSN(YDCPG_OPTS%KLON)
  
  !         ACFLUSO (ECUME) local variable
  REAL(KIND=JPRB) :: ZCE(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZCEROV(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZCRTI(YDCPG_OPTS%KLON)
  
  !        New ACDIFV1 local variable
  REAL(KIND=JPRB) :: ZXURO(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZXQRO(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZXTRO(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  
  !        New ACNORGWD local variables
  REAL(KIND=JPRB) :: ZFLX_LOTT_GWU(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZFLX_LOTT_GWV(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  
  !    TKE+ for ACCLDIA
  REAL(KIND=JPRB) :: ZTKE1(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  
  !   For ACVISIH
  REAL(KIND=JPRB) :: ZQGM(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  
  
  !        New ARP_GROUND_PARAM local variable
  REAL(KIND=JPRB) :: ZALPHA1(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZCOEFA(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZLVT(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQICE(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZDIFWQ(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDIFWS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSC_FEVI(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSC_FEVN(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSC_FCLL(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSC_FCLN(YDCPG_OPTS%KLON)
  
  !           TRAJECTORY (For diffusion !) local VARIABLES
  REAL(KIND=JPRB) :: ZTRAJGWD(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)  !Traj buffer saved for TL/AD (YDMODEL%YRML_PHY_MF%YRSIMPHL%LGWDSPNL)
  
  REAL(KIND=JPRB) :: ZAIPCMT(YDCPG_OPTS%KLON)  ! Activity Index of PCMT: 1. if PCMT is active, 0. else case.
  REAL(KIND=JPRB) :: ZQIC(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQLC(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQLI_CVP(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZQC_DET_PCMT(YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZDCAPE(YDCPG_OPTS%KLON)  ! Descending CAPE for gusts.
  
  ! ACRANEB/ACRANEB2 local variables
  REAL(KIND=JPRB) :: ZDECRD(YDCPG_OPTS%KLON)  ! decorrelation depth for cloud overlaps
  
  ! Precipitation type diagnostics
  INTEGER(KIND=JPIM) :: IMOC_CLPH(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZBAY_QRCONV(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZBAY_QSCONV(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZDSA_C1(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDSA_C2(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDSA_CPS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDSA_LHS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZDSA_RS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_CDN(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_CD(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_CH(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_EMIS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_FEVI(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KTSSG + 1)
  REAL(KIND=JPRB) :: ZFLU_NEIJ(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_QSATS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZFLU_QSAT(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZFLU_VEG(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZMSC_FRMQ(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZMSC_LH(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZMSC_LSCPE(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZMSC_QW(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZMSC_TW(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FEFB1(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FEFB2(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FEFB3(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FPLCH(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FPLSH(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FTKEI(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPFL_FTKE(YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZPRC_DPRECIPS2(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
  REAL(KIND=JPRB) :: ZPRC_DPRECIPS(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
  REAL(KIND=JPRB) :: ZRDG_CVGQ(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZRDG_LCVQ(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZRDG_MU0LU(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZRDG_MU0M(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZRDG_MU0N(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZRDG_MU0(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_DDAL(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSAV_DDOM(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSAV_ENTCH(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSAV_FHPS(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_GZ0F(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_GZ0HF(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_HV(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_PBLH(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_QSH(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_UDAL(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSAV_UDGRO(YDCPG_OPTS%KLON)
  REAL(KIND=JPRB) :: ZSAV_UDOM(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  REAL(KIND=JPRB) :: ZSAV_UNEBH(YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
  
  INTEGER(KIND=JPIM) :: INSTEP_DEB
  INTEGER(KIND=JPIM) :: INSTEP_FIN
  INTEGER(KIND=JPIM) :: JLEV
  INTEGER(KIND=JPIM) :: JLON
  INTEGER(KIND=JPIM) :: JSPP
  LOGICAL :: LLCLS
  LOGICAL :: LLHMT
  LOGICAL :: LLREDPR
  REAL(KIND=JPRB) :: ZEPS0
  REAL(KIND=JPRB) :: ZEPSNEB
  REAL(KIND=JPRB) :: ZRVMD
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_FIELD_API
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_PARALLEL
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_COMPUTE
  CLASS(FIELD_4RB), POINTER :: YL_ZDIFEXT
  REAL(KIND=JPRB), POINTER :: ZDIFEXT(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_INLAB_CVPP
  INTEGER(KIND=JPIM), POINTER :: INLAB_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTROV
  REAL(KIND=JPRB), POINTER :: ZXTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXUROV
  REAL(KIND=JPRB), POINTER :: ZXUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMRIPP
  REAL(KIND=JPRB), POINTER :: ZMRIPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKTROV
  REAL(KIND=JPRB), POINTER :: ZKTROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKUROV
  REAL(KIND=JPRB), POINTER :: ZKUROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNBVNO
  REAL(KIND=JPRB), POINTER :: ZNBVNO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQROV
  REAL(KIND=JPRB), POINTER :: ZKQROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZKQLROV
  REAL(KIND=JPRB), POINTER :: ZKQLROV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS
  REAL(KIND=JPRB), POINTER :: ZNEBS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS
  REAL(KIND=JPRB), POINTER :: ZQLIS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBS0
  REAL(KIND=JPRB), POINTER :: ZNEBS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLIS0
  REAL(KIND=JPRB), POINTER :: ZQLIS0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBC0
  REAL(KIND=JPRB), POINTER :: ZNEBC0(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBDIFF
  REAL(KIND=JPRB), POINTER :: ZNEBDIFF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEBCH
  REAL(KIND=JPRB), POINTER :: ZNEBCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZUNEBH
  REAL(KIND=JPRB), POINTER :: ZUNEBH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPCOR
  REAL(KIND=JPRB), POINTER :: ZFPCOR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPOID
  REAL(KIND=JPRB), POINTER :: ZPOID(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQV
  REAL(KIND=JPRB), POINTER :: ZQV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQI
  REAL(KIND=JPRB), POINTER :: ZQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQL
  REAL(KIND=JPRB), POINTER :: ZQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQR
  REAL(KIND=JPRB), POINTER :: ZQR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQS
  REAL(KIND=JPRB), POINTER :: ZQS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENHA
  REAL(KIND=JPRB), POINTER :: ZTENHA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENQVA
  REAL(KIND=JPRB), POINTER :: ZTENQVA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCP
  REAL(KIND=JPRB), POINTER :: ZCP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSL
  REAL(KIND=JPRB), POINTER :: ZFPLSL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFPLSN
  REAL(KIND=JPRB), POINTER :: ZFPLSN(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQL
  REAL(KIND=JPRB), POINTER :: ZSEDIQL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSEDIQI
  REAL(KIND=JPRB), POINTER :: ZSEDIQI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPQ
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPS
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPU
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDIFCVPPV
  REAL(KIND=JPRB), POINTER :: ZDIFCVPPV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFQ
  REAL(KIND=JPRB), POINTER :: ZEDMFQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFS
  REAL(KIND=JPRB), POINTER :: ZEDMFS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFU
  REAL(KIND=JPRB), POINTER :: ZEDMFU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZEDMFV
  REAL(KIND=JPRB), POINTER :: ZEDMFV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMF_UP
  REAL(KIND=JPRB), POINTER :: ZMF_UP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPL
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCONDCVPPI
  REAL(KIND=JPRB), POINTER :: ZCONDCVPPI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRODTH_CVPP
  REAL(KIND=JPRB), POINTER :: ZPRODTH_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZDE2MR
  REAL(KIND=JPRB), POINTER :: ZDE2MR(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXDROV
  REAL(KIND=JPRB), POINTER :: ZXDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZXHROV
  REAL(KIND=JPRB), POINTER :: ZXHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZUGST
  REAL(KIND=JPRB), POINTER :: ZUGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZVGST
  REAL(KIND=JPRB), POINTER :: ZVGST(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCDROV
  REAL(KIND=JPRB), POINTER :: ZCDROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCHROV
  REAL(KIND=JPRB), POINTER :: ZCHROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDQSTS
  REAL(KIND=JPRB), POINTER :: ZDQSTS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZGWDCS
  REAL(KIND=JPRB), POINTER :: ZGWDCS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHQ
  REAL(KIND=JPRB), POINTER :: ZHQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHU
  REAL(KIND=JPRB), POINTER :: ZHU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZHTR
  REAL(KIND=JPRB), POINTER :: ZHTR(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRTI
  REAL(KIND=JPRB), POINTER :: ZRTI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHI
  REAL(KIND=JPRB), POINTER :: ZDPHI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPRS
  REAL(KIND=JPRB), POINTER :: ZPRS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSTAB
  REAL(KIND=JPRB), POINTER :: ZSTAB(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWFC
  REAL(KIND=JPRB), POINTER :: ZWFC(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWPMX
  REAL(KIND=JPRB), POINTER :: ZWPMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWLMX
  REAL(KIND=JPRB), POINTER :: ZWLMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSEQ
  REAL(KIND=JPRB), POINTER :: ZWSEQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWSMX
  REAL(KIND=JPRB), POINTER :: ZWSMX(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZWWILT
  REAL(KIND=JPRB), POINTER :: ZWWILT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZC3
  REAL(KIND=JPRB), POINTER :: ZC3(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCG
  REAL(KIND=JPRB), POINTER :: ZCG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCN
  REAL(KIND=JPRB), POINTER :: ZCN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJG
  REAL(KIND=JPRB), POINTER :: ZNEIJG(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZNEIJV
  REAL(KIND=JPRB), POINTER :: ZNEIJV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZPCLS
  REAL(KIND=JPRB), POINTER :: ZPCLS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZBLH
  REAL(KIND=JPRB), POINTER :: ZBLH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQO3
  REAL(KIND=JPRB), POINTER :: ZQO3(:, :, :)
  CLASS(FIELD_4RB), POINTER :: YL_ZAER
  REAL(KIND=JPRB), POINTER :: ZAER(:, :, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZAERINDS
  REAL(KIND=JPRB), POINTER :: ZAERINDS(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIV
  REAL(KIND=JPRB), POINTER :: ZDPHIV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDPHIT
  REAL(KIND=JPRB), POINTER :: ZDPHIT(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTRSOD
  REAL(KIND=JPRB), POINTER :: ZTRSOD(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCEMTR
  REAL(KIND=JPRB), POINTER :: ZCEMTR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCTRSO
  REAL(KIND=JPRB), POINTER :: ZCTRSO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBD
  REAL(KIND=JPRB), POINTER :: ZALBD(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALBP
  REAL(KIND=JPRB), POINTER :: ZALBP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIR
  REAL(KIND=JPRB), POINTER :: ZSFSWDIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSFSWDIF
  REAL(KIND=JPRB), POINTER :: ZSFSWDIF(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIR
  REAL(KIND=JPRB), POINTER :: ZTRSODIR(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRSODIF
  REAL(KIND=JPRB), POINTER :: ZTRSODIF(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSUDU
  REAL(KIND=JPRB), POINTER :: ZSUDU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTHETAVS
  REAL(KIND=JPRB), POINTER :: ZTHETAVS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZGEOSLC
  REAL(KIND=JPRB), POINTER :: ZGEOSLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTENT
  REAL(KIND=JPRB), POINTER :: ZTENT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTHETAV
  REAL(KIND=JPRB), POINTER :: ZTHETAV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFN
  REAL(KIND=JPRB), POINTER :: ZCOEFN(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVPP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZNEB_CVPP
  REAL(KIND=JPRB), POINTER :: ZNEB_CVPP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBTH
  REAL(KIND=JPRB), POINTER :: ZCFBTH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFATH
  REAL(KIND=JPRB), POINTER :: ZCFATH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFAU
  REAL(KIND=JPRB), POINTER :: ZCFAU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBU
  REAL(KIND=JPRB), POINTER :: ZCFBU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCFBV
  REAL(KIND=JPRB), POINTER :: ZCFBV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSRAIN
  REAL(KIND=JPRB), POINTER :: ZSRAIN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSSNOW
  REAL(KIND=JPRB), POINTER :: ZSSNOW(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSGROUPEL
  REAL(KIND=JPRB), POINTER :: ZSGROUPEL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZTSN
  REAL(KIND=JPRB), POINTER :: ZTSN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCE
  REAL(KIND=JPRB), POINTER :: ZCE(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCEROV
  REAL(KIND=JPRB), POINTER :: ZCEROV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZCRTI
  REAL(KIND=JPRB), POINTER :: ZCRTI(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXURO
  REAL(KIND=JPRB), POINTER :: ZXURO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXQRO
  REAL(KIND=JPRB), POINTER :: ZXQRO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZXTRO
  REAL(KIND=JPRB), POINTER :: ZXTRO(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWU
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWU(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLX_LOTT_GWV
  REAL(KIND=JPRB), POINTER :: ZFLX_LOTT_GWV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTKE1
  REAL(KIND=JPRB), POINTER :: ZTKE1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQGM
  REAL(KIND=JPRB), POINTER :: ZQGM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZALPHA1
  REAL(KIND=JPRB), POINTER :: ZALPHA1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZCOEFA
  REAL(KIND=JPRB), POINTER :: ZCOEFA(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZLVT
  REAL(KIND=JPRB), POINTER :: ZLVT(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQICE
  REAL(KIND=JPRB), POINTER :: ZQICE(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWQ
  REAL(KIND=JPRB), POINTER :: ZDIFWQ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDIFWS
  REAL(KIND=JPRB), POINTER :: ZDIFWS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVI
  REAL(KIND=JPRB), POINTER :: ZSC_FEVI(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FEVN
  REAL(KIND=JPRB), POINTER :: ZSC_FEVN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLL
  REAL(KIND=JPRB), POINTER :: ZSC_FCLL(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSC_FCLN
  REAL(KIND=JPRB), POINTER :: ZSC_FCLN(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZTRAJGWD
  REAL(KIND=JPRB), POINTER :: ZTRAJGWD(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZAIPCMT
  REAL(KIND=JPRB), POINTER :: ZAIPCMT(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQIC
  REAL(KIND=JPRB), POINTER :: ZQIC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLC
  REAL(KIND=JPRB), POINTER :: ZQLC(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQLI_CVP
  REAL(KIND=JPRB), POINTER :: ZQLI_CVP(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZQC_DET_PCMT
  REAL(KIND=JPRB), POINTER :: ZQC_DET_PCMT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDCAPE
  REAL(KIND=JPRB), POINTER :: ZDCAPE(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDECRD
  REAL(KIND=JPRB), POINTER :: ZDECRD(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_IMOC_CLPH
  INTEGER(KIND=JPIM), POINTER :: IMOC_CLPH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QRCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QRCONV(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZBAY_QSCONV
  REAL(KIND=JPRB), POINTER :: ZBAY_QSCONV(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C1
  REAL(KIND=JPRB), POINTER :: ZDSA_C1(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_C2
  REAL(KIND=JPRB), POINTER :: ZDSA_C2(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_CPS
  REAL(KIND=JPRB), POINTER :: ZDSA_CPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_LHS
  REAL(KIND=JPRB), POINTER :: ZDSA_LHS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZDSA_RS
  REAL(KIND=JPRB), POINTER :: ZDSA_RS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CDN
  REAL(KIND=JPRB), POINTER :: ZFLU_CDN(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CD
  REAL(KIND=JPRB), POINTER :: ZFLU_CD(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_CH
  REAL(KIND=JPRB), POINTER :: ZFLU_CH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_EMIS
  REAL(KIND=JPRB), POINTER :: ZFLU_EMIS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_FEVI
  REAL(KIND=JPRB), POINTER :: ZFLU_FEVI(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_NEIJ
  REAL(KIND=JPRB), POINTER :: ZFLU_NEIJ(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_QSATS
  REAL(KIND=JPRB), POINTER :: ZFLU_QSATS(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZFLU_QSAT
  REAL(KIND=JPRB), POINTER :: ZFLU_QSAT(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZFLU_VEG
  REAL(KIND=JPRB), POINTER :: ZFLU_VEG(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_FRMQ
  REAL(KIND=JPRB), POINTER :: ZMSC_FRMQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LH
  REAL(KIND=JPRB), POINTER :: ZMSC_LH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_LSCPE
  REAL(KIND=JPRB), POINTER :: ZMSC_LSCPE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_QW
  REAL(KIND=JPRB), POINTER :: ZMSC_QW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZMSC_TW
  REAL(KIND=JPRB), POINTER :: ZMSC_TW(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB1
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB1(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB2
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FEFB3
  REAL(KIND=JPRB), POINTER :: ZPFL_FEFB3(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLCH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLCH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FPLSH
  REAL(KIND=JPRB), POINTER :: ZPFL_FPLSH(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKEI
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKEI(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPFL_FTKE
  REAL(KIND=JPRB), POINTER :: ZPFL_FTKE(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS2
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS2(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZPRC_DPRECIPS
  REAL(KIND=JPRB), POINTER :: ZPRC_DPRECIPS(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_CVGQ
  REAL(KIND=JPRB), POINTER :: ZRDG_CVGQ(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZRDG_LCVQ
  REAL(KIND=JPRB), POINTER :: ZRDG_LCVQ(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0LU
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0LU(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0M
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0M(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0N
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0N(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZRDG_MU0
  REAL(KIND=JPRB), POINTER :: ZRDG_MU0(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_DDAL(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_DDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_DDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_ENTCH
  REAL(KIND=JPRB), POINTER :: ZSAV_ENTCH(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_FHPS
  REAL(KIND=JPRB), POINTER :: ZSAV_FHPS(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0F
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0F(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_GZ0HF
  REAL(KIND=JPRB), POINTER :: ZSAV_GZ0HF(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_HV
  REAL(KIND=JPRB), POINTER :: ZSAV_HV(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_PBLH
  REAL(KIND=JPRB), POINTER :: ZSAV_PBLH(:, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_QSH
  REAL(KIND=JPRB), POINTER :: ZSAV_QSH(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDAL
  REAL(KIND=JPRB), POINTER :: ZSAV_UDAL(:, :, :)
  CLASS(FIELD_2RB), POINTER :: YL_ZSAV_UDGRO
  REAL(KIND=JPRB), POINTER :: ZSAV_UDGRO(:, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UDOM
  REAL(KIND=JPRB), POINTER :: ZSAV_UDOM(:, :, :)
  CLASS(FIELD_3RB), POINTER :: YL_ZSAV_UNEBH
  REAL(KIND=JPRB), POINTER :: ZSAV_UNEBH(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_DYN0_CTY_EVEL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDCPG_PHY0_XYB_RDELP(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_GELAM_T0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_DL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_DL(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_Q_DM(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_CVGQ_DM(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_U_T0(:, :, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_GEOMETRY_GEMU_T0(:, :)
  REAL(KIND=JPRB), POINTER :: Z_YDVARS_V_T0(:, :, :)
  TYPE(STACK) :: YLSTACK
  
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE', 0, ZHOOK_HANDLE)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  CALL FIELD_NEW(YL_ZDIFEXT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT /),  &
  & PERSISTENT=.true.)
  CALL FIELD_NEW(YL_INLAB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMRIPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKTROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKUROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNBVNO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZKQLROV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLIS0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBC0, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBDIFF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEBCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPCOR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPOID, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENHA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENQVA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFPLSN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSEDIQI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFCVPPV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZEDMFV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMF_UP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCONDCVPPI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRODTH_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDE2MR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZUGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZVGST, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCDROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCHROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDQSTS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGWDCS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZHTR, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSTAB, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWFC, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWPMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWLMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSEQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWSMX, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZWWILT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZC3, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEIJV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPCLS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQO3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAER, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG, 6 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAERINDS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDPHIT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSOD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEMTR, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCTRSO, UBOUNDS=(/ YDCPG_OPTS%KLON, 1 /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALBP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSFSWDIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIR, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRSODIF, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KSW /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSUDU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAVS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZGEOSLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTENT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTHETAV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFN, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZNEB_CVPP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBTH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFATH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFAU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCFBV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSRAIN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSSNOW, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSGROUPEL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTSN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCEROV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCRTI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXURO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXQRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZXTRO, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWU, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLX_LOTT_GWV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTKE1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQGM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZALPHA1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZCOEFA, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZLVT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQICE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWQ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDIFWS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FEVN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLL, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSC_FCLN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZTRAJGWD, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZAIPCMT, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQIC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLC, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQLI_CVP, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZQC_DET_PCMT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDCAPE, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDECRD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_IMOC_CLPH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QRCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZBAY_QSCONV, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C1, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_C2, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_CPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_LHS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZDSA_RS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CDN, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CD, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_CH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_EMIS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_FEVI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KTSSG + 1 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_NEIJ, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSATS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_QSAT, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZFLU_VEG, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_FRMQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_LSCPE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_QW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZMSC_TW, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB1, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FEFB3, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FPLSH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKEI, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPFL_FTKE, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 0 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS2, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC2 /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZPRC_DPRECIPS, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%NDTPREC /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_CVGQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_LCVQ, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0LU, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0M, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0N, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZRDG_MU0, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_DDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_ENTCH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_FHPS, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0F, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_GZ0HF, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_HV, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_PBLH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_QSH, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDAL, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDGRO, UBOUNDS=(/ YDCPG_OPTS%KLON /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UDOM, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  CALL FIELD_NEW(YL_ZSAV_UNEBH, UBOUNDS=(/ YDCPG_OPTS%KLON, YDCPG_OPTS%KFLEVG /), LBOUNDS=(/ 0, 1 /), PERSISTENT=.true.)
  IF (LHOOK) CALL DR_HOOK('CREATE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  
  
  
  
  
  INSTEP_DEB = 1
  INSTEP_FIN = 1
  
  IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE:CPPHINP')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => GET_HOST_DATA_RDWR(YL_ZRDG_MU0LU)
    Z_YDCPG_DYN0_CTY_EVEL => GET_HOST_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
    Z_YDVARS_CVGQ_T0 => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_T0)
    Z_YDCPG_PHY0_XYB_RDELP => GET_HOST_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
    Z_YDVARS_GEOMETRY_GELAM_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
    Z_YDVARS_Q_DL => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DL)
    Z_YDVARS_Q_T0 => GET_HOST_DATA_RDONLY(YDVARS%Q%F_T0)
    Z_YDVARS_CVGQ_DL => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DL)
    ZRDG_MU0 => GET_HOST_DATA_RDWR(YL_ZRDG_MU0)
    Z_YDVARS_Q_DM => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DM)
    Z_YDVARS_CVGQ_DM => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DM)
    ZRDG_MU0N => GET_HOST_DATA_RDWR(YL_ZRDG_MU0N)
    Z_YDVARS_U_T0 => GET_HOST_DATA_RDONLY(YDVARS%U%F_T0)
    ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
    ZRDG_MU0M => GET_HOST_DATA_RDWR(YL_ZRDG_MU0M)
    Z_YDVARS_GEOMETRY_GEMU_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
    Z_YDVARS_V_T0 => GET_HOST_DATA_RDONLY(YDVARS%V%F_T0)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK ) FIRSTPRIVATE( YLCPG_BNDS )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
      CALL YLCPG_BNDS%UPDATE(JBLK)
      
      CALL CPPHINP(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, Z_YDVARS_GEOMETRY_GEMU_T0(:, JBLK),  &
      & Z_YDVARS_GEOMETRY_GELAM_T0(:, JBLK), Z_YDVARS_U_T0(:, :, JBLK), Z_YDVARS_V_T0(:, :, JBLK), Z_YDVARS_Q_T0(:, :, JBLK),  &
      & Z_YDVARS_Q_DL(:, :, JBLK), Z_YDVARS_Q_DM(:, :, JBLK), Z_YDVARS_CVGQ_DL(:, :, JBLK), Z_YDVARS_CVGQ_DM(:, :, JBLK),  &
      & Z_YDCPG_PHY0_XYB_RDELP(:, :, JBLK), Z_YDCPG_DYN0_CTY_EVEL(:, :, JBLK), Z_YDVARS_CVGQ_T0(:, :, JBLK), ZRDG_MU0(:, JBLK),  &
      & ZRDG_MU0LU(:, JBLK), ZRDG_MU0M(:, JBLK), ZRDG_MU0N(:, JBLK), ZRDG_CVGQ(:, :, JBLK))
      
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:CPPHINP')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_MU0LU => GET_HOST_DATA_RDWR(YL_ZRDG_MU0LU)
      Z_YDCPG_DYN0_CTY_EVEL => GET_HOST_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
      Z_YDVARS_CVGQ_T0 => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_T0)
      Z_YDCPG_PHY0_XYB_RDELP => GET_HOST_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
      Z_YDVARS_GEOMETRY_GELAM_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
      Z_YDVARS_Q_DL => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DL)
      Z_YDVARS_Q_T0 => GET_HOST_DATA_RDONLY(YDVARS%Q%F_T0)
      Z_YDVARS_CVGQ_DL => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DL)
      ZRDG_MU0 => GET_HOST_DATA_RDWR(YL_ZRDG_MU0)
      Z_YDVARS_Q_DM => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DM)
      Z_YDVARS_CVGQ_DM => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DM)
      ZRDG_MU0N => GET_HOST_DATA_RDWR(YL_ZRDG_MU0N)
      Z_YDVARS_U_T0 => GET_HOST_DATA_RDONLY(YDVARS%U%F_T0)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZRDG_MU0M => GET_HOST_DATA_RDWR(YL_ZRDG_MU0M)
      Z_YDVARS_GEOMETRY_GEMU_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
      Z_YDVARS_V_T0 => GET_HOST_DATA_RDONLY(YDVARS%V%F_T0)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => NULL()
    Z_YDCPG_DYN0_CTY_EVEL => NULL()
    Z_YDVARS_CVGQ_T0 => NULL()
    Z_YDCPG_PHY0_XYB_RDELP => NULL()
    Z_YDVARS_GEOMETRY_GELAM_T0 => NULL()
    Z_YDVARS_Q_DL => NULL()
    Z_YDVARS_Q_T0 => NULL()
    Z_YDVARS_CVGQ_DL => NULL()
    ZRDG_MU0 => NULL()
    Z_YDVARS_Q_DM => NULL()
    Z_YDVARS_CVGQ_DM => NULL()
    ZRDG_MU0N => NULL()
    Z_YDVARS_U_T0 => NULL()
    ZRDG_CVGQ => NULL()
    ZRDG_MU0M => NULL()
    Z_YDVARS_GEOMETRY_GEMU_T0 => NULL()
    Z_YDVARS_V_T0 => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  IF (LPARALLELMETHOD('OPENMPSINGLECOLUMN', 'APL_ARPEGE:CPPHINP')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => GET_HOST_DATA_RDWR(YL_ZRDG_MU0LU)
    Z_YDCPG_DYN0_CTY_EVEL => GET_HOST_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
    Z_YDVARS_CVGQ_T0 => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_T0)
    Z_YDCPG_PHY0_XYB_RDELP => GET_HOST_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
    Z_YDVARS_GEOMETRY_GELAM_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
    Z_YDVARS_Q_DL => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DL)
    Z_YDVARS_Q_T0 => GET_HOST_DATA_RDONLY(YDVARS%Q%F_T0)
    Z_YDVARS_CVGQ_DL => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DL)
    ZRDG_MU0 => GET_HOST_DATA_RDWR(YL_ZRDG_MU0)
    Z_YDVARS_Q_DM => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DM)
    Z_YDVARS_CVGQ_DM => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DM)
    ZRDG_MU0N => GET_HOST_DATA_RDWR(YL_ZRDG_MU0N)
    Z_YDVARS_U_T0 => GET_HOST_DATA_RDONLY(YDVARS%U%F_T0)
    ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
    ZRDG_MU0M => GET_HOST_DATA_RDWR(YL_ZRDG_MU0M)
    Z_YDVARS_GEOMETRY_GEMU_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
    Z_YDVARS_V_T0 => GET_HOST_DATA_RDONLY(YDVARS%V%F_T0)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
      DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L = stack_l(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U = stack_u(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        
        CALL CPPHINP_OPENACC(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, Z_YDVARS_GEOMETRY_GEMU_T0(:, JBLK),  &
        & Z_YDVARS_GEOMETRY_GELAM_T0(:, JBLK), Z_YDVARS_U_T0(:, :, JBLK), Z_YDVARS_V_T0(:, :, JBLK), Z_YDVARS_Q_T0(:, :, JBLK),  &
        & Z_YDVARS_Q_DL(:, :, JBLK), Z_YDVARS_Q_DM(:, :, JBLK), Z_YDVARS_CVGQ_DL(:, :, JBLK), Z_YDVARS_CVGQ_DM(:, :, JBLK),  &
        & Z_YDCPG_PHY0_XYB_RDELP(:, :, JBLK), Z_YDCPG_DYN0_CTY_EVEL(:, :, JBLK), Z_YDVARS_CVGQ_T0(:, :, JBLK),  &
        & ZRDG_MU0(:, JBLK), ZRDG_MU0LU(:, JBLK), ZRDG_MU0M(:, JBLK), ZRDG_MU0N(:, JBLK), ZRDG_CVGQ(:, :, JBLK), YDSTACK=YLSTACK)
        
        
      END DO
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:CPPHINP')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_MU0LU => GET_HOST_DATA_RDWR(YL_ZRDG_MU0LU)
      Z_YDCPG_DYN0_CTY_EVEL => GET_HOST_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
      Z_YDVARS_CVGQ_T0 => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_T0)
      Z_YDCPG_PHY0_XYB_RDELP => GET_HOST_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
      Z_YDVARS_GEOMETRY_GELAM_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
      Z_YDVARS_Q_DL => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DL)
      Z_YDVARS_Q_T0 => GET_HOST_DATA_RDONLY(YDVARS%Q%F_T0)
      Z_YDVARS_CVGQ_DL => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DL)
      ZRDG_MU0 => GET_HOST_DATA_RDWR(YL_ZRDG_MU0)
      Z_YDVARS_Q_DM => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DM)
      Z_YDVARS_CVGQ_DM => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DM)
      ZRDG_MU0N => GET_HOST_DATA_RDWR(YL_ZRDG_MU0N)
      Z_YDVARS_U_T0 => GET_HOST_DATA_RDONLY(YDVARS%U%F_T0)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZRDG_MU0M => GET_HOST_DATA_RDWR(YL_ZRDG_MU0M)
      Z_YDVARS_GEOMETRY_GEMU_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
      Z_YDVARS_V_T0 => GET_HOST_DATA_RDONLY(YDVARS%V%F_T0)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => NULL()
    Z_YDCPG_DYN0_CTY_EVEL => NULL()
    Z_YDVARS_CVGQ_T0 => NULL()
    Z_YDCPG_PHY0_XYB_RDELP => NULL()
    Z_YDVARS_GEOMETRY_GELAM_T0 => NULL()
    Z_YDVARS_Q_DL => NULL()
    Z_YDVARS_Q_T0 => NULL()
    Z_YDVARS_CVGQ_DL => NULL()
    ZRDG_MU0 => NULL()
    Z_YDVARS_Q_DM => NULL()
    Z_YDVARS_CVGQ_DM => NULL()
    ZRDG_MU0N => NULL()
    Z_YDVARS_U_T0 => NULL()
    ZRDG_CVGQ => NULL()
    ZRDG_MU0M => NULL()
    Z_YDVARS_GEOMETRY_GEMU_T0 => NULL()
    Z_YDVARS_V_T0 => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  IF (LPARALLELMETHOD('OPENACCSINGLECOLUMN', 'APL_ARPEGE:CPPHINP')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => GET_DEVICE_DATA_RDWR(YL_ZRDG_MU0LU)
    Z_YDCPG_DYN0_CTY_EVEL => GET_DEVICE_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
    Z_YDVARS_CVGQ_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%CVGQ%F_T0)
    Z_YDCPG_PHY0_XYB_RDELP => GET_DEVICE_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
    Z_YDVARS_GEOMETRY_GELAM_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
    Z_YDVARS_Q_DL => GET_DEVICE_DATA_RDONLY(YDVARS%Q%F_DL)
    Z_YDVARS_Q_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%Q%F_T0)
    Z_YDVARS_CVGQ_DL => GET_DEVICE_DATA_RDONLY(YDVARS%CVGQ%F_DL)
    ZRDG_MU0 => GET_DEVICE_DATA_RDWR(YL_ZRDG_MU0)
    Z_YDVARS_Q_DM => GET_DEVICE_DATA_RDONLY(YDVARS%Q%F_DM)
    Z_YDVARS_CVGQ_DM => GET_DEVICE_DATA_RDONLY(YDVARS%CVGQ%F_DM)
    ZRDG_MU0N => GET_DEVICE_DATA_RDWR(YL_ZRDG_MU0N)
    Z_YDVARS_U_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%U%F_T0)
    ZRDG_CVGQ => GET_DEVICE_DATA_RDWR(YL_ZRDG_CVGQ)
    ZRDG_MU0M => GET_DEVICE_DATA_RDWR(YL_ZRDG_MU0M)
    Z_YDVARS_GEOMETRY_GEMU_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
    Z_YDVARS_V_T0 => GET_DEVICE_DATA_RDONLY(YDVARS%V%F_T0)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$ACC PARALLEL LOOP GANG PRESENT( ZRDG_MU0LU,Z_YDCPG_DYN0_CTY_EVEL,Z_YDVARS_CVGQ_T0,  &
!$ACC & Z_YDCPG_PHY0_XYB_RDELP,Z_YDVARS_GEOMETRY_GELAM_T0,Z_YDVARS_Q_DL, Z_YDVARS_Q_T0,Z_YDVARS_CVGQ_DL,ZRDG_MU0,  &
!$ACC & Z_YDVARS_Q_DM,Z_YDVARS_CVGQ_DM,ZRDG_MU0N, Z_YDVARS_U_T0,ZRDG_CVGQ,ZRDG_MU0M, Z_YDVARS_GEOMETRY_GEMU_T0,Z_YDVARS_V_T0 )  &
!$ACC & PRIVATE( JBLK ) VECTOR_LENGTH( YDCPG_OPTS%KLON )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
!$ACC LOOP VECTOR PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )
      DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L = stack_l(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U = stack_u(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        
        CALL CPPHINP_OPENACC(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, Z_YDVARS_GEOMETRY_GEMU_T0(:, JBLK),  &
        & Z_YDVARS_GEOMETRY_GELAM_T0(:, JBLK), Z_YDVARS_U_T0(:, :, JBLK), Z_YDVARS_V_T0(:, :, JBLK), Z_YDVARS_Q_T0(:, :, JBLK),  &
        & Z_YDVARS_Q_DL(:, :, JBLK), Z_YDVARS_Q_DM(:, :, JBLK), Z_YDVARS_CVGQ_DL(:, :, JBLK), Z_YDVARS_CVGQ_DM(:, :, JBLK),  &
        & Z_YDCPG_PHY0_XYB_RDELP(:, :, JBLK), Z_YDCPG_DYN0_CTY_EVEL(:, :, JBLK), Z_YDVARS_CVGQ_T0(:, :, JBLK),  &
        & ZRDG_MU0(:, JBLK), ZRDG_MU0LU(:, JBLK), ZRDG_MU0M(:, JBLK), ZRDG_MU0N(:, JBLK), ZRDG_CVGQ(:, :, JBLK), YDSTACK=YLSTACK)
        
        
      END DO
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:CPPHINP')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_MU0LU => GET_HOST_DATA_RDWR(YL_ZRDG_MU0LU)
      Z_YDCPG_DYN0_CTY_EVEL => GET_HOST_DATA_RDONLY(YDCPG_DYN0%CTY%F_EVEL)
      Z_YDVARS_CVGQ_T0 => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_T0)
      Z_YDCPG_PHY0_XYB_RDELP => GET_HOST_DATA_RDONLY(YDCPG_PHY0%XYB%F_RDELP)
      Z_YDVARS_GEOMETRY_GELAM_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GELAM%F_T0)
      Z_YDVARS_Q_DL => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DL)
      Z_YDVARS_Q_T0 => GET_HOST_DATA_RDONLY(YDVARS%Q%F_T0)
      Z_YDVARS_CVGQ_DL => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DL)
      ZRDG_MU0 => GET_HOST_DATA_RDWR(YL_ZRDG_MU0)
      Z_YDVARS_Q_DM => GET_HOST_DATA_RDONLY(YDVARS%Q%F_DM)
      Z_YDVARS_CVGQ_DM => GET_HOST_DATA_RDONLY(YDVARS%CVGQ%F_DM)
      ZRDG_MU0N => GET_HOST_DATA_RDWR(YL_ZRDG_MU0N)
      Z_YDVARS_U_T0 => GET_HOST_DATA_RDONLY(YDVARS%U%F_T0)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZRDG_MU0M => GET_HOST_DATA_RDWR(YL_ZRDG_MU0M)
      Z_YDVARS_GEOMETRY_GEMU_T0 => GET_HOST_DATA_RDONLY(YDVARS%GEOMETRY%GEMU%F_T0)
      Z_YDVARS_V_T0 => GET_HOST_DATA_RDONLY(YDVARS%V%F_T0)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_MU0LU => NULL()
    Z_YDCPG_DYN0_CTY_EVEL => NULL()
    Z_YDVARS_CVGQ_T0 => NULL()
    Z_YDCPG_PHY0_XYB_RDELP => NULL()
    Z_YDVARS_GEOMETRY_GELAM_T0 => NULL()
    Z_YDVARS_Q_DL => NULL()
    Z_YDVARS_Q_T0 => NULL()
    Z_YDVARS_CVGQ_DL => NULL()
    ZRDG_MU0 => NULL()
    Z_YDVARS_Q_DM => NULL()
    Z_YDVARS_CVGQ_DM => NULL()
    ZRDG_MU0N => NULL()
    Z_YDVARS_U_T0 => NULL()
    ZRDG_CVGQ => NULL()
    ZRDG_MU0M => NULL()
    Z_YDVARS_GEOMETRY_GEMU_T0 => NULL()
    Z_YDVARS_V_T0 => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:CPPHINP:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  
  
  IF (LPARALLELMETHOD('OPENMP', 'APL_ARPEGE:ZRDG_LCVQ')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => GET_HOST_DATA_RDWR(YL_ZRDG_LCVQ)
    ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
    ZFLU_QSATS => GET_HOST_DATA_RDWR(YL_ZFLU_QSATS)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK ) FIRSTPRIVATE( YLCPG_BNDS )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
      CALL YLCPG_BNDS%UPDATE(JBLK)
      
      DO JLEV=1,YDCPG_OPTS%KFLEVG
        DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
          ZRDG_LCVQ(JLON, JLEV, JBLK) = ZRDG_CVGQ(JLON, JLEV, JBLK)
        END DO
      END DO
      
      DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        ZFLU_QSATS(JLON, JBLK) = 0.0_JPRB
      END DO
      
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:ZRDG_LCVQ')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_LCVQ => GET_HOST_DATA_RDWR(YL_ZRDG_LCVQ)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZFLU_QSATS => GET_HOST_DATA_RDWR(YL_ZFLU_QSATS)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => NULL()
    ZRDG_CVGQ => NULL()
    ZFLU_QSATS => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  IF (LPARALLELMETHOD('OPENMPSINGLECOLUMN', 'APL_ARPEGE:ZRDG_LCVQ')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => GET_HOST_DATA_RDWR(YL_ZRDG_LCVQ)
    ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
    ZFLU_QSATS => GET_HOST_DATA_RDWR(YL_ZFLU_QSATS)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$OMP PARALLEL DO PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
      DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L = stack_l(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U = stack_u(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        
        DO JLEV=1,YDCPG_OPTS%KFLEVG
          ZRDG_LCVQ(JLON, JLEV, JBLK) = ZRDG_CVGQ(JLON, JLEV, JBLK)
        END DO
        
        ZFLU_QSATS(JLON, JBLK) = 0.0_JPRB
        
      END DO
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:ZRDG_LCVQ')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_LCVQ => GET_HOST_DATA_RDWR(YL_ZRDG_LCVQ)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZFLU_QSATS => GET_HOST_DATA_RDWR(YL_ZFLU_QSATS)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => NULL()
    ZRDG_CVGQ => NULL()
    ZFLU_QSATS => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  IF (LPARALLELMETHOD('OPENACCSINGLECOLUMN', 'APL_ARPEGE:ZRDG_LCVQ')) THEN
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => GET_DEVICE_DATA_RDWR(YL_ZRDG_LCVQ)
    ZRDG_CVGQ => GET_DEVICE_DATA_RDWR(YL_ZRDG_CVGQ)
    ZFLU_QSATS => GET_DEVICE_DATA_RDWR(YL_ZFLU_QSATS)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:GET_DATA', 1, ZHOOK_HANDLE_FIELD_API)
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 0, ZHOOK_HANDLE_COMPUTE)
    CALL YLCPG_BNDS%INIT(YDCPG_OPTS)
!$ACC PARALLEL LOOP GANG PRESENT( ZRDG_LCVQ,ZRDG_CVGQ,ZFLU_QSATS ) PRIVATE( JBLK ) VECTOR_LENGTH( YDCPG_OPTS%KLON )
    DO JBLK=1,YDCPG_OPTS%KGPBLKS
!$ACC LOOP VECTOR PRIVATE( JBLK, JLON, YLCPG_BNDS, YLSTACK )
      DO JLON=1,MIN(YDCPG_OPTS%KLON, YDCPG_OPTS%KGPCOMP - (JBLK - 1)*YDCPG_OPTS%KLON)
        YLCPG_BNDS%KIDIA = JLON
        YLCPG_BNDS%KFDIA = JLON
        YLSTACK%L = stack_l(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        YLSTACK%U = stack_u(YSTACK, JBLK, YDCPG_OPTS%KGPBLKS)
        
        DO JLEV=1,YDCPG_OPTS%KFLEVG
          ZRDG_LCVQ(JLON, JLEV, JBLK) = ZRDG_CVGQ(JLON, JLEV, JBLK)
        END DO
        
        ZFLU_QSATS(JLON, JBLK) = 0.0_JPRB
        
      END DO
    END DO
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:COMPUTE', 1, ZHOOK_HANDLE_COMPUTE)
    IF (LSYNCHOST('APL_ARPEGE:ZRDG_LCVQ')) THEN
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 0, ZHOOK_HANDLE_FIELD_API)
      ZRDG_LCVQ => GET_HOST_DATA_RDWR(YL_ZRDG_LCVQ)
      ZRDG_CVGQ => GET_HOST_DATA_RDWR(YL_ZRDG_CVGQ)
      ZFLU_QSATS => GET_HOST_DATA_RDWR(YL_ZFLU_QSATS)
      IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:SYNCHOST', 1, ZHOOK_HANDLE_FIELD_API)
    END IF
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 0, ZHOOK_HANDLE_FIELD_API)
    ZRDG_LCVQ => NULL()
    ZRDG_CVGQ => NULL()
    ZFLU_QSATS => NULL()
    IF (LHOOK) CALL DR_HOOK('APL_ARPEGE:ZRDG_LCVQ:NULLIFY', 1, ZHOOK_HANDLE_FIELD_API)
  END IF
  
  
  
  IF (LHOOK) CALL DR_HOOK('APL_ARPEGE', 1, ZHOOK_HANDLE)
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 0, ZHOOK_HANDLE_FIELD_API)
  
  IF (ASSOCIATED(YL_ZDIFEXT)) CALL FIELD_DELETE(YL_ZDIFEXT)
  IF (ASSOCIATED(YL_INLAB_CVPP)) CALL FIELD_DELETE(YL_INLAB_CVPP)
  IF (ASSOCIATED(YL_ZXTROV)) CALL FIELD_DELETE(YL_ZXTROV)
  IF (ASSOCIATED(YL_ZXUROV)) CALL FIELD_DELETE(YL_ZXUROV)
  IF (ASSOCIATED(YL_ZMRIPP)) CALL FIELD_DELETE(YL_ZMRIPP)
  IF (ASSOCIATED(YL_ZKTROV)) CALL FIELD_DELETE(YL_ZKTROV)
  IF (ASSOCIATED(YL_ZKUROV)) CALL FIELD_DELETE(YL_ZKUROV)
  IF (ASSOCIATED(YL_ZNBVNO)) CALL FIELD_DELETE(YL_ZNBVNO)
  IF (ASSOCIATED(YL_ZKQROV)) CALL FIELD_DELETE(YL_ZKQROV)
  IF (ASSOCIATED(YL_ZKQLROV)) CALL FIELD_DELETE(YL_ZKQLROV)
  IF (ASSOCIATED(YL_ZNEBS)) CALL FIELD_DELETE(YL_ZNEBS)
  IF (ASSOCIATED(YL_ZQLIS)) CALL FIELD_DELETE(YL_ZQLIS)
  IF (ASSOCIATED(YL_ZNEBS0)) CALL FIELD_DELETE(YL_ZNEBS0)
  IF (ASSOCIATED(YL_ZQLIS0)) CALL FIELD_DELETE(YL_ZQLIS0)
  IF (ASSOCIATED(YL_ZNEBC0)) CALL FIELD_DELETE(YL_ZNEBC0)
  IF (ASSOCIATED(YL_ZNEBDIFF)) CALL FIELD_DELETE(YL_ZNEBDIFF)
  IF (ASSOCIATED(YL_ZNEBCH)) CALL FIELD_DELETE(YL_ZNEBCH)
  IF (ASSOCIATED(YL_ZUNEBH)) CALL FIELD_DELETE(YL_ZUNEBH)
  IF (ASSOCIATED(YL_ZFPCOR)) CALL FIELD_DELETE(YL_ZFPCOR)
  IF (ASSOCIATED(YL_ZPOID)) CALL FIELD_DELETE(YL_ZPOID)
  IF (ASSOCIATED(YL_ZQV)) CALL FIELD_DELETE(YL_ZQV)
  IF (ASSOCIATED(YL_ZQI)) CALL FIELD_DELETE(YL_ZQI)
  IF (ASSOCIATED(YL_ZQL)) CALL FIELD_DELETE(YL_ZQL)
  IF (ASSOCIATED(YL_ZQR)) CALL FIELD_DELETE(YL_ZQR)
  IF (ASSOCIATED(YL_ZQS)) CALL FIELD_DELETE(YL_ZQS)
  IF (ASSOCIATED(YL_ZTENHA)) CALL FIELD_DELETE(YL_ZTENHA)
  IF (ASSOCIATED(YL_ZTENQVA)) CALL FIELD_DELETE(YL_ZTENQVA)
  IF (ASSOCIATED(YL_ZCP)) CALL FIELD_DELETE(YL_ZCP)
  IF (ASSOCIATED(YL_ZFPLSL)) CALL FIELD_DELETE(YL_ZFPLSL)
  IF (ASSOCIATED(YL_ZFPLSN)) CALL FIELD_DELETE(YL_ZFPLSN)
  IF (ASSOCIATED(YL_ZSEDIQL)) CALL FIELD_DELETE(YL_ZSEDIQL)
  IF (ASSOCIATED(YL_ZSEDIQI)) CALL FIELD_DELETE(YL_ZSEDIQI)
  IF (ASSOCIATED(YL_ZDIFCVPPQ)) CALL FIELD_DELETE(YL_ZDIFCVPPQ)
  IF (ASSOCIATED(YL_ZDIFCVPPS)) CALL FIELD_DELETE(YL_ZDIFCVPPS)
  IF (ASSOCIATED(YL_ZDIFCVPPU)) CALL FIELD_DELETE(YL_ZDIFCVPPU)
  IF (ASSOCIATED(YL_ZDIFCVPPV)) CALL FIELD_DELETE(YL_ZDIFCVPPV)
  IF (ASSOCIATED(YL_ZEDMFQ)) CALL FIELD_DELETE(YL_ZEDMFQ)
  IF (ASSOCIATED(YL_ZEDMFS)) CALL FIELD_DELETE(YL_ZEDMFS)
  IF (ASSOCIATED(YL_ZEDMFU)) CALL FIELD_DELETE(YL_ZEDMFU)
  IF (ASSOCIATED(YL_ZEDMFV)) CALL FIELD_DELETE(YL_ZEDMFV)
  IF (ASSOCIATED(YL_ZMF_UP)) CALL FIELD_DELETE(YL_ZMF_UP)
  IF (ASSOCIATED(YL_ZCONDCVPPL)) CALL FIELD_DELETE(YL_ZCONDCVPPL)
  IF (ASSOCIATED(YL_ZCONDCVPPI)) CALL FIELD_DELETE(YL_ZCONDCVPPI)
  IF (ASSOCIATED(YL_ZPRODTH_CVPP)) CALL FIELD_DELETE(YL_ZPRODTH_CVPP)
  IF (ASSOCIATED(YL_ZDE2MR)) CALL FIELD_DELETE(YL_ZDE2MR)
  IF (ASSOCIATED(YL_ZXDROV)) CALL FIELD_DELETE(YL_ZXDROV)
  IF (ASSOCIATED(YL_ZXHROV)) CALL FIELD_DELETE(YL_ZXHROV)
  IF (ASSOCIATED(YL_ZUGST)) CALL FIELD_DELETE(YL_ZUGST)
  IF (ASSOCIATED(YL_ZVGST)) CALL FIELD_DELETE(YL_ZVGST)
  IF (ASSOCIATED(YL_ZCDROV)) CALL FIELD_DELETE(YL_ZCDROV)
  IF (ASSOCIATED(YL_ZCHROV)) CALL FIELD_DELETE(YL_ZCHROV)
  IF (ASSOCIATED(YL_ZDQSTS)) CALL FIELD_DELETE(YL_ZDQSTS)
  IF (ASSOCIATED(YL_ZGWDCS)) CALL FIELD_DELETE(YL_ZGWDCS)
  IF (ASSOCIATED(YL_ZHQ)) CALL FIELD_DELETE(YL_ZHQ)
  IF (ASSOCIATED(YL_ZHU)) CALL FIELD_DELETE(YL_ZHU)
  IF (ASSOCIATED(YL_ZHTR)) CALL FIELD_DELETE(YL_ZHTR)
  IF (ASSOCIATED(YL_ZRTI)) CALL FIELD_DELETE(YL_ZRTI)
  IF (ASSOCIATED(YL_ZDPHI)) CALL FIELD_DELETE(YL_ZDPHI)
  IF (ASSOCIATED(YL_ZPRS)) CALL FIELD_DELETE(YL_ZPRS)
  IF (ASSOCIATED(YL_ZSTAB)) CALL FIELD_DELETE(YL_ZSTAB)
  IF (ASSOCIATED(YL_ZWFC)) CALL FIELD_DELETE(YL_ZWFC)
  IF (ASSOCIATED(YL_ZWPMX)) CALL FIELD_DELETE(YL_ZWPMX)
  IF (ASSOCIATED(YL_ZWLMX)) CALL FIELD_DELETE(YL_ZWLMX)
  IF (ASSOCIATED(YL_ZWSEQ)) CALL FIELD_DELETE(YL_ZWSEQ)
  IF (ASSOCIATED(YL_ZWSMX)) CALL FIELD_DELETE(YL_ZWSMX)
  IF (ASSOCIATED(YL_ZWWILT)) CALL FIELD_DELETE(YL_ZWWILT)
  IF (ASSOCIATED(YL_ZC3)) CALL FIELD_DELETE(YL_ZC3)
  IF (ASSOCIATED(YL_ZCG)) CALL FIELD_DELETE(YL_ZCG)
  IF (ASSOCIATED(YL_ZCN)) CALL FIELD_DELETE(YL_ZCN)
  IF (ASSOCIATED(YL_ZNEIJG)) CALL FIELD_DELETE(YL_ZNEIJG)
  IF (ASSOCIATED(YL_ZNEIJV)) CALL FIELD_DELETE(YL_ZNEIJV)
  IF (ASSOCIATED(YL_ZPCLS)) CALL FIELD_DELETE(YL_ZPCLS)
  IF (ASSOCIATED(YL_ZBLH)) CALL FIELD_DELETE(YL_ZBLH)
  IF (ASSOCIATED(YL_ZQO3)) CALL FIELD_DELETE(YL_ZQO3)
  IF (ASSOCIATED(YL_ZAER)) CALL FIELD_DELETE(YL_ZAER)
  IF (ASSOCIATED(YL_ZAERINDS)) CALL FIELD_DELETE(YL_ZAERINDS)
  IF (ASSOCIATED(YL_ZDPHIV)) CALL FIELD_DELETE(YL_ZDPHIV)
  IF (ASSOCIATED(YL_ZDPHIT)) CALL FIELD_DELETE(YL_ZDPHIT)
  IF (ASSOCIATED(YL_ZTRSOD)) CALL FIELD_DELETE(YL_ZTRSOD)
  IF (ASSOCIATED(YL_ZCEMTR)) CALL FIELD_DELETE(YL_ZCEMTR)
  IF (ASSOCIATED(YL_ZCTRSO)) CALL FIELD_DELETE(YL_ZCTRSO)
  IF (ASSOCIATED(YL_ZALBD)) CALL FIELD_DELETE(YL_ZALBD)
  IF (ASSOCIATED(YL_ZALBP)) CALL FIELD_DELETE(YL_ZALBP)
  IF (ASSOCIATED(YL_ZSFSWDIR)) CALL FIELD_DELETE(YL_ZSFSWDIR)
  IF (ASSOCIATED(YL_ZSFSWDIF)) CALL FIELD_DELETE(YL_ZSFSWDIF)
  IF (ASSOCIATED(YL_ZTRSODIR)) CALL FIELD_DELETE(YL_ZTRSODIR)
  IF (ASSOCIATED(YL_ZTRSODIF)) CALL FIELD_DELETE(YL_ZTRSODIF)
  IF (ASSOCIATED(YL_ZSUDU)) CALL FIELD_DELETE(YL_ZSUDU)
  IF (ASSOCIATED(YL_ZTHETAVS)) CALL FIELD_DELETE(YL_ZTHETAVS)
  IF (ASSOCIATED(YL_ZGEOSLC)) CALL FIELD_DELETE(YL_ZGEOSLC)
  IF (ASSOCIATED(YL_ZTENT)) CALL FIELD_DELETE(YL_ZTENT)
  IF (ASSOCIATED(YL_ZTHETAV)) CALL FIELD_DELETE(YL_ZTHETAV)
  IF (ASSOCIATED(YL_ZCOEFN)) CALL FIELD_DELETE(YL_ZCOEFN)
  IF (ASSOCIATED(YL_ZQLI_CVPP)) CALL FIELD_DELETE(YL_ZQLI_CVPP)
  IF (ASSOCIATED(YL_ZNEB_CVPP)) CALL FIELD_DELETE(YL_ZNEB_CVPP)
  IF (ASSOCIATED(YL_ZCFBTH)) CALL FIELD_DELETE(YL_ZCFBTH)
  IF (ASSOCIATED(YL_ZCFATH)) CALL FIELD_DELETE(YL_ZCFATH)
  IF (ASSOCIATED(YL_ZCFAU)) CALL FIELD_DELETE(YL_ZCFAU)
  IF (ASSOCIATED(YL_ZCFBU)) CALL FIELD_DELETE(YL_ZCFBU)
  IF (ASSOCIATED(YL_ZCFBV)) CALL FIELD_DELETE(YL_ZCFBV)
  IF (ASSOCIATED(YL_ZSRAIN)) CALL FIELD_DELETE(YL_ZSRAIN)
  IF (ASSOCIATED(YL_ZSSNOW)) CALL FIELD_DELETE(YL_ZSSNOW)
  IF (ASSOCIATED(YL_ZSGROUPEL)) CALL FIELD_DELETE(YL_ZSGROUPEL)
  IF (ASSOCIATED(YL_ZTSN)) CALL FIELD_DELETE(YL_ZTSN)
  IF (ASSOCIATED(YL_ZCE)) CALL FIELD_DELETE(YL_ZCE)
  IF (ASSOCIATED(YL_ZCEROV)) CALL FIELD_DELETE(YL_ZCEROV)
  IF (ASSOCIATED(YL_ZCRTI)) CALL FIELD_DELETE(YL_ZCRTI)
  IF (ASSOCIATED(YL_ZXURO)) CALL FIELD_DELETE(YL_ZXURO)
  IF (ASSOCIATED(YL_ZXQRO)) CALL FIELD_DELETE(YL_ZXQRO)
  IF (ASSOCIATED(YL_ZXTRO)) CALL FIELD_DELETE(YL_ZXTRO)
  IF (ASSOCIATED(YL_ZFLX_LOTT_GWU)) CALL FIELD_DELETE(YL_ZFLX_LOTT_GWU)
  IF (ASSOCIATED(YL_ZFLX_LOTT_GWV)) CALL FIELD_DELETE(YL_ZFLX_LOTT_GWV)
  IF (ASSOCIATED(YL_ZTKE1)) CALL FIELD_DELETE(YL_ZTKE1)
  IF (ASSOCIATED(YL_ZQGM)) CALL FIELD_DELETE(YL_ZQGM)
  IF (ASSOCIATED(YL_ZALPHA1)) CALL FIELD_DELETE(YL_ZALPHA1)
  IF (ASSOCIATED(YL_ZCOEFA)) CALL FIELD_DELETE(YL_ZCOEFA)
  IF (ASSOCIATED(YL_ZLVT)) CALL FIELD_DELETE(YL_ZLVT)
  IF (ASSOCIATED(YL_ZQICE)) CALL FIELD_DELETE(YL_ZQICE)
  IF (ASSOCIATED(YL_ZDIFWQ)) CALL FIELD_DELETE(YL_ZDIFWQ)
  IF (ASSOCIATED(YL_ZDIFWS)) CALL FIELD_DELETE(YL_ZDIFWS)
  IF (ASSOCIATED(YL_ZSC_FEVI)) CALL FIELD_DELETE(YL_ZSC_FEVI)
  IF (ASSOCIATED(YL_ZSC_FEVN)) CALL FIELD_DELETE(YL_ZSC_FEVN)
  IF (ASSOCIATED(YL_ZSC_FCLL)) CALL FIELD_DELETE(YL_ZSC_FCLL)
  IF (ASSOCIATED(YL_ZSC_FCLN)) CALL FIELD_DELETE(YL_ZSC_FCLN)
  IF (ASSOCIATED(YL_ZTRAJGWD)) CALL FIELD_DELETE(YL_ZTRAJGWD)
  IF (ASSOCIATED(YL_ZAIPCMT)) CALL FIELD_DELETE(YL_ZAIPCMT)
  IF (ASSOCIATED(YL_ZQIC)) CALL FIELD_DELETE(YL_ZQIC)
  IF (ASSOCIATED(YL_ZQLC)) CALL FIELD_DELETE(YL_ZQLC)
  IF (ASSOCIATED(YL_ZQLI_CVP)) CALL FIELD_DELETE(YL_ZQLI_CVP)
  IF (ASSOCIATED(YL_ZQC_DET_PCMT)) CALL FIELD_DELETE(YL_ZQC_DET_PCMT)
  IF (ASSOCIATED(YL_ZDCAPE)) CALL FIELD_DELETE(YL_ZDCAPE)
  IF (ASSOCIATED(YL_ZDECRD)) CALL FIELD_DELETE(YL_ZDECRD)
  IF (ASSOCIATED(YL_IMOC_CLPH)) CALL FIELD_DELETE(YL_IMOC_CLPH)
  IF (ASSOCIATED(YL_ZBAY_QRCONV)) CALL FIELD_DELETE(YL_ZBAY_QRCONV)
  IF (ASSOCIATED(YL_ZBAY_QSCONV)) CALL FIELD_DELETE(YL_ZBAY_QSCONV)
  IF (ASSOCIATED(YL_ZDSA_C1)) CALL FIELD_DELETE(YL_ZDSA_C1)
  IF (ASSOCIATED(YL_ZDSA_C2)) CALL FIELD_DELETE(YL_ZDSA_C2)
  IF (ASSOCIATED(YL_ZDSA_CPS)) CALL FIELD_DELETE(YL_ZDSA_CPS)
  IF (ASSOCIATED(YL_ZDSA_LHS)) CALL FIELD_DELETE(YL_ZDSA_LHS)
  IF (ASSOCIATED(YL_ZDSA_RS)) CALL FIELD_DELETE(YL_ZDSA_RS)
  IF (ASSOCIATED(YL_ZFLU_CDN)) CALL FIELD_DELETE(YL_ZFLU_CDN)
  IF (ASSOCIATED(YL_ZFLU_CD)) CALL FIELD_DELETE(YL_ZFLU_CD)
  IF (ASSOCIATED(YL_ZFLU_CH)) CALL FIELD_DELETE(YL_ZFLU_CH)
  IF (ASSOCIATED(YL_ZFLU_EMIS)) CALL FIELD_DELETE(YL_ZFLU_EMIS)
  IF (ASSOCIATED(YL_ZFLU_FEVI)) CALL FIELD_DELETE(YL_ZFLU_FEVI)
  IF (ASSOCIATED(YL_ZFLU_NEIJ)) CALL FIELD_DELETE(YL_ZFLU_NEIJ)
  IF (ASSOCIATED(YL_ZFLU_QSATS)) CALL FIELD_DELETE(YL_ZFLU_QSATS)
  IF (ASSOCIATED(YL_ZFLU_QSAT)) CALL FIELD_DELETE(YL_ZFLU_QSAT)
  IF (ASSOCIATED(YL_ZFLU_VEG)) CALL FIELD_DELETE(YL_ZFLU_VEG)
  IF (ASSOCIATED(YL_ZMSC_FRMQ)) CALL FIELD_DELETE(YL_ZMSC_FRMQ)
  IF (ASSOCIATED(YL_ZMSC_LH)) CALL FIELD_DELETE(YL_ZMSC_LH)
  IF (ASSOCIATED(YL_ZMSC_LSCPE)) CALL FIELD_DELETE(YL_ZMSC_LSCPE)
  IF (ASSOCIATED(YL_ZMSC_QW)) CALL FIELD_DELETE(YL_ZMSC_QW)
  IF (ASSOCIATED(YL_ZMSC_TW)) CALL FIELD_DELETE(YL_ZMSC_TW)
  IF (ASSOCIATED(YL_ZPFL_FEFB1)) CALL FIELD_DELETE(YL_ZPFL_FEFB1)
  IF (ASSOCIATED(YL_ZPFL_FEFB2)) CALL FIELD_DELETE(YL_ZPFL_FEFB2)
  IF (ASSOCIATED(YL_ZPFL_FEFB3)) CALL FIELD_DELETE(YL_ZPFL_FEFB3)
  IF (ASSOCIATED(YL_ZPFL_FPLCH)) CALL FIELD_DELETE(YL_ZPFL_FPLCH)
  IF (ASSOCIATED(YL_ZPFL_FPLSH)) CALL FIELD_DELETE(YL_ZPFL_FPLSH)
  IF (ASSOCIATED(YL_ZPFL_FTKEI)) CALL FIELD_DELETE(YL_ZPFL_FTKEI)
  IF (ASSOCIATED(YL_ZPFL_FTKE)) CALL FIELD_DELETE(YL_ZPFL_FTKE)
  IF (ASSOCIATED(YL_ZPRC_DPRECIPS2)) CALL FIELD_DELETE(YL_ZPRC_DPRECIPS2)
  IF (ASSOCIATED(YL_ZPRC_DPRECIPS)) CALL FIELD_DELETE(YL_ZPRC_DPRECIPS)
  IF (ASSOCIATED(YL_ZRDG_CVGQ)) CALL FIELD_DELETE(YL_ZRDG_CVGQ)
  IF (ASSOCIATED(YL_ZRDG_LCVQ)) CALL FIELD_DELETE(YL_ZRDG_LCVQ)
  IF (ASSOCIATED(YL_ZRDG_MU0LU)) CALL FIELD_DELETE(YL_ZRDG_MU0LU)
  IF (ASSOCIATED(YL_ZRDG_MU0M)) CALL FIELD_DELETE(YL_ZRDG_MU0M)
  IF (ASSOCIATED(YL_ZRDG_MU0N)) CALL FIELD_DELETE(YL_ZRDG_MU0N)
  IF (ASSOCIATED(YL_ZRDG_MU0)) CALL FIELD_DELETE(YL_ZRDG_MU0)
  IF (ASSOCIATED(YL_ZSAV_DDAL)) CALL FIELD_DELETE(YL_ZSAV_DDAL)
  IF (ASSOCIATED(YL_ZSAV_DDOM)) CALL FIELD_DELETE(YL_ZSAV_DDOM)
  IF (ASSOCIATED(YL_ZSAV_ENTCH)) CALL FIELD_DELETE(YL_ZSAV_ENTCH)
  IF (ASSOCIATED(YL_ZSAV_FHPS)) CALL FIELD_DELETE(YL_ZSAV_FHPS)
  IF (ASSOCIATED(YL_ZSAV_GZ0F)) CALL FIELD_DELETE(YL_ZSAV_GZ0F)
  IF (ASSOCIATED(YL_ZSAV_GZ0HF)) CALL FIELD_DELETE(YL_ZSAV_GZ0HF)
  IF (ASSOCIATED(YL_ZSAV_HV)) CALL FIELD_DELETE(YL_ZSAV_HV)
  IF (ASSOCIATED(YL_ZSAV_PBLH)) CALL FIELD_DELETE(YL_ZSAV_PBLH)
  IF (ASSOCIATED(YL_ZSAV_QSH)) CALL FIELD_DELETE(YL_ZSAV_QSH)
  IF (ASSOCIATED(YL_ZSAV_UDAL)) CALL FIELD_DELETE(YL_ZSAV_UDAL)
  IF (ASSOCIATED(YL_ZSAV_UDGRO)) CALL FIELD_DELETE(YL_ZSAV_UDGRO)
  IF (ASSOCIATED(YL_ZSAV_UDOM)) CALL FIELD_DELETE(YL_ZSAV_UDOM)
  IF (ASSOCIATED(YL_ZSAV_UNEBH)) CALL FIELD_DELETE(YL_ZSAV_UNEBH)
  IF (LHOOK) CALL DR_HOOK('DELETE_TEMPORARIES', 1, ZHOOK_HANDLE_FIELD_API)
  
END SUBROUTINE APL_ARPEGE
