SUBROUTINE APL_ARPEGE(YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, &
& YDCPG_MISC, YDCPG_GPAR, YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF, YDCPG_SL2, YDVARS,       &
& YDMODEL, YDDDH)

!**** *APL_ARPEGE*  - Call ARPEGE physics

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 28-04-2021

!     Modifications.
!     --------------
!     13-Jul-2022 R. El Khatib Fix initialization of ZQGM
! End Modifications
!-------------------------------------------------------------------------------

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE, CPG_DYN_TYPE, &
                              & CPG_GPAR_TYPE, CPG_PHY_TYPE
USE CPG_SL2_TYPE_MOD   , ONLY : CPG_SL2_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD  &
                     & , ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                     & , ONLY : MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
                     & , ONLY : MF_PHYS_NEXT_STATE_TYPE
USE TYPE_MODEL         , ONLY : MODEL

USE PARKIND1           , ONLY : JPIM     ,JPRB
USE YOMHOOK            , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE DDH_MIX            , ONLY : TYP_DDH

IMPLICIT NONE

TYPE(MF_PHYS_BASE_STATE_TYPE),  INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(MF_PHYS_NEXT_STATE_TYPE),  INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
TYPE(GEOMETRY),                 INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),            INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE),            INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_GPAR_TYPE),            INTENT(INOUT) :: YDCPG_GPAR
TYPE(CPG_PHY_TYPE),             INTENT(IN)    :: YDCPG_PHY0
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(CPG_DYN_TYPE),             INTENT(IN)    :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE),        INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(CPG_SL2_TYPE),             INTENT(INOUT) :: YDCPG_SL2
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
TYPE(TYP_DDH),                  INTENT(INOUT) :: YDDDH

#include "accldia.intfb.h"
#include "acclph.intfb.h"
#include "acdnshf.intfb.h"
#include "acdrag.intfb.h"
#include "acdrme.intfb.h"
#include "acevadcape.intfb.h"
#include "achmt.intfb.h"
#include "achmtls.intfb.h"
#include "acpluis.intfb.h"
#include "acsol.intfb.h"
#include "actqsat.intfb.h"
#include "acvisih.intfb.h"
#include "aplpar_init.intfb.h"
#include "checkmv.intfb.h"
#include "cpphinp.intfb.h"
#include "cpqsol.intfb.h"
#include "mf_phys_bayrad.intfb.h"
#include "mf_phys_corwat.intfb.h"
#include "mf_phys_cvv.intfb.h"
#include "mf_phys_fpl_part1.intfb.h"
#include "mf_phys_fpl_part2.intfb.h"
#include "mf_phys_mocon.intfb.h"
#include "mf_phys_precips.intfb.h"
#include "mf_phys_save_phsurf_part1.intfb.h"
#include "mf_phys_save_phsurf_part2.intfb.h"
#include "mf_phys_transfer.intfb.h"
#include "ppwetpoint.intfb.h"
#include "qngcor.intfb.h"
#include "aplpar_flexdia.intfb.h"
#include "apl_arpege_oceanic_fluxes.intfb.h"
#include "apl_wind_gust.intfb.h"
#include "apl_arpege_shallow_convection_and_turbulence.intfb.h"
#include "apl_arpege_albedo_computation.intfb.h"
#include "apl_arpege_aerosols_for_radiation.intfb.h"
#include "apl_arpege_cloudiness.intfb.h"
#include "apl_arpege_radiation.intfb.h"
#include "apl_arpege_soil_hydro.intfb.h"
#include "apl_arpege_surface.intfb.h"
#include "apl_arpege_deep_convection.intfb.h"
#include "apl_arpege_precipitation.intfb.h"
#include "apl_arpege_hydro_budget.intfb.h"
#include "apl_arpege_surface_update.intfb.h"
#include "apl_arpege_atmosphere_update.intfb.h"
#include "apl_arpege_init.intfb.h"
#include "apl_arpege_init_surfex.intfb.h"
#include "apl_arpege_dprecips.intfb.h"


REAL(KIND=JPRB) :: ZDIFEXT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)     ! Extra-GFL fluxes.
INTEGER(KIND=JPIM) :: INLAB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZXTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG),ZXUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZMRIPP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZKTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG),ZKUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG),ZNBVNO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZKQROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG),ZKQLROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZNEBS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZQLIS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZNEBS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZQLIS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZNEBC0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)          ! Nebulosite convective radiative
REAL(KIND=JPRB) :: ZNEBDIFF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)        ! Nebulosite: calcul de la diffusion
REAL(KIND=JPRB) :: ZNEBCH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)          ! Nebulosite convective condensation
REAL(KIND=JPRB) :: ZUNEBH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)          ! Nebulosite convective histo
REAL(KIND=JPRB) :: ZFPCOR(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZPOID(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)           ! DP/(YDMODEL%YRCST%RG*DT) FOR A GIVEN LEVEL AND A GIVEN TIME STEP.
REAL(KIND=JPRB) :: ZQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! corrected (for negative values) vapour
REAL(KIND=JPRB) :: ZQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! corrected (for negative values) cloud ice
REAL(KIND=JPRB) :: ZQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! corrected (for negative values) cloud liquid
REAL(KIND=JPRB) :: ZQR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! corrected (for negative values) rain
REAL(KIND=JPRB) :: ZQS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! corrected (for negative values) snow
REAL(KIND=JPRB) :: ZTENHA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZTENQVA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)             ! new cp for turbulent diffusion
REAL(KIND=JPRB) :: ZFPLSL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! total liquid water flux: diff+sedi+rain
REAL(KIND=JPRB) :: ZFPLSN(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! total solid water flux: diff+sedi+snow
REAL(KIND=JPRB) :: ZSEDIQL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)       ! sedimentation flux of cloud liquid water
REAL(KIND=JPRB) :: ZSEDIQI(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)       ! sedimentation flux of cloud ice water
REAL(KIND=JPRB) :: ZDIFCVPPQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)     ! Flux de CVPP (KFB or EDKF) sur Qv
REAL(KIND=JPRB) :: ZDIFCVPPS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)     ! Flux de CVPP (KFB or EDKF) sur CpT
REAL(KIND=JPRB) :: ZDIFCVPPU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)     ! Flux de CVPP (EDKF) sur U
REAL(KIND=JPRB) :: ZDIFCVPPV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)     ! Flux de CVPP (EDKF) sur V
REAL(KIND=JPRB) :: ZEDMFQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! Mass flux part of EDMF flux for Qv
REAL(KIND=JPRB) :: ZEDMFS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! Mass flux part of EDMF flux for CpT
REAL(KIND=JPRB) :: ZEDMFU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! Mass flux part of EDMF flux for U
REAL(KIND=JPRB) :: ZEDMFV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! Mass flux part of EDMF flux for V
REAL(KIND=JPRB) :: ZMF_UP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)        ! Mass flux for implicit formulation of EDMF equation (LEDMFI)
REAL(KIND=JPRB) :: ZCONDCVPPL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)    ! Flux de condensation liquide du a CVVPP (KFB)
REAL(KIND=JPRB) :: ZCONDCVPPI(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)    ! Flux de condensation glace du a CVVPP (KFB)
REAL(KIND=JPRB) :: ZPRODTH_CVPP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)  ! Flux de production thermique de TKE du a CVPP(KFB)
REAL(KIND=JPRB) :: ZDE2MR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)          ! temporary array for conversion of density to mixing ratio
REAL(KIND=JPRB) :: ZXDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZXHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZUGST(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZVGST(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZCDROV(YDCPG_OPTS%KLON)                            ! ZCDROV     : PCD RENORME EN DENSITE FOIS VITESSE.
REAL(KIND=JPRB) :: ZCHROV(YDCPG_OPTS%KLON)                            ! ZCHROV     : PCH RENORME EN DENSITE FOIS VITESSE.
REAL(KIND=JPRB) :: ZDQSTS(YDCPG_OPTS%KLON)                            ! ZDQSTS     : DERIVEE DE PQSATS PAR RAPPORT A LA TEMPERATURE.
REAL(KIND=JPRB) :: ZGWDCS(YDCPG_OPTS%KLON)                            ! ZGWDCS     : VARIABLE DE SURFACE POUR LE DRAG OROGRAPHIQUE (RHO*N0/G).
REAL(KIND=JPRB) :: ZHQ(YDCPG_OPTS%KLON)                               ! ZHQ        : POIDS DE L'HUMIDITE DE L'AIR DANS L'HUMIDITE DE SURFACE.
REAL(KIND=JPRB) :: ZHU(YDCPG_OPTS%KLON)                               ! ZHU        : POIDS DE L'HUMIDITE SATURANTE DANS L'HUMIDITE DE SURFACE.
REAL(KIND=JPRB) :: ZHTR(YDCPG_OPTS%KLON)                              ! ZHTR       : RESISTANCE A LA TRANSPIRATION DU COUVERT VEGETAL. /  FOLIAGE TRANSPIRATION RESISTANCE.
REAL(KIND=JPRB) :: ZRTI(YDCPG_OPTS%KLON)                              ! ZRTI       : INVERSE DE R*T.
REAL(KIND=JPRB) :: ZDPHI(YDCPG_OPTS%KLON)                             ! ZDPHI      : EPAISSEUR EN GEOPOTENTIEL DU NIVEAU DE SURFACE.
REAL(KIND=JPRB) :: ZPRS(YDCPG_OPTS%KLON)                              ! ZPRS       : CONSTANTE DES GAZ POUR L'AIR AU SOL.
REAL(KIND=JPRB) :: ZSTAB(YDCPG_OPTS%KLON)                             ! ZSTAB      : INDICE DE STABILITE A LA SURFACE.
REAL(KIND=JPRB) :: ZWFC(YDCPG_OPTS%KLON)                              ! ZWFC       : TENEUR EN EAU A LA CAPACITE AUX CHAMPS. /  FIELD CAPACITY WATER CONTENT.
REAL(KIND=JPRB) :: ZWPMX(YDCPG_OPTS%KLON)                             ! ZWPMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR PROFOND.  / MAXIMUM WATER CONTENT OF THE DEEP WATER-TANK.
REAL(KIND=JPRB) :: ZWLMX(YDCPG_OPTS%KLON)                             ! ZWLMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR D'INTERCEPTION. / MAXIMUM WATER CONTENT OF THE INTERCEPTION WATER-TANK.
REAL(KIND=JPRB) :: ZWSEQ(YDCPG_OPTS%KLON)                             ! ZWSEQ      : TENEUR EN EAU A L'EQUILIBRE (EQUILIBRE ENTRE GRAVITE ET CAPILLARITE) EN SURFACE.  / SURFACE WATER CONTENT FOR THE BALANCE BETWEEN GRAVITY AND CAPILLARITY
REAL(KIND=JPRB) :: ZWSMX(YDCPG_OPTS%KLON)                             ! ZWSMX      : TENEUR EN EAU MAXIMALE DU RESERVOIR SUPERFICIEL.  / MAXIMUM WATER CONTENT FOR THE SUPERFICIAL WATER-TANK.
REAL(KIND=JPRB) :: ZWWILT(YDCPG_OPTS%KLON)                            ! ZWWILT     : TENEUR EN EAU AU POINT DE FLETRISSEMENT.  / WATER CONTENT AT THE WILTING POINT.
REAL(KIND=JPRB) :: ZC3(YDCPG_OPTS%KLON)                               ! ZC3        : COEFFICIENT UTILE POUR LE CALCUL DU DRAINAGE
REAL(KIND=JPRB) :: ZCG(YDCPG_OPTS%KLON)                               ! ZCG        : COEFFICIENT THERMIQUE DU SOL NU.  / THERMICAL COEFFICIENT OF BARE GROUND.
REAL(KIND=JPRB) :: ZCN(YDCPG_OPTS%KLON)                               ! ZCN        : COEFFICIENT THERMIQUE DE LA NEIGE./ THERMICAL COEFFICIENT OF SNOW.
REAL(KIND=JPRB) :: ZNEIJG(YDCPG_OPTS%KLON)                            ! ZNEIJG     : FRACTION DE NEIGE RECOUVRANT LE SOL.
REAL(KIND=JPRB) :: ZNEIJV(YDCPG_OPTS%KLON)                            ! ZNEIJV     : FRACTION DE NEIGE RECOUVRANT LA VEGETATION.
REAL(KIND=JPRB) :: ZPCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZBLH(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZQO3(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)          ! ZQO3    : RAPPORT DE MELANGE MASSIQUE D'OZONE MOYEN AU-DESSUS DU MODELE / OZONE MIXING RATIO (MASS) AVERAGED-ABOVE
REAL(KIND=JPRB) :: ZAER(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,6)
REAL(KIND=JPRB) :: ZAERINDS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZDPHIV(YDCPG_OPTS%KLON),ZDPHIT(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZTRSOD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZCEMTR(YDCPG_OPTS%KLON,0:1) , ZCTRSO(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB) :: ZALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW), ZALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB) :: ZSFSWDIR (YDCPG_OPTS%KLON,YDCPG_OPTS%KSW), ZSFSWDIF (YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB) :: ZTRSODIR (YDCPG_OPTS%KLON,YDCPG_OPTS%KSW), ZTRSODIF (YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB) :: ZSUDU(YDCPG_OPTS%KLON) 
REAL(KIND=JPRB) :: ZTHETAVS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZGEOSLC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZTENT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZTHETAV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCOEFN(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)          ! ZCOEFN : COEFFICIENT STATISTIQUE POUR LES FLUX D'EAUX CONDENSEES.

! LOCAL ARRAYS FOR ACVPPKF
REAL(KIND=JPRB) :: ZQLI_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZNEB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)

! Implicit coupling coefficients
REAL(KIND=JPRB) :: ZCFBTH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZDTMSE,ZRHGMT,ZSTATI
REAL(KIND=JPRB) :: ZCFATH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCFAU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCFBU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCFBV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZSRAIN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSSNOW(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSGROUPEL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZTSN(YDCPG_OPTS%KLON)

!         ACFLUSO (ECUME) local variable
REAL(KIND=JPRB) :: ZCE(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZCEROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZCRTI(YDCPG_OPTS%KLON)

!        New ACDIFV1 local variable
REAL(KIND=JPRB) :: ZXURO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZXQRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZXTRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)

!        New ACNORGWD local variables
REAL(KIND=JPRB) :: ZFLX_LOTT_GWU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZFLX_LOTT_GWV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)

!    TKE+ for ACCLDIA
REAL(KIND=JPRB) :: ZTKE1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)

!   For ACVISIH
REAL(KIND=JPRB) :: ZQGM(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)


!        New ARP_GROUND_PARAM local variable
REAL(KIND=JPRB) :: ZALPHA1(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZCOEFA (YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZLVT   (YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZQICE  (YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZDIFWQ (YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZDIFWS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSC_FEVI (YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSC_FEVN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSC_FCLL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) :: ZSC_FCLN(YDCPG_OPTS%KLON)

!           TRAJECTORY (For diffusion !) local VARIABLES
REAL(KIND=JPRB) :: ZTRAJGWD(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG) !Traj buffer saved for TL/AD (YDMODEL%YRML_PHY_MF%YRSIMPHL%LGWDSPNL)

REAL(KIND=JPRB) :: ZAIPCMT(YDCPG_OPTS%KLON) ! Activity Index of PCMT: 1. if PCMT is active, 0. else case.
REAL(KIND=JPRB) :: ZQIC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG),ZQLC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZQLI_CVP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZQC_DET_PCMT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) :: ZDCAPE(YDCPG_OPTS%KLON) ! Descending CAPE for gusts.

! ACRANEB/ACRANEB2 local variables
REAL(KIND=JPRB) :: ZDECRD   (YDCPG_OPTS%KLON) ! decorrelation depth for cloud overlaps

! Precipitation type diagnostics
INTEGER (KIND=JPIM)  :: IMOC_CLPH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZBAY_QRCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZBAY_QSCONV (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZDSA_C1 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZDSA_C2 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZDSA_CPS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZDSA_LHS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZDSA_RS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_CDN (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_CD (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_CH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_EMIS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_FEVI (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB)     :: ZFLU_NEIJ (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_QSATS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZFLU_QSAT (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZFLU_VEG (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZMSC_FRMQ (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZMSC_LH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZMSC_LSCPE (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZMSC_QW (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZMSC_TW (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FEFB1 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FEFB2 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FEFB3 (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FPLCH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FPLSH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FTKEI (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPFL_FTKE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZPRC_DPRECIPS2 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC2)
REAL(KIND=JPRB)     :: ZPRC_DPRECIPS  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%NDTPREC)
REAL(KIND=JPRB)     :: ZRDG_CVGQ (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZRDG_LCVQ (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZRDG_MU0LU (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZRDG_MU0M (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZRDG_MU0N (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZRDG_MU0 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_DDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZSAV_DDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZSAV_ENTCH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZSAV_FHPS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_GZ0F (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_GZ0HF (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_HV (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_PBLH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_QSH  (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_UDAL (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZSAV_UDGRO (YDCPG_OPTS%KLON)
REAL(KIND=JPRB)     :: ZSAV_UDOM (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)     :: ZSAV_UNEBH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)

INTEGER(KIND=JPIM) :: INSTEP_DEB, INSTEP_FIN
INTEGER(KIND=JPIM) :: JLEV, JLON, JSPP
LOGICAL :: LLCLS, LLHMT, LLREDPR
REAL(KIND=JPRB) :: ZEPS0, ZEPSNEB
REAL(KIND=JPRB) :: ZRVMD

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('APL_ARPEGE',0,ZHOOK_HANDLE)

ASSOCIATE(YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY, YDTOPH=>YDMODEL%YRML_PHY_MF%YRTOPH, YDRIP=>YDMODEL%YRML_GCONF%YRRIP,             &
& YDARPHY=>YDMODEL%YRML_PHY_MF%YRARPHY, YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY, YDPHY2=>YDMODEL%YRML_PHY_MF%YRPHY2,               &
& YGFL=>YDMODEL%YRML_GCONF%YGFL, YDSTA=>YDGEOMETRY%YRSTA, YDMCC=>YDMODEL%YRML_AOC%YRMCC, YDPHY3=>YDMODEL%YRML_PHY_MF%YRPHY3, &
& YDSPP_CONFIG=>YDMODEL%YRML_GCONF%YRSPP_CONFIG,                                                                             &
& YDPHY1=>YDMODEL%YRML_PHY_MF%YRPHY1, YDPHY0=>YDMODEL%YRML_PHY_MF%YRPHY0)


ASSOCIATE(TSPHY=>YDPHY2%TSPHY, NTSSG=>YDDPHY%NTSSG, LMSE=>YDARPHY%LMSE, LNEBN=>YDPHY%LNEBN, NDPSFI=>YDPHY%NDPSFI, &
& LRRGUST=>YDPHY%LRRGUST, LEDR=>YDPHY%LEDR, NTPLUI=>YDTOPH%NTPLUI, XMINLM=>YDPHY0%XMINLM, XMAXLM=>YDPHY0%XMAXLM,  &
& HSOLIWR=>YDPHY1%HSOLIWR, WSMX=>YDPHY1%WSMX, HSOLIT0=>YDPHY1%HSOLIT0, HSOL=>YDPHY1%HSOL, WPMX=>YDPHY1%WPMX,      &
& LRAFTKE=>YDPHY2%LRAFTKE, HVCLS=>YDPHY2%HVCLS, HTCLS=>YDPHY2%HTCLS, RII0=>YDPHY3%RII0, YA=>YGFL%YA,              &
& YIRAD=>YGFL%YIRAD, YLRAD=>YGFL%YLRAD, LSTRAS=>YDPHY%LSTRAS, LSOLV=>YDPHY%LSOLV, NTDRME=>YDTOPH%NTDRME,          &
& NTDRAG=>YDTOPH%NTDRAG, NTQSAT=>YDTOPH%NTQSAT, LMCC03=>YDMCC%LMCC03, RHGMT=>YDRIP%RHGMT, RSTATI=>YDRIP%RSTATI,   &
& LGCHECKMV=>YDPHY%LGCHECKMV             )

ASSOCIATE(PAPRSF=> YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYDF, PAPRS => YDMF_PHYS_BASE_STATE%YCPG_PHY%PREHYD,                                   &
& PAPHIF=> YDMF_PHYS_BASE_STATE%YCPG_DYN%PHIF, PAPHI=> YDMF_PHYS_BASE_STATE%YCPG_DYN%PHI, PDELP => YDMF_PHYS_BASE_STATE%YCPG_PHY%XYB%DELP, &
& PR=>YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%R, PT=> YDMF_PHYS_BASE_STATE%T, PU=> YDMF_PHYS_BASE_STATE%U,                                       &
& PV=>YDMF_PHYS_BASE_STATE%V, PCP=>YDMF_PHYS_BASE_STATE%YCPG_DYN%RCP%CP)

INSTEP_DEB=1
INSTEP_FIN=1

!$ACDC PARALLEL,TARGET=OpenMP/OpenMPSingleColumn/OpenACCSingleColumn,NAME=CPPHINP {

CALL CPPHINP(YDGEOMETRY, YDMODEL, YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA, YDVARS%GEOMETRY%GEMU%T0,                     &
& YDVARS%GEOMETRY%GELAM%T0, YDVARS%U%T0, YDVARS%V%T0, YDVARS%Q%T0, YDVARS%Q%DL, YDVARS%Q%DM, YDVARS%CVGQ%DL,       &
& YDVARS%CVGQ%DM, YDCPG_PHY0%XYB%RDELP, YDCPG_DYN0%CTY%EVEL, YDVARS%CVGQ%T0, ZRDG_MU0, ZRDG_MU0LU, ZRDG_MU0M,      &
& ZRDG_MU0N, ZRDG_CVGQ)

!$ACDC }

!$ACDC PARALLEL,TARGET=OpenMP/OpenMPSingleColumn/OpenACCSingleColumn,NAME=ZRDG_LCVQ {

DO JLEV = 1, YDCPG_OPTS%KFLEVG
  DO JLON = YDCPG_BNDS%KIDIA, YDCPG_BNDS%KFDIA
    ZRDG_LCVQ (JLON, JLEV) = ZRDG_CVGQ (JLON, JLEV)
  ENDDO
ENDDO

DO JLON=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
  ZFLU_QSATS(JLON)=0.0_JPRB
ENDDO

!$ACDC }

END ASSOCIATE
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('APL_ARPEGE',1,ZHOOK_HANDLE)

END SUBROUTINE APL_ARPEGE

